<?php

/*
	Plugin Name: q2apro Booking System
	Plugin URI: http://www.q2apro.com/plugins/bookingsystem
*/

	return array(

		// default
		'enable_plugin' => 'Enable Plugin',
		'minimum_level' => 'Level to access this page:',
		'plugin_disabled' => 'Plugin has been disabled.',
		'access_forbidden' => 'Access forbidden.',
		'plugin_page_url' => 'Open page in forum:',
		'contact' => 'For questions please visit ^1q2apro.com^2',

		// time formats
		'datetime_format' => 'DD.MM.YYYY hh:mm', // humans
		'datetime_format_js' => 'd.m.y h:s',
		'datetime_format_php' => 'd.m.Y H:i',
		'datetime_format_php_fullhour' => 'd.m.Y H:00',
		'date_format' => 'DD.MM.YYYY', // humans
		'date_format_php' => 'd.m.Y', // http://php.net/manual/de/function.date.php
		'date_format_momentjs' => 'DD.MM.YYYY', // http://momentjs.com/docs/#/displaying/format/
		'date_format_calendarweek' => 'YYYY MM', // fullcalendar title on booking page

		// plugin general
		'meta_description' => 'Order instantly the personal service that you need. When and where you like it!',
		'contractor' => 'Provider',
		'client' => 'Client',
		'member' => 'Member',
		'user' => 'User',
		'nav_main_contractor' => 'Find service', // main menu on top
		'book_service_btn' => 'Book service',
		'admin_maillist' => 'E-mail listing',
		'optional' => 'optional',
		'additional' => 'additional',
		'fee' => 'fee',
		'feepay' => 'Fee payment',
		'btn_submit' => 'Send',
		'btn_create' => 'Create',
		'order' => 'Order',
		'protocol' => 'protocol',
		'event' => 'event', // Event
		'eventid' => 'Event No.', // Event-ID
		'date' => 'Date',
		'time' => 'Time',
		'timeabbr' => 'h', // e.g. 10:00 Uhr
		'hourabbr' => 'h', // e.g. h
		'min' => 'min', // minutes abbreviation
		'timespan' => 'period',
		'price' => 'price',
		'sum' => 'Sum',
		'anonymous' => 'anonymous',
		'length' => 'length',
		'start' => 'Start',
		'end' => 'End',
		'eventdetails' => 'Event details',
		'attachments' => 'Attachments',
		'bookingnr' => 'Booking No.',
		'bookingtotal' => 'Total booking price',
		'ev_former' => 'Former',
		'ev_new' => 'New',
		'ev_until' => 'until',
		'reason' => 'Reason',
		'eventproposal' => 'event proposal',
		'file' => 'file',
		'absent' => 'absent',
		'reserved' => 'reserved',
		'already_reserved' => 'already reserved',
		'booked' => 'booked',
		'completed' => 'completed',
		'event_completed' => 'completed',
		'paid' => 'paid',
		'confirmed' => 'confirmed',
		'save_btn' => 'Save',
		'saveall_btn' => 'Save all',
		'from' => 'from', // e.g. paid from
		'address' => 'address',
		'location' => 'location',
		'portfolio' => 'portfolio',
		'birthdate' => 'birth date',
		'deposit' => 'deposit', // a fixed amount can be bought by client, and he can use this deposit money to book contractors
		'balance' => 'balance',
		'accountbalance' => 'account balance',
		'balance_plus' => 'Credit',
		'balance_minus' => 'Deficit',
		'clearance' => 'Account clearance', // to balance the account to zero
		'paymentin' => 'Receipt of payment', // Zahlungseingang
		'paymentout' => 'Outgoing payment', // Zahlungsausgang
		'appt' => 'booking',
		'appts' => 'bookings',
		'myappts' => 'My bookings',
		'appt_from' => 'booking from',
		'sendmsg_btn' => 'Send message',
		'message' => 'Message',
		'messages' => 'Messages',
		'per' => 'per', // price per hour
		'status' => 'status',
		'name' => 'name',
		'payamount' => 'Pay amount',
		'password' => 'Password',
		'forum' => 'Knowledge forum',
		'forum_short' => 'forum',
		'notallowed' => 'Not allowed',
		'error' => 'Error',
		'only' => 'only', // price
		'notspecified' => 'not specified',
		'myaccount' => 'My account',
		'created' => 'Created',
		'or' => 'or',
		'value' => 'value',
		'accepted' => 'accepted',
		'title' => 'title',

		// week
		'monday' => 'Monday',
		'tuesday' => 'Tuesday',
		'wednesday' => 'wednesday',
		'thursday' => 'Thursday',
		'friday' => 'Friday',
		'saturday' => 'Saturaay',
		'sunday' => 'Sunday',
		'mon' => 'Mon',
		'tue' => 'Tue',
		'wed' => 'Wed',
		'thu' => 'Thu',
		'fri' => 'Fri',
		'sat' => 'Sat',
		'sun' => 'Sun',

		// qa-plugin.php
		'no_bookings' => 'No bookings found.',
		'prefered_times' => 'Prefered Times',
		'prefered_times_none' => 'No times specified',
		'appts_with' => 'Appointments with',
		'appt_paid' => 'paid',
		'hello' => 'Hello',
		'thxpaid' => 'Thank you for your payment',
		'mail_thxpaid' => 'Thank you for your payment.',
		'mail_willcontact' => 'has to confirm the booking time. The service provider will contact you.', // person ...
		'mail_askdetails' => 'Have you already entered your booking details?',
		'mail_btndetails' => 'Enter booking details',
		'mail_yourappts' => 'Your bookings are:',
		'mail_canmessage' => 'You can ^1send a message^2 to the service provider at any time.',
		'mail_greetings' => 'Best regards',
		'mail_greeter' => 'Kyga Team',
		'notmentioned' => 'not mentioned',
		'confirm_appts' => 'Confirm bookings',
		'directmessage' => 'direct message',
		'telephone' => 'Phone',
		'telephone_abbr' => 'Tel.',
		'mailtocon_custopaid' => 'the client ~~~ has paid the booking.', // leave ~~~, this will be replaced by the client name
		'mailtocon_doconfirm' => 'Please confirm the booking times in your ^1booking schedule^2.',
		'mailtocon_contactcusto' => 'Please contact the client: ',
		'mailtocon_bookdetails' => 'The times of booking n° ~~~ are:', // leave ~~~, this will be replaced by the booking id
		'eventsavailable' => 'New open Bookings available', // email subject
		'mail_neweventsav' => 'There are new bookings and we have not yet found a service provider who takes over the work. You can take over this job at:',
		'mail_gotoevents' => 'Go to booking',
		'mail_eventaccepted_subject' => 'Appointment accepted by ~~~', // email subject, leave ~~~, this will be replaced by the contractorname
		'mail_eventaccepted' => 'Your appointment was accepted by ~~~ and takes place.', // leave ~~~, this will be replaced by the contractorname
		'mail_seeyourschedule' => 'Here you can open your schedule',
		'mail_eventrejected_subject' => 'Appointment declined by ~~~', // email subject, leave ~~~, this will be replaced by the contractorname
		'mail_eventrejected' => 'Unfortunately, the service provider ~~~ cannot keep your booking.', // leave ~~~, this will be replaced by the contractorname
		'mail_rejectreason' => 'Reason: „~~~“', // leave ~~~, this will be replaced
		'mail_othersinformed' => 'Other service providers got informed to take over the booking. One of them will contact you shortly.',
		'mail_newtime_subject' => 'New times for your appointments',
		'mail_newtime' => 'There are new suggested times for your appointments. Please accept one of the times:',
		'mail_clearancesuccess' => 'Account clearance successful', // in case of negative balance the client pays
		'mail_clearanceintro' => 'Thank you for your payment in the amount of ~~~. Now your account is balanced.', // leave ~~~
		'mail_depositsuccess_subject' => 'Credit credited',
		'mail_depositsuccess' => 'We have received your payment, thank you. A credit in the amount of ~~~ was added to your account.',
		'mail_bookcontractors' => 'You can use the credit now to ^1book service providers^2 of your choice.',

		// events
		'evname_openevent' => 'Client initiated order',
		'evname_openevent2' => 'open', // Bestellung
		'evname_reserved' => 'Client reserved time',
		'evname_reserved2' => 'Time reserved',
		'evname_paid' => 'Client has paid',
		'evname_changed' => 'Booking time changed',
		'evname_setdetails' => 'Client defines booking details',
		'evname_setdetails2' => 'Booking details specified',
		'evname_consetdetails' => 'Service provider defines booking details',
		'evname_consetdetails2' => 'Booking details defined',
		'evname_findtime' => 'Time gets negotiated',
		'evname_findtime2' => 'Time is in negotiation',
		'evname_accepted' => 'Booking time agreed on and appointment takes place',
		'evname_accepted2' => 'Appointment takes place',
		'evname_rejected' => 'Service provider rejects appointment',
		'evname_rejected2' => 'Appointment rejected',
		'evname_conneeded' => 'We try to find a new service provider for your booking',
		'evname_conneeded2' => 'Service provider is being searched',
		'evname_completed' => 'Service provider completes job',
		'evname_completed2' => 'Job completed',
		'evname_rated' => 'Client rated booking',
		'evname_rated2' => 'Booking rated',
		'evname_available' => 'Contractor available',
		'view_appt' => 'View booking',

		// ratings
		'rating' => 'Rating',
		'ratings' => 'Ratings',
		'ratingtext' => 'Rating details',
		'noratings' => 'No ratings yet.',
		'comment' => 'Comment',

		// layer
		'profile' => 'Profile',
		'calendar' => 'Calendar',
		'yourcalendar' => 'Your calendar',
		'menubtn_con_week' => 'Week times',
		'menubtn_con_balance' => 'Fee',
		'menubtn_con_info' => 'Info',
		'menubtn_cli_ratings' => 'Rate',
		'menubtn_cli_balance' => 'Account overview',
		'menubtn_cli_profile' => 'Profile',
		'menubtn_balance' => 'Fees',
		'menubtn_con_offers' => 'Offers',
		'payments' => 'Payments',
		'contractors' => 'Service provider',
		'clients' => 'Clients',
		'menubtn_messages' => '✉',
		'topright_next_appt' => 'Next appointment',
		'topright_no_appt' => 'no appointment',
		'topright_msg' => 'Messages',
		'admin' => 'Admin',
		'upcomingappts' => 'Upcoming appointments',
		'earningbookings' => 'Earnings with last 30 days',
		'recentrequests' => 'Your recent service requests',

		// page general
		'page_deactive' => 'This page has been deactivated.',
		'page_noaccess' => 'Not allowed to access.',
		'fee_balance' => 'Balance',

		// page adminbalance
		'adminbal_title' => 'Admin: Fees',
		'income' => 'Income',
		'fee_payout' => 'Payout of Fees',
		'fee_lastmonth' => 'last month',
		'fee_sum' => 'SUM',
		'forcontractor' => 'for service provider',

		// page admincalendar
		'admincal_title' => 'Admin: All Bookings',
		'admincal_perhaps' => 'maybe',
		'admincal_unpaid' => 'not paid',
		'admincal_from' => 'from',
		'admincal_by' => 'by', // person
		'btnupdate_appt' => 'update appointments',
		'admincal_nochanges' => 'No changes were made.',
		'updatesuccess' => 'Appointment updated successfully.',
		'reloadpage' => 'Reloading page.',
		'cal_warnonleave' => 'Appointments were changed but not saved. Do you really want to leave the page?',

		// page adminclients + admincontractors
		'admincli_title' => 'Admin: Clients',
		'admincon_title' => 'Admin: Service Providers',
		'admin_tab_userdata' => 'User data',
		'admin_tab_birthdate' => 'Birthday',
		'admin_tab_address' => 'Address',
		'admin_tab_price' => 'Price',
		'admin_tab_absent' => 'Absence (e. g. holidays)',
		'paymethod' => 'Payment method',
		'admin_tab_spec' => 'Specialisation',
		'admin_tab_portfolio' => 'Portfolio',
		'email' => 'Email',
		'admin_sendmsg' => 'Write message',
		'forum_profile' => 'Forum profil',
		'pointstatistic' => 'Point statistics',
		'forumstatistic' => 'Forum statistics',
		'forumactivity' => 'Forum activity',
		'bookingsite' => 'Booking page',
		'nolocationset' => 'No location set.',
		'admin_open_gmaps' => 'Open in Google Maps.',
		'approve' => 'approve',
		'approved' => 'approved',
		'doapprove' => 'approve',
		'dounlock' => 'unlock',
		'removeapprove' => 'Remove approval',
		'disapprove' => 'disapprove',
		'disapproved' => 'disapproved',
		'removedisapprove' => 'remove disapproval',
		'bookingvolume' => 'Booking volume',

		// page admineventedit
		'admineved_title' => 'Admin: Edit event', // appointment
		'admineved_missingid' => 'Please enter the event ID.',
		'admineved_success' => 'Event updated successfully.',
		'admineved_back' => 'Back to the event list.',

		// page adminmessages
		'adminmsg_title' => 'Admin: All Messages',
		'adminmsg_from' => 'From',
		'adminmsg_to' => 'To',
		'delete' => 'delete',
		'nomessages' => 'No messages yet.',
		'adminmsg_confirmdel' => 'Really delete?',
		'message_deleted' => 'Message deleted.',

		// page adminpayments
		'adminpaym_title' => 'Admin: Payments',
		'adminpaym_paymethod' => 'Payment method',
		'adminpaym_bank' => 'Bank',
		'adminpaym_paypal' => 'Paypal',
		'adminpaym_creditnote' => 'Deposit',
		'adminpaym_elimination' => 'Elimination', // Ausbuchung
		'adminpaym_paid' => 'Paid',
		'adminpaym_timestamp' => 'Timestamp',
		'adminpaym_paybookid' => 'Booking Nr. (if paid)',
		'adminpaym_payid' => 'Payment ID',
		'adminpaym_deposit' => 'Deposit',
		'adminpaym_validate' => 'validate',
		'adminpaym_delete' => 'delete',
		'adminpaym_unpaid' => 'unpaid',
		'adminpaym_created' => 'Created payment',

		// page adminratings
		'adminrat_title' => 'Admin: Ratings',
		'rat_negativ' => 'negativ',
		'rat_neutral' => 'neutral',
		'rat_good' => 'good',
		'rat_verygood' => 'very good',
		'rat_excellent' => 'excellent',
		'adminrat_tab_client' => 'Customer',
		'adminrat_tab_contractor' => 'Service provider',

		// page adminschedule
		'adminsched_title' => 'Admin: Appointments',
		'apptcount' => 'Appointments that are not older than 30 days',
		'adminsched_id' => 'ID',
		'adminsched_price' => 'Price',
		'adminsched_contractor' => 'Service provider',
		'adminsched_client' => 'Customer',
		'adminsched_needs' => 'Order details',
		'adminsched_state' => 'Status',
		'adminsched_paidpaypal' => 'paid using Paypal',
		'adminsched_paidbank' => 'paid using bank transfer',
		'adminsched_paiddeposit' => 'paid using deposit',
		'hintincomplete1' => 'Add booking details and a note for completion',
		'hintincomplete2' => 'Complement booking details',
		'hintincomplete3' => 'Add a note for completion',
		'apptdetails' => 'Enter booking details',
		'adminsched_placeholder' => 'Add a note for completion',
		'adminsched_bookedon' => 'booked on',
		'adminsched_unit' => 'per unit',
		'adminsched_confirmdelete' => 'Really delete event',

		// page booking
		'bookservice' => 'Book time',
		'onlyregistered' => 'You can use this page only as logged-in user.',
		'noservice' => 'No service was chosen.',
		'con_notavailable' => 'This service provider is currently not available.',
		'notavailable' => 'not available',
		'needregisterlogin' => 'Please ^1login^2 or ^3register^4.',
		'needreglogin_service' => 'Please ^1login^2 or ^3register^4 to book a service.',
		'notpaid_click' => 'Booking with ~~~ not paid yet - Click to pay',
		'yourapptwith' => 'Your booking with',
		'openprofile' => 'View your profile',
		'preferedtimes' => 'Choose a time by clicking onto the calendar. If ^1colorful areas^2 are visible, you can only book those. Gray times are already taken or unavailable.',
		'preferedtimes_short' => 'Select the desired time by dragging the mouse onto the calendar.',
		'howtimesbymouse' => 'How you select times',
		'specify_fullname' => 'Please specify your complete name',
		'firstlastname' => 'First and last name',
		'specify_address' => 'Please specify your address.',
		'placeholder_addressexample' => 'e. g. Burger street 12, DK-80335 Copenhagen',
		'specify_birthdate' => 'Please specify your date of birth.',
		'specify_birthdate_page' => 'We also need your birthday',
		'placeholder_dateexample' => 'e. g. 1981-09-15',
		'pleasepay' => 'Please balance your account.',
		'yourbalance' => 'Your balance',
		'acceptterms' => 'I accept the ^1Terms and Conditions^2.',
		'askforterms' => 'Please accept the Terms and Conditions.',
		'btn_bookandpay' => 'Book service now',
		'earliesttomorrow' => 'The appointment can take place tomorrow at the earliest. Every service provider needs preparation time.',
		'notpast' => 'The appointment cannot be in the past.',
		'onlyfixedtimes' => 'The appointment must be within a blue area.',
		'depositafterbooking' => 'Your deposit afterwards',
		'depositempty' => 'Your deposit is used up with this booking. The remaining amount of \'+newbalancestr+\' has to be compensated.',
		'choosecaltime' => 'Please choose a time in the calendar.',
		'specify_email' => 'Please specify your email address.',
		'specify_validemail' => 'Please specify a valid email address.',
		'specify_password' => 'Please enter a password.',
		'contractor_notexist' => 'This service provider already exists.',
		'user_notexist' => 'This user does not exist.',
		'calendarhelp' => 'Help with the calendar?',
		'distance' => 'Distance',
		'time' => 'Time',
		'timebycar' => 'Travel time by car',
		'showmap' => 'Show map',
		'hidemap' => 'Hide map',
		'start' => 'Start',
		'target' => 'Target',
		'updatebtn' => 'Update',
		'specialoffers' => 'Offers',
		'offer_validuntil' => 'Offer valid until',
		'executiontime' => 'Execution time',
		'bookofferfor' => 'Book offer for',
		'choosedaytime' => 'Please choose day and time:',
		'chooseday' => 'Please choose the day:',
		'approx' => 'ca.',
		'btn_bookoffer' => 'Book offer now',
		'intotal' => 'in total',
		'incl_taxes' => 'incl. all taxes',
		'shortlink_profile' => 'Shortlink to profile',
		'order_imp' => 'Order now',
		'order_for' => 'Book for', // price follows
		'vcardlink' => 'Download vCard',
		'createlogin' => 'Create Login',
		'nopriceset' => 'No hourly price set',

		// page clientbalance - obsolete
		'clibal_title' => 'Balance the Deficit',
		'clibal_title_overview' => 'Account overview',
		'paywith' => 'Payment per',
		'paywithpaypal' => 'Payment using Paypal',
		'paywithbank' => 'Payment using bank',
		'btn_paynow' => 'Pay now',
		'upcoming_appts' => 'Upcoming appointments',
		'event_paid' => 'Booking paid',
		'no_balanceminus' => 'No negative balance found.',
		'or_getdeposit' => 'Purchase ^1deposit^2 instead?',
		'pleasepaynext' => 'Pleases transfer next',
		'payto' => 'to',
		'payreceiver' => 'Receiver',
		'afterclearbal' => 'After receivment of the payment we confirm the balanced account. You receive an email from us.',
		'paypurpose' => 'pay purpose',
		'pay_clearance' => 'Clearance for',
		'pay_id' => 'Payment nr.',
		'connect_paypal' => 'Connecting to PayPal …',
		'pleasewait' => 'Please wait …',
		'paypal_js' => 'Your browser does not use Javascript, please click on the following button to continue the transaction.',

		// page clientcalendar + contractorcalendar
		'clical_title' => 'Calendar',
		'notpaid_pay' => 'not paid yet - click to pay',
		'notpaidyet' => 'not paid yet',
		'listclients' => 'Contact current service providers',
		'embed' => 'Embed',
		'embedcalendar' => 'You can embed your calendar into Google Calender, Outlook, Thunderbird etc. Simply import the link as external calendar.',
		'embedcalendar_2' => 'Please look into the manual of the according program.',
		'instructions' => 'Instructions',
		'hints' => 'Hints',
		'calguide_google' => 'Instructions for Google Calendar',
		'calguide_outlook' => 'Instructions for Outlook',
		'calguide_thunderbird' => 'Instructions for Thunderbird/Lightning',
		'gcal_hint1' => 'To share your Google Calendar, you have to set its settings to "Public" and set the event details as hidden.',
		'gcal_hint2' => 'Your "Calendar ID" you find more below at "Calendar Details" in Google. This ID you have to enter above!',
		'gcal_hint3' => 'Be sure that your events in Google Calendar do always have the status "busy". If your events have the status "available", then they will not be shown in our calendar.',
		'screenshot' => 'Screenshot',
		'embedcal' => 'Embed calendar',
		'import' => 'Import',
		'export' => 'Export',
		'google_connect' => 'Connect with Google',
		'google_hint' => 'You can integrate your ^1Google Calendar^2 events with us. This way your customers see immediately, at which time you are not available.',
		'google_hint_client' => 'You can share your ^1Google Calendar^2 events with us. This way you see your own appointments when booking someone in another calendar, and overlaps are not possible anymore.',
		'google_nodetails' => 'The events are only shown with times, no details will be shown publicly.',
		'clipboard_copied' => 'Copied link. Now you can insert the link with the right mouse button.',
		'googlecal_link' => 'Link to your Google Calendar',
		'eventtypes' => 'Event types',
		'copylink' => 'Copy link',
		'openlink' => 'Open link',

		// page clientdeposit - obsolete
		'clidep_paytitle' => 'Payment of deposit',
		'clidep_noorder' => 'We could not find any order.',
		'clidep_title' => 'Purchase deposit',
		'clidep_intro' => 'With the deposit you can book every service provider immediately and you can control your costs better.',
		'recent_balance' => 'Your current ^1account balance^2 amounts to:',
		'set_deposit' => 'Set deposit',
		'set_slider' => 'Choose your deposit with the slider',
		'paymethodchoice' => 'Choose the payment method',
		'banktransfer' => 'bank transfer',
		'bankhint' => 'You transfer the amount by bank. Receipt after 1 - 2 days.',
		'paypalhint' => 'After the successful payment we add the deposit to your account.',
		'depositback' => 'We return your deposit at any time. For this purpose, it is sufficient to inform us by email.',
		'depositset' => 'You have a deposit of ~~~ specified.', // leave ~~~
		'paydeposit' => 'Pay deposit',
		'clidep_mail_subject' => 'Order of deposit',
		'clidep_mail_body1' => 'You have ordered a deposit of ~~~.',
		'clidep_mail_body2' => 'Please pay the amount of ~~~, only afterwards the deposit is valid.',
		'paymentalways' => 'The payment you can carry out at any time ^1here (make payment)^2.',
		'pay_deposit_for' => 'Deposit for',
		'aftercleardeposit' => 'After receipt of the payment your deposit will be confirmed. You will receive an email from us.',

		// page userprofile
		'cliprof_title' => '',
		'startcredit_activated' => 'Deposit activated for', // admin info mail
		'user_registered' => 'New member registered',
		'registered' => 'registered',
		'contracted' => 'contracted',
		'can_photoupload' => 'Here you can upload a ^1personal profile photo^2.',
		'reward_profile' => 'Fill out your profile and for your first booking your receive a deposit of',
		'placeholder_phone' => 'for contact and callbacks',
		'skypename' => 'Skype name',
		'change_pwmail' => 'Change email or password',
		'data_updated' => 'Information updated',
		'startcredit_granted' => 'Your deposit was credited.',
		'next_book_contractor' => 'Next you can book a ^1service provider^2.',
		'data_incompleted' => 'The Information is not complete, we could not save.',
		'offershint' => 'After the registration you can create service packages with separate prices.',
		'getbookingbutton' => 'Booking button for your website',

		// page clientratings
		'clirat_title' => 'Ratings of Service Providers',
		'clirat_mail' => 'Your booking was rated',
		'clirat_content' => '~name~ has rated you on ~date~:', // leave ~name~ and ~date~
		'see_ratings' => 'View all your ratings here',
		'clirat_contactus' => 'You can contact us at any time if you are not satisfied with the service provider',
		'clirat_dorate' => 'Please rate each appointment that you had with a service provider. Be honest and critical, because only then the service provider can improve.',
		'clirat_prevratings' => 'Previous Ratings',
		'clirat_placeholder_rat' => 'Insert a comment …',
		'noapptyet' => 'You have not had a booking yet.',
		'ratingsaved' => 'Rating was saved, thank you.',

		// page clientschedule
		'clisched_title' => 'Schedule',
		'specify_needs' => 'Please specify timely the booking details for all your appointments, so that the service providers can prepare themselves.',
		'singleappt' => 'Single Appointment',
		'onlysingleappt' => 'You only see a single appointment. Here you can ^1view all your schedule^2.',
		'noappts' => 'Currently no bookings.',
		'noeventsfound' => 'Could not find a booking.',
		'uploadfile' => 'Upload file',
		'uploadfile_another' => 'Upload another file',
		'uploadsuccess' => 'Upload successful ',
		'pay_tooltip' => 'Booking is not paid yet. Click here to pay.',
		'pay_appt' => 'Pay appointment',
		'savesuccess' => 'Saved successfully',
		'filesizewarning' => 'Maximal fil size is 8 MB. Please reduce your file size or zip it.',
		'completed_button' => 'Confirm the completion of the booking',
		'completed_tooltip' => 'Booking was completed and paid.',

		// page contractorbalance
		'conbal_title' => 'Fee',
		'con_noapptyet' => 'You do not have any bookings yet.',
		'apptcompleted_hint' => 'A booking is regarded as completed as soon as the customer confirms.',
		'conbal_recent' => 'Recent',
		'conbal_onlyadmin' => 'Only for Admin',
		'conbal_turnover' => 'Turnover',
		'conbal_fees' => 'Fees',
		'conbal_earnings' => 'Earnings',

		// page contractorcalendar
		'concal_title' => 'Calendar',
		'change_appt' => 'Change appointments',
		'change_appt_hint1' => 'You can move each appointment and even change its duration (touch the dragger in the week view). Note that the customer has to pay the difference or receives money back.',
		'change_appt_hint2' => 'Important',
		'change_appt_hint3' => 'Every change of the time has to be documented by ^1sending a message to the customer^2.',
		'contact_clients' => 'Contact customer',
		'booktimespan' => 'Book this timespan',
		'nochanges' => 'No changes made.',
		'reloadingpage' => 'Reloading page.',

		// page contractorinfo
		// please edit booker-page-contractorinfo.php directly
		// this information is flexible depeding on the FAQ and requirements of the project

		// page contractorlist
		'conli_title' => 'Book service',
		'voucher_until' => 'Valid until',
		'voucher_detail' => 'For your first booking you receive ~~~ deposit.',
		'registerforbooking' => 'To book a service provider you have to ^1register quickly^2.',
		'registerclient' => 'Register as customer',
		'moneybackguarantee' => 'Monay-Back-Guarantee',
		'moneybackdetail' => 'If you are not satisfied with the booked service, you get your money back. Without any “but“.', // not implemented
		'positiveratings' => 'Positiv Ratings',
		'bookfor' => 'Book for', // price
		'customerratings' => 'Current customer ratings',
		'recommendcontractor' => 'Suggest service provider',
		'bestprice' => 'Best price',
		'guaranteed' => 'guaranteed',
		'bestpriceguarantee' => 'Best Price Guarantee',
		'weguarantee' => 'We guarantee the best price for the chosen service of this provider. If you find the offer cheaper in the Internet, we will adapt the price immediately.',
		'moneywithhold' => 'Your money is safe',
		'withholdguarantee' => 'The service provider receives your money only, if you confirm the booking as completed. Until then we hold your money back.', // not implemented
		'clickmoreservices' => 'Click here to find more service providers in this field.',

		// page userprofile
		'nav_login' => 'Login',
		'conpro_title' => 'Provider profile',
		'yourprofile' => 'Your profile',
		'douploadphoto' => 'A photo of you is missing.', // Bitte ein persönliches Foto hochladen.
		'facerequired' => 'Your face must be visible.',
		'forcustomertrust' => 'Important for customer trust.',
		'accountstatus' => 'Account status',
		'verified' => 'verified',
		'we_verify' => 'After your registration we verify your account and unlock it within 24 hours.',
		'available' => 'Available',
		'absent_placeholder' => 'e. g. 2016-05-01, 2016-06-15 - 2016-06-20',
		'absent_tooltip' => 'Enter single days as yyyy.mm.dd. Divide several times by comma. Enter a timespan with yyyy.mm.dd - yyyy.mm.dd.',
		'weekdays_head' => 'Not availabe weekdays',
		'public_data' => 'Public data',
		'internal_data' => 'Internal data',
		'basic_data' => 'Basic data',
		'contractor_data' => 'Service provider data',
		'contractor_data_qu' => 'Do you offer a service?',
		'yourservice_short' => 'Your service',
		'placeholder_service' => 'e. g. lawyer for tenancy law',
		'yourservice_desc' => 'Description / Portfolio',
		'yourservice_hint' => 'Describe the service you offer which will be published. ^1Only Premium:^2 Add photos and videos as well as your contact data.',
		'upload_img' => 'Upload image',
		'insert_img' => 'Insert image',
		'textlength_warn' => 'Warning: 8000 characters exceeded.',
		'placeholder_paypal' => 'for all payments',
		'placeholder_address' => 'for contract and statements',
		'paypal_iban' => 'Paypal or IBAN',
		'skype' => 'Skype',
		'set_price' => 'Please specify your price.',
		'your_price' => 'Your price',
		'hour' => 'hour',
		'hours' => 'hours',
		'per_hour' => 'per hour',
		'filesizewarning_exact' => 'Your file has a size of \'+img_size+\' Mb which is too big. Maximal \'+maximg_size+\' Mb are allowed.',
		'payout' => 'Payout',
		'newcontractor' => 'New Contractor',
		'newcon_mailsubject' => 'New contractor registered',
		'changeavatar' => 'Upload another profile photo',
		'removeavatar' => 'Remove profile photo',
		'removeavatar_confirm' => 'Do you really want to remove your profile photo?',
		'commission' => 'Commission',
		'finish_registration_btn' => 'Finish registration',
		'company' => 'Company name',

		// page contractorratings
		'conrat_title' => 'Customer Ratings',
		'conrat_tellclients' => 'Please advice your customers to rate you after each appointment. Here you find all your previous ratings.',
		'clientmail_auto' => 'The customer receives an email automatically.',
		'conrat_notpaidyet' => 'Not paid yet, the appointment will maybe not take place.',
		'manage_event_btn' => 'Manage the time',
		'add_details' => 'If the appointment details are not specified, please add them.',

		// page contractorschedule
		'consched_title' => 'Schedule',
		'protocol_note' => 'This is the final note of the service provider',
		'mail_concompleted' => 'has announced your appointment as completed.', // person ...
		'please_rate' => 'Please rate the service.',
		'torating' => 'go to Ratings',
		'bookingfrom' => 'Booking from',
		'confirmcomplete_btn' => 'Complete booking',
		'apptinpast' => 'Appointment is in past',
		'customerconfirmneeded' => 'The customer has not yet confirmed the completion of the appointment.',

		// page contractorweek
		'conweek_title' => 'My Times',
		'setup_times' => 'Setup times',
		'block_times' => 'Block times',
		'week_hint0' => 'If customers are supposed to book your service only at certain times, you can specify them here.',
		'week_hint1' => 'This can lead to less customers, because the customer cannot book that flexible anymore.',
		'week_hint2' => 'We recommend to not set up fixed times. You can change each incoming booking in time and coorindate it with the customer.',
		'week_hint3' => 'The times can be changed at any time.',
		'week_hint4' => '- Selection by click and dragging the mouse.',
		'week_hint5' => '- One click onto the selected time will remove it again.',
		'week_updatesuccess' => 'Week times updated successfully.',
		'week_warnonleave' => 'Week times were not saved yet. Really leave page?',
		'preview' => 'Preview',
		'saveweek_btn' => 'Save week times',
		'favoritetimes' => 'Fixed times',

		// page eventhistory
		'evhis_title' => 'Event History',
		'put_eventid' => 'Please specify the event id.',
		'eventhistoryfor' => 'History for event nr. ~eventid~',
		'recent_eventdata' => 'Current event data',
		'intotal' => 'in total',

		// page ipn
		'payment_success' => 'Payment successful',
		'payment_success_message' => 'Thanks for your payment. You are now Premium member at Kvanto.lt and can enjoy all advantages!',
		'payment_fail_title' => 'Payment was not made',
		'payment_fail' => 'Unfortunately the payment was cancelled or there was another problem.',
		'mail_paid1' => 'We have received your payment and the service provider is available for you. S/he will contact you shortly.',
		'mail_paid2' => 'Please specify your booking details next',
		'clearance_success' => 'We have received your payment and your account is now balanced. Thank you.',
		'deposit_success' => 'We have received your payment and your deposit is active now. Thank you.',
		'trypaymentagain' => 'You can try the payment again ^1by clicking here^2.',

		// page mbcontact
		'contact_intro' => 'Send us a message here. We will contact you as soon as possible.',
		'yourmessage' => 'Your message',
		'yourname' => 'Your name',
		'youremail' => 'Your email',
		'contactto' => 'Contact to',

		// page mbmessages
		'msg_title' => 'Private Messages',
		'msgfrom' => 'Message from',
		'msganswer' => 'Reply to this message',
		'msglist' => 'List of all messages',
		'msgselferror' => 'Wait, you should not send yourself a message.',
		'msgerror1' => 'You cannot send a message yet.',
		'msgerror2' => 'This member cannot receive messages.',
		'nameunknown' => 'Name unknown',
		'msgto' => 'Message to',
		'yourmsgto' => 'Your message to',
		'msgtocontractor' => 'Your message will be delivered to the service provider by e-mail.',
		'msgtoclient' => 'Your message will be delivered to the client by e-mail.',
		'msgtooperator' => 'Your message will be delivered to us by e-mail.',
		'emailsecret' => 'Your e-mail address is kept secret. ',
		'copysaved' => 'A copy of the message is saved on our server.',
		'msg_to_us' => 'us',
		'prevmessages' => 'Previous messages',
		'msgcontent' => 'Content',
		'sent' => 'Sent',
		'received' => 'Received',
		'insertmsg' => 'Insert message …',
		'msgsent' => 'Your message has been sent.',

		// page mbupload
		'filetype_disallowed' => 'Filetype not allowed',
		'filename_exists' => 'File name already exists',
		'nouploadfolder' => 'Upload folder does not exist.',

		// page pay
		'pay_title' => 'Payment',
		'deducting' => 'deducting', // minus deposit (positive balance)
		'so_only' => 'so only', // payment minus x, so only ...
		'reservation_from' => 'Reservation from',
		'youwerebooked' => 'You were booked by ~name~ (booking n° ~bookid~) as follows', // leave ~name~ and ~bookid~
		'paidbydeposit' => 'The booking was paid by deposit and takes place.',
		'contactclient' => 'Please contact the customer.',
		'appts_probexist' => 'The customer has probably entered the booking details, please look into your ^1schedule^2.',
		'confirmtime' => 'Please confirm the appointment in your schedule',
		'waitforpay' => 'Next we have to wait for the receipt of the payment.',
		'appts_reserved' => 'Appointments with ~~~ reserved',
		'appts_booked' => 'Appointments with ~~~ confirmed', // confirmed
		'bookconfirmed_deposit' => 'The amount was balanced using your deposit. The booking is valid.',
		'cansendmsg' => 'If necessary you can send a ^1message to the service provider^2.',
		'pleasepayamount' => 'Please pay the amount of ~~~, only then the booking is valid.', // leave ~~~
		'bookedby' => 'You have booked a service with ~name~.', // leave ~name~
		'booking_bookid' => 'Booking n° ~bookid~.', // leave ~bookid~
		'booking_success' => 'Booking successful',
		'booking_thanks' => 'Thank your for your booking.',
		'appts_activated' => '^1Your appointments^2 have been activated.',
		'confirmwassent' => 'You have received a confirmation email.',
		'con_willcontact' => 'The service provider ~~~ will contact you shortly.',
		'put_details' => 'Insert the booking details next:',
		'con_contactbefore' => 'If you wish, you can contact the service provider in advance',
		'goodluck' => 'Good luck!',
		'confirmpaymail' => 'After receipt of the payment your booking will be confirmed via e-mail.',
		'servicefor' => 'Service for ~client~ by ~contractor~', // leave ~~
		'paybooking' => 'Pay the booking',
		'confirmbooking' => 'Confirm booking',
		'nobookingchosen' => 'No booking was chosen.',
		'nobookingfound' => 'No booking was found.',
		'chosentimes' => 'Chosen times',
		'chosenoffer' => 'Chosen offer',
		'remainingdeposit' => 'Remaining deposit',
		'bookcontractor' => 'Book service provider',
		'bookamount' => 'Booking amount',
		'paywithinday' => 'You have to make the payment within 24 hours, otherwise the booking gets cancelled.',
		'bankpayhint' => 'You transfer the payment amount by bank. Only when the payment has been received, your booking gets confirmed.',
		'paypalpayhint' => 'Your appointment gets confirmed immediately. The chosen time gets reserved for you.',
		'paymillpayhint' => 'Your appointment gets confirmed immediately. The chosen time gets reserved for you.',
		'btn_booknow' => 'Book now',
		'verification' => 'Verification',
		'paymentwithprovider' => 'Please pay the booked service only after it has been performed. The payment goes directly to the service provider, never to us.',
		'providergetscontact' => 'In the next step, the service provider receives your contact data, confirms your chosen time and contacts you.',
		'verification_hint1' => 'To verify bookings on our platform, we ask every user to insert his/her credit card or bank details one time.',
		'verification_hint2' => 'Only for verification purposes. We <b>never charge you</b>.',
		'verification_placeholder' => 'e. g. 4567 8912 4556 1234 2547',
		'verification_error' => 'Error: Credit card not correct',
		'verification_success' => 'Verification successful',
		'verification_done' => 'Thanks for your verification',

		// contratorlist search
		'search_results' => 'Search results',
		'found' => 'found',
		'search_label' => 'Service search',
		'searchlocation_label' => 'Limit to location',
		'all_locations' => 'All places',
		'search_placeholder' => 'Search service, profession or name',
		'search_clear' => 'Clear Search',
		'nothing_found' => 'Could not find anything to your query.',
		'newest_contractors' => 'Latest service providers',
		'random_contractors' => 'Random service providers',
		'alphabetic_contractors' => 'List of all service providers (alphabetic)',
		'showall_contractors_btn' => 'Show all service providers',
		'all_contractors' => 'All service providers',

		// page forumprofile
		'answer' => 'Answer',
		'answers' => 'Answers',
		'question' => 'Question',
		'questions' => 'Questions',
		'comment' => 'Comment',
		'comments' => 'Comments',
		'bestanswers' => 'Best Answers',
		'votesreceived' => 'Upvotes',
		'bestanswer_iconhover' => 'Awards for best answers',
		'thumbsup_iconhover' => 'Received votes',
		'newestanswers' => 'Recent answers',
		'noansweryet' => 'No answers yet.',
		'all_answers' => 'All answers',
		'reputation' => 'Reputation',
		'points' => 'Points',
		'weekhistory' => '7-day-history',
		'aboutme' => 'About me',
		'aboutus' => 'About us',
		'service' => 'Service',
		'inforum' => 'In Forum',
		'secret' => 'secret',
		'private_data' => 'private data',
		'nonpublic' => 'Not public',
		'needfulldata' => 'When you register as service provider, all information must be complete.',
		'fullnamehint' => 'A complete name is necessary, it creates trust.',
		'nocompanyname' => 'No fantasy name, no company name, your real name!',
		'addresshint' => 'Street and place in one line, divided by comma.',
		'execution' => 'Execution', // execution of the service
		'servicelocal' => 'at my place',
		'serviceonline' => 'Service online',
		'serviceatcustomer' => 'at the customer',
		'onlineonly' => 'Service only online',
		'onlinetoo' => 'Service online too',
		'perkm' => 'per km', // price per km
		'kmratehint' => 'Example: 10 km are', // example: 10 km are ...
		'eg' => 'e. g.', // abbreviation: for example
		'profilecreated' => 'Profil created successfully',
		'changemailpw' => 'Change e-mail or password',
		'specify_service' => 'Please specify your service.',
		'specify_portfolio' => 'Please add your portfolio, the description of your service.',
		'hourprice_hint' => 'Keep free if you do not want hourly booking.',

		// page contract
		'contract_title' => 'Contract between service provider and mediator',
		'contract_hint' => 'This is the last step to complete the registration as service provider. Please read the terms and accept the contract.',
		'conclude_contract' => 'Enter into contract',
		'registersuccess' => 'Registration successful',
		'newcontract_subject' => 'New service provider contract',
		'newcontract' => 'A new service provider has entered the service provider contract.',
		'contract_line_1' => 'Between the mediator',
		'contract_line_2' => 'and you as service provider',
		'contract_line_3' => 'is agreed',
		'contract_line_4' => 'The service provider declares agreement with the ^1Terms and Conditions for Service Providers^2. They are essential part of the agreement.',
		'contract_line_5' => 'The commission rate amounts to',
		'contract_line_6' => 'The agreement is valid only after the approval of the mediator.',
		'contract_line_7' => 'To conclude, please confirm',
		'contract_line_8' => 'I guarantee that all information specified are truthful and that I am in possession of all necessary permits to execute the services offered.',
		'contract_line_9' => 'I have read and understood the ^1Terms and Conditions for Service Providers^2 and confirm this agreement.',
		'contract_line_10' => 'I understand that when services are booked by customers, a contract is only concluded between service provider and customer. The operator of this platform is only mediator.',
		'contract_line_11' => 'By clicking on the button you enter a legally valid contract with us:',
		'contract_line_12' => 'Please select all checkboxes.',
		'contract_line_13' => 'We thank you for your registration as service provider.',
		'contract_line_14' => 'We will valid your information within the next 24 hours and unlock them.',
		'contract_line_15' => 'In case there is need of intervention or when problems occur, we will contact you.',

		// dropdown main menu
		'contractorslist' => 'List of all service providers',
		'forcontractors' => 'For service providers',
		'forclients' => 'For customers',
		'toptopics' => 'Main topics',

		// extra
		'motto' => 'Kvanto - Einer für alle, alle für einen',

		// page eventmanager
		'evman_title' => 'Event Manager',
		'events_available_title' => 'Available appointments',
		'events_allocated' => 'It seems that all available appointments are already taken.',
		'events_available' => 'The following appointments are not yet assigned to a service provider. You can take over the appointment.',
		'events_coordinate' => 'Appointments to be considered',
		'events_allocated_client' => 'It seems that all appointments has already been clarified.',
		'events_findtime' => 'The following appointments have to be coordinated in time:',
		'event_accepted_title' => 'Appointment accepted',
		'event_accepted' => 'You have accpeted appointment n° ~eventid~. Thank you!',
		'backtoeventlist' => 'continue to your schedule',
		'event_hint_title' => 'Hint to appointment',
		'event_hint' => 'The appointment n° ~eventid~ was already taken over by ^1~name~^2.',
		'event_backdetails' => 'back to the appointment details',
		'event_rejectreason' => 'Reason for rejection of the appointment', // or booking
		'rejectplaceholder' => 'State reason …',
		'reject_btn' => 'Reject',
		'event_rejected_title' => 'Appointment rejected',
		'event_rejected' => 'You have rejected the appointment n° ~eventid~. Another service provider will take over the appointment.',
		'already_rejected' => 'The appointment n° ~eventid~ was already rejected by you.',
		'newtimeproposed_title' => 'New Times for your appointment suggested',
		'proposenewtime' => 'Suggest a new time for appointment n° ~eventid~.',
		'eventduration' => 'Duration of appointment: ~eventduration~ min',
		'starttime' => 'Start time',
		'addmoreproposals' => 'Add more times for the appointment?',
		'propose_btn' => 'Suggest',
		'event_proposed_title' => 'Suggestion of new appointment times',
		'event_proposed' => 'You have suggested new times for appointment n° ~eventid~. The customer will be informed and can choose a time.',
		'event_iscompleted' => 'The appointment n° ~eventid~ was already completed.',
		'event_notpaidyet' => 'The appointment n° ~eventid~ has not been paid yet.',
		'event_alreadyaccepted' => 'The appointment n° ~eventid~ was already accepted.',
		'event_notexist' => 'This appointment does not exist.', // or booking
		'contractor_firstbooked' => 'Firstly booked service provider', // contractor who rejected the event
		'eventtime' => 'Appointment time',
		'reject_event_btn' => 'Reject appointment',
		'propose_event_btn' => 'Propose another time',
		'accept_event_btn' => 'Accept appointment',
		'eventproposals' => 'Suggestions for new appointment times',
		'clickconfirm' => 'Clicking on the time confirms it',

		// dropdown extras
		'pointsystem' => 'Point system',
		'monthbest' => 'Monthly best',
		'newsletter' => 'Newsletter',
		'yourquestions' => 'Your questions',
		'youranswers' => 'Your answers',
		'youractivity' => 'Your activities',

		// mini user statistic in top menu
		'points' => 'Points',
		'bestanswers' => 'Best answers',
		'votesreceived' => 'Votes received',

		// page userrecommend
		'recommend_hint' => 'Here you can propose a service provider that is not yet registered in our platform. We verify your input and inform the service provider afterwards by e-mail.',
		'placeholder_email_con' => 'E-mail of service provider',
		'newcon_suggested' => 'New service provider proposed',
		'back_services' => 'Back to startpage',
		'specify_fullname_con' => 'Please specify the name of the service provider.',
		'specify_email_con' => 'Please specify the e-mail of the service provider.',
		'specify_service_con' => 'Please specify the service of the service provider.',
		'specify_address_con' => 'Please specify the address of the service provider.',
		'userrecommended' => 'New service provider proposed, thanks a lot.',

		// page offercreate
		'offer_pagetitle' => 'Create offer',
		'offer_edit' => 'Edit offer',
		'offer_hint' => 'Here you can create an offer that exists independently from the hourly bookings. A photograph can, for instance, offer a wedding shooting for 1800 € instead of hourly rates.',
		'offer_hint_2' => 'You can create up to 5 offers. All offers will be shown publicly to customers on your ^1booking page^2.',
		'offertitle' => 'Offer title',
		'offertitle_placeholder' => 'e. g. Wedding photos incl. photo editing',
		'offerprice' => 'Price of the offer',
		'offerprice_placeholder' => 'e. g. 1800',
		'specify_price' => 'Please specify a price.',
		'duration' => 'Duration',
		'duration_placeholder' => 'e. g. 5',
		'specify_duration' => 'Please state the approximate duration.',
		'offerend' => 'Offer valid until',
		'offerend_hint' => 'Leave free if permanent.',
		'offerduration_hint' => 'Leave free if not determinable.',
		'description' => 'Description',
		'youroffer_hint' => 'Describe your offer detailed and add photos or videos. The booking will be possible directly on your booking page.',
		'new_offer' => 'New offer',
		'newcon_offer' => 'New offer created', // new offer created
		'flags' => 'Flags',
		'back_profile' => 'Back to profile',
		'back_offers' => 'Back to your offers',
		'another_offer' => 'Add another offer',
		'offer' => 'Offer',
		'offers' => 'Offers',
		'offer_activated' => 'Offer activated.',
		'offer_deactivated' => 'Offer deactivated.',
		'offer_created' => 'Offer created.',
		'offer_created_thx' => 'Offer created, thank you.',
		'offer_edited' => 'Offer updated.',
		'offer_deleted' => 'Offer deleted.',
		'offer_approved' => 'Offer approved.',
		'offer_disapproved' => 'Offer rejected.',
		'offer_tobechecked' => 'This offer is currently checked and will published soon.',
		'offer_gotdisapproved' => 'This offer did not comply with our guidelines.',
		'offer_gotdeleted' => 'This offer was deleted.',
		'offer_gotdeactivated' => 'This offer was deactivated.',
		'offer_expired' => 'This offer is already expired.',
		'premium_paid' => 'Premium paid.',
		'premium_activated' => 'Premium activated.',
		'options' => 'Options',
		'edit' => 'edit',
		'deactivate' => 'deactivate',
		'deactivated' => 'deactivated',
		'activate' => 'activate',
		'activated' => 'activated',
		'remove' => 'remove',
		'deleted' => 'deleted',
		'needcontractor' => 'You need to ^1become service provider^2 to create offers.',

		// page contractoroffers
		'conoff_title' => 'Your offers',
		'nooffers' => 'No offers created yet.',
		'table_created' => 'Created',
		'conoff_intro' => 'Here you see all your offers. You can create a new offer or edit existing ones.',
		'offer_create_btn' => 'Create new offer',

		// page clientrequests
		'clirequ_title' => 'Your service requests',
		'norequests' => 'No service request created yet.',
		'clirequ_intro' => 'Here you see your service requests including received quotes. You can always create more requests.',
		'request_create_btn' => 'Create service request',
		'newrequest_create_btn' => 'Create new request',
		'ownrequest_create_btn' => 'Create your own request',
		'request' => 'Request', // Gesuch
		'requests' => 'Requests',
		'bestprice' => 'Best Price',
		'priceoffers' => 'Price quote',
		'removerequest_confirm' => 'Do you really want to remove this request?',
		'choosebid' => 'Choose quote',
		'nobidsyet' => 'no quotes yet',
		'disabled' => 'deactivated',
		'notapprovedyet' => 'not approved yet',
		'ischecked' => 'is checked',
		'share' => 'Share',
		'sharefacebook' => 'Share on Facebook',
		'adminrequ_title' => 'Admin: Service requests',

		// page requestlist
		'all_requests' => 'All service requests',
		'my_requests' => 'My service requests',
		'reli_search_label' => 'Request search',
		'reli_search_placeholder' => 'e. g. handicraft', // Berlin
		'endsin' => 'ends in', // days, hours ...

		// page offerlist
		'all_offers' => 'All offers',
		'my_offers' => 'My offers',
		'offli_search_label' => 'Search for offer',
		'offli_search_placeholder' => 'e. g. repair',
		'ownoffer_create_btn' => 'Create your own offer',

		// page requestcreate
		'request_pagetitle' => 'Create request',
		'request_create' => 'Create request',
		'request_open' => 'Open request',
		'request_edit' => 'Edit request',
		'request_savebtn' => 'Save request',
		'request_hint_1' => 'Here you can create a service request. The providers will quote a price for the required service. You can choose the best offer in the end.',
		'request_hint_2' => 'All serice requests appear centralized on the page ^1Service requests^2.',
		'request_hint_3' => 'After you have chosen a service provider for your job, you have to pay the agreed price.',
		'requesttitle' => 'I need',
		'requesttitle_placeholder' => 'e. g. shower installation',
		'requestprice' => 'My Budget',
		'requestprice_placeholder' => 'e. g. 250',
		'specify_price' => 'Please specify a price.',
		'duration_placeholder' => 'e. g. 5',
		'specify_duration' => 'Please state the approximate duration.',
		'requestend' => 'Request online until',
		'requestend_hint' => 'Period maximal 2 weeks.',
		'requestduration_hint' => 'Leave empty if not determinable.',
		'yourrequest_hint' => 'Describe your request in detail and add photos or Youtube videos.',
		'new_request' => 'New service request',
		'newcon_request' => 'Newe request created',
		'back_requests' => 'Back to your requests',
		'another_request' => 'Create another request',
		'request_created' => 'Request created.',
		'request_activated' => 'Request activated.',
		'request_deactivated' => 'Request deactivated.',
		'request_gotcreated' => 'Request created, thank you.',
		'request_edited' => 'Service request updated.',
		'request_deleted' => 'Service request deleted.',
		'request_approved' => 'Service request approved.',
		'request_disapproved' => 'Service request rejected.',
		'specify_requesttitle' => 'Please specify a title for your service request.',
		'specify_date' => 'Please specify an end date.',
		'specify_description' => 'Please enter a description.',
		'format' => 'Format',
		'specify_realname' => 'Please specify ^1your name^2 at first.',
		'specify_realname_request' => 'To create service requests you have at first to specify ^1your name^2.',
		'mail_btncheck_request' => 'Check data + activate request',
		'mail_btncheck_offer' => 'Check data + publish offer',

		// page adminoffers
		'adminoffers_title' => 'Admin: Offers',
		'offerid' => 'Offer n°',
		'nr' => 'n°', // number

		// page adminsearchtrack
		'adminsearch_title' => 'Admin: Search tracking',
		'searchtrack' => 'Search tracking',
		'searchterm' => 'Searchterm',
		'ipaddress' => 'IP-Address',
		'menubtn_admin_searchtrack' => '🔍',
		'nodata' => 'no data',

		// page bid
		'bid_pagetitle' => 'Required', // Angebot abgeben
		'request_notexist' => 'This request does not exist.',
		'request_expired' => 'This request has expired already.',
		'alreadybid' => 'You have already gave a quote on ~date~.',
		'service_required' => 'The following service is required',
		'bid_ends' => 'Request ends on',
		'yourpricebid' => 'Your price quote',
		'yourprice' => 'Your price',
		'yourprice_placeholder' => 'e. g. 200',
		'yourcomment' => 'Your comment',
		'bid_pricehint' => 'Please note that your price quote is legally binding. This means, you have to entirely render the service to the quote given.',
		'postoffer_btn' => 'Give quote',
		'postsuccess' => 'Quote successfully submitted',
		'request_tobechecked' => 'This service request is checked currently and might be published soon.',
		'request_gotdisapproved' => 'This request did not meet our guidelines.',
		'request_gotdeleted' => 'This request was deleted.',

		// page bookingbutton
		'bookbtn_title' => 'Booking button for your website',
		'bookbtn_intro' => 'Add a booking button to your website. This way you give your visitors the chance to book your services right away!',
		'bookme_example' => 'Example of contact form with booking button',
		'bookmenow_btn' => 'Book me now',
		'bookbtn_label' => 'Label of the button',
		'buttonstyle' => 'Button style',
		'simplelink' => 'Simple link',
		'menu_bookingbutton' => 'Button',

		// paymill
		'paymill_title' => 'Payment using Paymill',
		'paymill_error' => 'An unexpected error occurred.',
		'contactus' => 'Please contact us',
		'missing_data' => 'Missing data',

		// userforumprofile
		'recommendation' => 'Recommendation',
		'recommendations' => 'Recommendations',
		'recommendedby' => 'These people recommend ~username~',
		'personrecommendedby' => 'This person is recommended by',
		'irecommend' => 'I recommend ~username~',
		'unrecommend' => 'Withdraw recommendation?',
		'recommends' => '~username~ recommends',

		// adminlogview
		'adviewlog_title' => 'Event Logs',
		'mail_sent' => 'E-mail sent',
		'msg_sent' => 'Message sent',
		'msg_deleted' => 'Message deleted',
		'eventname' => 'Eventname',
		'logdata' => 'Log data',
		'profile_edited' => 'Profile edited',
		'avatar_removed' => 'Profile photo removed',
		'avatar_uploaded' => 'Profil photo uploaded',
		'bid_posted' => 'Price quote posted',
		'payment_deleted' => 'Payment deleted',
		'contractor_weekupdated' => 'Week times updated',
		'profile_created' => 'Profile created',
		'client_depositorder' => 'Customer orders deposit',
		'contractor_paid' => 'Service provider was paid',
		'contractor_contracted' => 'Service provider accepted contract',
		'deposit_release' => 'Deposit released',
		'event_deleted' => 'Event deleted',
		'client_clearance' => 'Account balance initiated',
		'contractor_recommended' => 'Recommendation of service provider',
		'client_creditnote' => 'Creditnote activated', // voucher

		// page businesscard
		'bcard_title' => 'Your personal business card',
		'bcard_intro' => 'When you are Premium member, you receive your personal business cards from us. As Basic member you can order business cards separately.',
		'bcard_preview' => 'Preview',
		'bcard_design' => 'Design',
		'website' => 'Website',
		'bookme' => 'Book me',

		// page premium
		'premium_title' => 'Premium-Plans for Service Providers',
		'premium_intro' => 'As Premium or VIP member you enjoy many valuable advantages. The table shows you all the details:',
		'youarecurrently' => 'You are currently',
		'member_basic' => 'Basic Member',
		'member_premium' => 'Premium Member',
		'member_vip' => 'VIP Member',
		'yourownpage' => '^1Your own Page^2 with basic information and personal photo',
		'servicedesc_page' => 'Service description on your page',
		'servicedesc_limited' => '(limited: only text, no links, no images)',
		'servicedesc_unlimited' => '(unlimited: text, links, images, videos)',
		'createoffer_basic' => 'Create ^11 special offer^2 for more sales and advertisement',
		'createoffer_premium' => 'Create ^15 special offers^2 for more sales and advertisement',
		'createoffer_vip' => 'Create up to ^1100 special offers^2 for more sales and advertisement',
		'bookcal_basic' => 'Your own ^1Booking Calendar^2 with ^3time settings^4 and ^5ICS export^6',
		'eventmanagement' => 'Event Management: change booking times, accept, reject times',
		'bookbtn_external' => '^1Booking Button^2 for your external websites and for your Facebook page',
		'gopremium' => 'go Premium',
		'premium' => 'Premium',
		'govip' => 'go VIP',
		'commission_bookings' => 'Commission on bookings',
		'commission_details' => 'for 6 months, then 25 %',
		'monthly_price' => 'Monthly Value', // translated as Value by purpose (psychology)
		'free' => 'free', // price
		'become' => 'Become', // become premium member
		'subdomain_desc' => 'Subdomain for your page, for example "marius.kvanto.lt"',
		'gcal_integration' => '^1Google Calendar^2 Integration into your Booking Calendar',
		'payment_integration' => 'Payment integration: Get paid by the customer directly after the booking (PaySera integration)',
		'sendprivatemessages' => 'Send ^1private messages^2 to all kvanto members',
		'vcardcontact' => 'Members can import your contact data as vCard to their phone or computer in one click.',
		'adfree' => 'Completely ad-free',
		'forever' => 'forever',
		'eurospermonth' => '€/month',
		'become_contractor' => 'Become service provider',
		'become_premium' => 'Upgrade to Premium',
		'become_premiummember' => 'Become Premium member now',
		'become_vipmember' => 'Become VIP member now',
		'getbusinesscards_desc' => 'Get ^1100 beautiful Business cards^2 after your VIP subscription',
		'moneyback_desc' => 'We always give a money back guarantee of 30 days in case you change your mind.',
		'member_payment_hint' => 'The first month payment is done by you. Upcoming payments we withdraw from your account.',
		'needpremium' => 'You need to be premium member to use this feature.',
		'needpremium_links' => 'The link is not shown because this member is not premium member.',
		'needpremium_email' => 'The email is not shown because this member is not premium member.',
		'needpremium_phone' => 'The phone number is not shown because this member is not premium member.',
		'needpremium_offers' => 'If you want to add more offers, please change your premium plan.',
		'needpremium_messages' => 'You can send messages to anyone if you are premium member.',
		'faq_head' => 'Frequently asked questions',
		'faq_01_h1' => 'What happens after my payment?',
		'faq_01_content' => 'After your payment all premium features get unlocked for you immediately.',
		'faq_02_h1' => 'When is my next billing?',
		'faq_02_content' => 'Your billing cycle starts from the day of your first payment and you will be charged monthly for your premium account.',
		'faq_03_h1' => 'Can I downgrade at anytime?',
		'faq_03_content' => 'Yes. We meet your business needs wherever you are, whether you are growing or scaling back. You can upgrade or downgrade to the end of each month.',
		'faq_04_h1' => 'Can I choose only certain features that I need?',
		'faq_04_content' => 'No, we do not have feature-specific pricing plans. As premium member you benefit from the entire Kvanto system.',
		'faq_05_h1' => 'Can I pay for a yearly subscription?',
		'faq_05_content' => 'No, this is currently not possible. We charge on a monthly basis to give everyone more flexibility.',
		'faq_06_h1' => 'Can I get my money back if something goes wrong?',
		'faq_06_content' => 'Yes, you have up to 30 days after your premium payment to notify us, if you are not satisfied. We refund you of course.',
		'membership' => 'Membership',
		'youarepremium' => 'You are premium member.',
		'premiumtrial_promo' => 'We will give you a Premium membership if you book until until 31 July 2017!',
		'premiumtrial_click' => 'Click "Become premium" and get 6 months of Premium membership.',
		'premiumpayments' => 'Premium Payments',

		// premiumpay
		'membership_premium' => 'Premium Membership',
		'price_premium' => 'Price for Premium Membership',
		'membership_vip' => 'VIP Membership',
		'price_vip' => 'Price for VIP Membership',
		'vat_included' => 'VAT ~vatvalue~ % included', // leave ~vatvalue~, this will be replaced
		'payment' => 'Payment',

		// startpage
		'mainsearchlabel' => 'Find your personal service',
		'forexample' => 'For example',
		'photograph_link' => 'photograph', // custom links below search bar
		'photograph_linktext' => 'wedding photograph', // name of link
		'dentist_link' => 'dentist',
		'dentist_linktext' => 'dentist',
		'mechanic_link' => 'mechanic',
		'mechanic_linktext' => 'car mechanic',
		'nanny_link' => 'nanny',
		'nanny_linktext' => 'nanny',
		'translator_link' => 'translator',
		'translator_linktext' => 'translator',
		'trainer_link' => 'trainer',
		'trainer_linktext' => 'personal trainer',
		'apartmentrepair_link' => 'repair',
		'apartmentrepair_linktext' => 'flat repair',
		'designer_link' => 'designer',
		'designer_linktext' => 'designer',
		'findinstantly_h1' => 'Find individual service providers instantly',
		'findinstantly_text' => 'Browse our extensive and constantly growing list of service providers that help you to complete your tasks. From simple chores to professional services - you will find help on Kvanto. Just use the search to find a specialist, book him or her, and have your problem solved quickly.',
		'findinstantly_button' => 'Browse service providers',
		'timeyouneed_h1' => 'Book the time you need',
		'timeyouneed_text' => 'You can choose yourself when the service shall be provided. Whether you need an hour or a full day, you can select the time easily with our handy calendar. You can also choose a certain offer if a provider has predefined service packages.',
		'timeyouneed_button' => 'Find a service provider',
		'askquestion_h1' => 'Ask questions and get answers from experts',
		'askquestion_text' => 'Join our community and receive answers, tips and recommendations for anything that troubles you. You can even book an expert directly in the forum to help you solving your issues.',
		'askquestion_button' => 'What do you want to know?',
		'becomeprovider_h1' => 'Become a service provider',
		'becomeprovider_text' => 'Just as easy as searching for a service provider, you can start offering your own services and increase exposure with the help of Kvanto. Get found by new customers and increase you income. Kvanto is visited daily by thousands of potential clients that need your help.',
		'becomeprovider_button' => 'Register as service provider',
		'offerpackages_h1' => 'Offer service packages',
		'offerpackages_text' => 'If you perform special services that do not fit into the hourly booking (like a "wedding package" from a photograph), you can advertise them as a predefined service package. Clients will be able to buy them instantly and choose the date in your calendar. More examples: "Evening make-up", "House plumbing maintenance", "3 month personal fitness coaching". Let the world know what you are capable of.',
		'offerpackages_button' => 'Create a service package',
		'clientmanagement_h1' => 'Complete client management system',
		'clientmanagement_text' => 'When you get booked you can easily manage the booking in your dashboard and plan your times. We give you tools to be productive, streamline your client, do finance and calendar handling in one place. Do you always wanted to improve your productivity? Kvanto will make your headaches go away and bring clarity both for you and your clients.',
		'clientmanagement_button' => 'Open your dashboard',
		'getpremium_h1' => 'Become a Premium member',
		'getpremium_text' => 'If you want to use Kvanto as a daily client driver you will definitely benefit from our Premium membership. You get more ways to connect to your clients, no ads on your booking page, software integrations and a bonus of 100 high-quality business cards shipped to your doorstep as VIP.',
		'getpremium_button' => 'See Premium plans',
		'participate_h1' => 'Build your reputation and grow your network',
		'participate_text' => 'Participate in Kvanto\'s expert forum. By answering questions you receive reputation points. Let potential clients see your skills, demonstrate your professionality and your knowledge. Let people recommend you and suggest to their friends with our built-in social sharing tools. Grow your list of clients rapidly.',
		'participate_button' => 'Build your reputation',
		'getbookingpage' => 'Get your own booking page now',
		'signupnow' => 'Sign-up now',
		'ask_service' => 'Service requests',

		// IMPORTANT FOR QA-THEME.PHP
		'lang_code' => 'en',
		'headtitle' => 'Kvanto - Book your personal service',
		'interviewlabel' => 'Interview', // temporary! *** otherwise: interview
		'interviewtag' => 'interviu', // temporary! *** otherwise: interview
		'lang_askquestion' => 'Ask your question!',
		'lang_withoutregistration' => 'free + without registration',
		'lang_qu_alreadyexists' => 'already exists',
		'lang_qu_closed' => 'closed',
		'lang_footer_about' => 'About us',
		'lang_footer_terms' => 'Terms',
		'lang_footer_legal' => 'Legal',
		'lang_footer_contacts' => 'Contact',
		'lang_footer_premium' => 'Premium',
		'lang_shortlink' => 'Shortlink to this page',
		'lang_print' => 'Print',
		'lang_sharefacebook' => 'Share on Facebook',
		'lang_sharegoogleplus' => 'Share on Google Plus',
		'lang_thismember' => 'Member',
		'lang_thisguest' => 'This guest',
		'lang_wrotethosequ' => 'has asked the following questions',
		'lang_pointsforqu' => 'Points for questions',
		'lang_bestanswer' => 'Best?',
		'lang_answer' => 'Answer',
		'lang_answers' => 'Answers',
		'lang_existsalready' => 'Question already exists! Please ask at the original question.',
		'lang_yourquestions' => 'Your questions',
		'lang_search' => 'Search',
		'lang_mailorusername' => 'Username or e-mail',
		'lang_password' => 'Password',
		'lang_rememberme' => 'Remember me',
		'lang_login' => 'Login',
		'lang_qufastanswer' => 'Your question will be answered soon.',
		'lang_followlatest' => 'Follow question',
		'lang_commentanswer' => 'If you have questions regarding an answer, please comment the answer',
		'lang_qudelete' => 'This question will be deleted.',
		'lang_writecomment' => 'Please always use the comment form if you want to know more details.',
		'lang_whatis' => 'Kyga.de is a community of experts, that is helping you.',
		'lang_registerquickly' => 'Register within only one minute',
		'lang_register' => 'Register',
		'lang_forgot_link' => 'Forgot password',
		'whatis' => 'What is',

	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
