<?php

/*
	Plugin Name: q2apro Booking System
	Plugin URI: http://www.q2apro.com/plugins/bookingsystem
*/

	return array(

		// default
		'enable_plugin' => 'Įdiegti įskiepį',
		'minimum_level' => 'Prisijungti prie puslapio',
		'plugin_disabled' => 'Šis įskiepis išjungtas.',
		'access_forbidden' => 'Prisijungimas neleidžiamas.',
		'plugin_page_url' => 'Atidaryti forumo puslapį',
		'contact' => 'Esant klausimų apsilankykite ^1q2apro.com^2',

		// time formats, LIT is e.g. 1983.05.15
		'datetime_format' => 'YYYY.MM.DD hh:mm', // humans
		'datetime_format_js' => 'y.m.d h:s',
		'datetime_format_php' => 'Y.m.d H:i',
		'datetime_format_php_fullhour' => 'Y.m.d H:00',
		'date_format' => 'YYYY.MM.DD', // humans
		'date_format_php' => 'Y.m.d', // http://php.net/manual/de/function.date.php
		'date_format_momentjs' => 'YYYY.MM.DD', // http://momentjs.com/docs/#/displaying/format/
		'date_format_calendarweek' => 'YYYY MM', // fullcalendar title on booking page

		// plugin general
		'meta_description' => 'Greitai ir patogiai raskite specialistus, užsisakykite norimas paslaugas jums tinkamu metu.',
		'contractor' => 'Teikėjas',
		'client' => 'Klientas',
		'member' => 'Narys',
		'user' => 'Vartotojas',
		'nav_main_contractor' => 'Rasti paslaugą', // main menu on top
		'book_service_btn' => 'Užsakyti paslaugą',
		'admin_maillist' => 'El. pašto adresų sąrašas',
		'optional' => 'nebūtina',
		'additional' => 'papildomai',
		'fee' => 'Užmokestis',
		'feepay' => 'Užmokesčio išmokėjimas',
		'btn_submit' => 'Išsiųsti',
		'btn_create' => 'Sukurti',
		'order' => 'Užsakymas',
		'protocol' => 'Protokolas',
		'event' => 'Užsakymas',
		'eventid' => 'Užsakymas Nr.',
		'date' => 'Data',
		'time' => 'Laikas',
		'timeabbr' => 'val.', // e.g. 10:00 Uhr
		'hourabbr' => 'val.', // e.g. h
		'min' => 'min',
		'timespan' => 'Trukmė',
		'price' => 'Kaina',
		'sum' => 'Suma',
		'anonymous' => 'anonimiškai',
		'length' => 'Trukmė',
		'start' => 'Pradžia',
		'end' => 'Pabaiga',
		'eventdetails' => 'Užsakymo detalės',
		'attachments' => 'Priedai',
		'bookingnr' => 'Rezervacijos Nr.',
		'bookingtotal' => 'Rezervacijos kaina',
		'ev_former' => 'Ankstesnis',
		'ev_new' => 'Naujas',
		'ev_until' => 'iki',
		'reason' => 'Priežastis',
		'eventproposal' => 'Laiko pasiūlymas',
		'file' => 'Duomenys',
		'absent' => 'nepasiekiamas',
		'reserved' => 'rezervuotas',
		'already_reserved' => 'jau rezervuotas',
		'booked' => 'užsakytas',
		'completed' => 'baigtas',
		'event_completed' => 'baigtas',
		'paid' => 'sumokėta',
		'confirmed' => 'patvirtinta',
		'save_btn' => 'Išsaugoti',
		'saveall_btn' => 'Viską išsaugoti',
		'from' => 'nuo', // e.g. paid from
		'address' => 'Adresas',
		'location' => 'Vieta',
		'portfolio' => 'Aplankas',
		'birthdate' => 'Gimimo data',
		'deposit' => 'Pinigų likutis', // a fixed amount can be bought by client, and he can use this deposit money to book contractors
		'balance' => 'Likutis',
		'accountbalance' => 'Sąskaitos likutis',
		'balance_plus' => 'Pingų likutis',
		'balance_minus' => 'Grąžintina suma',
		'clearance' => 'Padengti įsiskolinimą', // to balance the account to zero
		'paymentin' => 'Įėjimas', // Zahlungseingang
		'paymentout' => 'Išėjimas', // Zahlungsausgang
		'appt' => 'Užsakymas',
		'appts' => 'Užsakymai',
		'myappts' => 'Mano užsakymai',
		'appt_from' => 'Užsakymas nuo',
		'sendmsg_btn' => 'Siųsti žinutę',
		'message' => 'Žinutė',
		'messages' => 'Žinutės',
		'per' => 'už', // price per hour
		'status' => 'Būklė',
		'name' => 'Vardas',
		'payamount' => 'Mokėtina suma',
		'password' => 'Slaptažodis',
		'forum' => 'Žinių forumas',
		'forum_short' => 'Forumas',
		'notallowed' => 'neleidžiama',
		'error' => 'Klaida',
		'only' => 'tik', // price
		'notspecified' => 'nenurodyta', // price
		'myaccount' => 'Mano paskyra',
		'created' => 'sukurta',
		'or' => 'arba',
		'value' => 'vertė',
		'accepted' => 'priimta',
		'title' => 'Pavadinimas',

		// week
		'monday' => 'Pirmadienis',
		'tuesday' => 'Antradienis',
		'wednesday' => 'Trečiadienis',
		'thursday' => 'Ketvirtadienis',
		'friday' => 'Penktadienis',
		'saturday' => 'Šeštadienis',
		'sunday' => 'Sekmadienis',
		'mon' => 'Pr',
		'tue' => 'An',
		'wed' => 'Tr',
		'thu' => 'Kt',
		'fri' => 'Pn',
		'sat' => 'Št',
		'sun' => 'Sk',

		// qa-plugin.php
		'no_bookings' => 'Nėra užsakymų.',
		'prefered_times' => 'Pageidaujamas laikas',
		'prefered_times_none' => 'Neįvestas laikas',
		'appts_with' => 'Užsakymai su',
		'appt_paid' => 'apmokėta',
		'hello' => 'Sveiki',
		'thxpaid' => 'Dėkojame už apmokėjimą',
		'mail_thxpaid' => 'dėkojame už apmokėjimą.',
		'mail_willcontact' => 'turi patvirtinti laiką. Jis su Jumis susisieks.', // person ...
		'mail_askdetails' => 'Ar jau įvedėte užsakymo duomenis?',
		'mail_btndetails' => 'Įvesti užsakymo duomenis',
		'mail_yourappts' => 'Jūsų pasirinktas laikas:',
		'mail_canmessage' => 'Galite bet kada tiesiogiai paslaugos teikėjui ^1išsiųsti žinutę^2.',
		'mail_greetings' => 'Iki',
		'mail_greeter' => 'Kvanto komanda',
		'notmentioned' => 'neįvesta',
		'confirm_appts' => 'Patvirtinti laiką',
		'directmessage' => 'tiesioginė žinutė',
		'telephone' => 'Telefonas',
		'telephone_abbr' => 'Tel.',
		'mailtocon_custopaid' => 'Klientas ~~~ apmokėjo užsakymą.', // leave ~~~, this will be replaced by the client name
		'mailtocon_doconfirm' => 'Patvirtinkite užsakymą ^1Užsakymo peržiūra^2.',
		'mailtocon_contactcusto' => 'Susisiekite su klientu. Kontaktiniai duomenys: ',
		'mailtocon_bookdetails' => 'Užsakymo Nr. ~~~ detalės yra:', // leave ~~~, this will be replaced by the booking id
		'eventsavailable' => 'Galimi nauji užsakymai', // email subject
		'mail_neweventsav' => 'Galimi nauji užsakymai, kurių atlikti negalėjo kiti paslaugų teikėjai. Jūs galite priimti arba atmesti:',
		'mail_gotoevents' => 'Atidaryti užsakymus',
		'mail_eventaccepted_subject' => 'Užsakymas pas ~~~ yra priimtas', // email subject, leave ~~~, this will be replaced by the contractorname
		'mail_eventaccepted' => 'Jūsų užsakymas pas ~~~ yra priimtas ir vykdomas.', // leave ~~~, this will be replaced by the contractorname
		'mail_seeyourschedule' => 'Čia galite atidaryti savo užsakymų tvarkaraštį',
		'mail_eventrejected_subject' => '~~~ užsakymas atmestas', // email subject, leave ~~~, this will be replaced by the contractorname
		'mail_eventrejected' => 'Deja Jūsų užsakymai ~~~ negali būti priimti.', // leave ~~~, this will be replaced by the contractorname
		'mail_rejectreason' => 'Priežastis: „~~~“', // leave ~~~, this will be replaced
		'mail_othersinformed' => 'Kiti paslaugų teikėjai buvo informuoti su pasiūlymu priimti Jūsų užsakymą. Paslaugos teikėjas su Jumis susisieks dėl užsakymo perėmimo.',
		'mail_newtime_subject' => 'Naujas paslaugos laikas',
		'mail_newtime' => 'Jums pasiūlytas naujas paslaugos laikas. Prašau pasirinkite tinkamiausią laiką:',
		'mail_clearancesuccess' => 'Sąskaita sėkmingai papildyta', // in case of negative balance the client pays
		'mail_clearanceintro' => 'Dėkojame už Jūsų mokėjimą, kurio dydis ~~~. Jūsų sąskaita subalansuota.', // leave ~~~
		'mail_depositsuccess_subject' => 'Įnašas aktyvuotas',
		'mail_depositsuccess' => 'Dėkojame, gavome Jūsų apmokėjimą. Jūsų sąskaita papildyta ~~~.',
		'mail_bookcontractors' => 'Dabar Jūs galite naudoti savo įnašą užsakyti ^1paslaugas^2.',

		// events
		'evname_openevent' => 'Klientas pradeda užsakymą',
		'evname_openevent2' => 'atviras',
		'evname_reserved' => 'Klientas rezervuoja laiką',
		'evname_reserved2' => 'Laikas rezervuotas',
		'evname_paid' => 'Klientas apmokėjo',
		'evname_changed' => 'Užsakymo laikas pakeistas',
		'evname_setdetails' => 'Klientas nustato užsakymo detales',
		'evname_setdetails2' => 'Užsakymo detalės nustatytos',
		'evname_consetdetails' => 'Paslaugos teikėjas nustato užsakymo detales',
		'evname_consetdetails2' => 'Užsakymo detalės nustatytos',
		'evname_findtime' => 'Užsakymo laikas bus suderintas',
		'evname_findtime2' => 'Užsakymo laikas apdorojamas',
		'evname_accepted' => 'Užsakymo laikas suderintas, užsakymas bus vykdomas',
		'evname_accepted2' => 'Užsakymas bus vykdomas',
		'evname_rejected' => 'Paslaugos teikėjas nepatvirtino užsakymo',
		'evname_rejected2' => 'Užsakymas atmestas',
		'evname_conneeded' => 'Užsakymui bus ieškomas paslaugos teikėjas',
		'evname_conneeded2' => 'Ieškomas paslaugos teikėjas',
		'evname_completed' => 'Paslaugos teikėjas pabaigia užsakymą',
		'evname_completed2' => 'Užsakymas pabaigtas',
		'evname_rated' => 'Klientas įvertina užsakymą',
		'evname_rated2' => 'Užsakymas įvertintas',
		'evname_available' => 'Contractor available',
		'view_appt' => 'Peržvelgti užsakymą',

		// ratings
		'rating' => 'Įvertinimas',
		'ratings' => 'Įvertinimai',
		'ratingtext' => 'Įvertinimo aprašymas',
		'noratings' => 'Kol kas nėra įvertinimų.',
		'comment' => 'Komentaras',

		// layer
		'profile' => 'Profilis',
		'calendar' => 'Kalendorius',
		'yourcalendar' => 'Jūsų kalendorius',
		'menubtn_con_week' => 'Savaitės laikai',
		'menubtn_con_balance' => 'Užmokestis',
		'menubtn_con_info' => 'Informacija',
		'menubtn_cli_ratings' => 'Įvertinti',
		'menubtn_cli_balance' => 'Sąskaitos apžvalga',
		'menubtn_cli_profile' => 'Profilis',
		'menubtn_balance' => 'Užmokestis',
		'menubtn_con_offers' => 'Pasiūlymai',
		'payments' => 'Mokėjimai',
		'contractors' => 'Paslaugos teikėjas',
		'clients' => 'Klientai',
		'menubtn_messages' => '✉',
		'topright_next_appt' => 'Kitas užsakymas',
		'topright_no_appt' => 'jokio užsakymo',
		'topright_msg' => 'Žinutės',
		'admin' => 'Admin', // istratorius
		'upcomingappts' => 'Ateinančių užsakymų skaičius',
		'earningbookings' => 'Paskutinių 30 dienų pajamos',
		'recentrequests' => 'Naujausių paslaugų užsakymų kiekis',

		// page general
		'page_deactive' => 'Šis puslapis šiuo metu nėra aktyvus.',
		'page_noaccess' => 'Nepasiekiamas.',
		'fee_balance' => 'Balansas',

		// page adminbalance
		'adminbal_title' => 'Admin: Užmokestis',
		'income' => 'Pajamos',
		'fee_payout' => 'Užmokesčio išmokėjimas',
		'fee_lastmonth' => 'praėjęs mėnuo',
		'fee_sum' => 'Suma',
		'forcontractor' => 'Paslaugų teikėjui',

		// page admincalendar
		'admincal_title' => 'Admin: Visi Terminai',
		'admincal_perhaps' => 'galbūt',
		'admincal_unpaid' => 'neapmokėta',
		'admincal_from' => 'nuo',
		'admincal_by' => 'pas', // person
		'btnupdate_appt' => 'Aktualizuoti užsakymus',
		'admincal_nochanges' => 'Nėra jokių pakeitimų.',
		'updatesuccess' => 'Užsakymas sėkmingai aktualizuoti.',
		'reloadpage' => 'Perkrauti puslapį.',
		'cal_warnonleave' => 'Užsakymai pakeisti, tačiau neišsaugoti. Ar tikrai norite uždaryti puslapį?',

		// page adminclients + admincontractors
		'admincli_title' => 'Admin: Klientai',
		'admincon_title' => 'Admin: Paslaugos teikėjas',
		'admin_tab_userdata' => 'Vartotojo duomenys',
		'admin_tab_birthdate' => 'Gimimo data',
		'admin_tab_address' => 'Adresas',
		'admin_tab_price' => 'Kaina',
		'admin_tab_absent' => 'Nepasiekiamas (pvz. atostogaujate)',
		'paymethod' => 'Mokėjimo būdas',
		'admin_tab_spec' => 'Veiklos sritis',
		'admin_tab_portfolio' => 'Veiklos aplankas',
		'email' => 'El. pašto adresas',
		'admin_sendmsg' => 'Rašyti žinutę',
		'forum_profile' => 'Forumo profilis',
		'pointstatistic' => 'Taškų statistika',
		'forumstatistic' => 'Forumo statistika',
		'forumactivity' => 'Aktyvumas forume',
		'bookingsite' => 'Rezervacijos puslapis',
		'nolocationset' => 'Neįvesta vietovė.',
		'admin_open_gmaps' => 'Atidaryti Google žemėlapiai.',
		'approve' => 'patvirtinti',
		'approved' => 'patvirtinta',
		'doapprove' => 'patvirtinti',
		'dounlock' => 'aktyvuotas (atblokuotas)',
		'removeapprove' => 'Panaikinti leidimą',
		'disapprove' => 'nepritarti',
		'disapproved' => 'nepritartas',
		'removedisapprove' => 'panaikinti apribojimus',
		'bookingvolume' => 'Užsakymų kiekis',

		// page admineventedit
		'admineved_title' => 'Admin: keisti įvykį',
		'admineved_missingid' => 'Įveskite įvykio ID.',
		'admineved_success' => 'Įvykis sėkmingai atnaujintas.',
		'admineved_back' => 'Atgal į užsakymų sąrašą.',

		// page adminmessages
		'adminmsg_title' => 'Admin: Visos žinutės',
		'adminmsg_from' => 'Nuo',
		'adminmsg_to' => 'Kam',
		'delete' => 'ištrinti',
		'nomessages' => 'Nėra žinučių.',
		'adminmsg_confirmdel' => 'Ar tikrai norite ištrinti?',
		'message_deleted' => 'Žinutė ištrinta.',

		// page adminpayments
		'adminpaym_title' => 'Admin: Mokėjimai',
		'adminpaym_paymethod' => 'Mokėjimo būdas',
		'adminpaym_bank' => 'Bankas',
		'adminpaym_paypal' => 'Paypal',
		'adminpaym_creditnote' => 'Dovanoti', // present to client
		'adminpaym_elimination' => 'Panaikinimas', // client has negative balance, we dispense the amount
		'adminpaym_paid' => 'Apmokėta',
		'adminpaym_timestamp' => 'Laikas',
		'adminpaym_paybookid' => 'Rezervacijos Nr. (apmokėjus užsakymą)',
		'adminpaym_payid' => 'Mokėjimo-ID',
		'adminpaym_deposit' => 'Disponuojama suma',
		'adminpaym_validate' => 'patvirtinti',
		'adminpaym_delete' => 'ištrinti',
		'adminpaym_unpaid' => 'neapmokėtas',
		'adminpaym_created' => 'Mokėjimas pateiktas',

		// page adminratings
		'adminrat_title' => 'Admin: Įvertinimai',
		'rat_negativ' => 'neigiamai',
		'rat_neutral' => 'neutraliai',
		'rat_good' => 'gerai',
		'rat_verygood' => 'labai gerai',
		'rat_excellent' => 'puikiai',
		'adminrat_tab_client' => 'Vartotojas',
		'adminrat_tab_contractor' => 'Paslaugos teikėjas',

		// page adminschedule
		'adminsched_title' => 'Admin: Užsakymai',
		'apptcount' => 'Užsakymai ne senesni negu 30 dienų',
		'adminsched_id' => 'ID',
		'adminsched_price' => 'Kaina',
		'adminsched_contractor' => 'Paslaugos teikėjas',
		'adminsched_client' => 'Vartotojas',
		'adminsched_needs' => 'Užsakymo detalės',
		'adminsched_state' => 'Statusas',
		'adminsched_paidpaypal' => 'apmokėta per Paypal',
		'adminsched_paidbank' => 'apmokėta banko pavedimu',
		'adminsched_paiddeposit' => 'apmokėta disponuojamu įnašu',
		'hintincomplete1' => 'Papildyti užsakymo detalės ir įtraukti nuorodą į užbaigimą',
		'hintincomplete2' => 'Papildyti užsakymo detalės',
		'hintincomplete3' => 'įtraukti nuorodą į užbaigimą',
		'apptdetails' => 'Pateikti užsakymo detales',
		'adminsched_placeholder' => 'Pateikti nuorodą dėl užbaigimo',
		'adminsched_bookedon' => 'užsakyta',
		'adminsched_unit' => 'už vienetą',
		'adminsched_confirmdelete' => 'Įvykį tikrai ištrinti',

		// page booking
		'bookservice' => 'Užsakyti laiką',
		'onlyregistered' => 'Tik registruoti vartotojai gali naudoti puslapis.',
		'noservice' => 'Nepasirinkta paslauga.',
		'con_notavailable' => 'Šiuo metu šis paslaugos teikėjas nepasiekiamas.',
		'notavailable' => 'nepasiekiamas',
		'needregisterlogin' => 'Prašome ^1prisijungti^2 arba ^3prisiregistruoti^4.',
		'needreglogin_service' => 'Norėdami rezervuoti paslaugas, prašome ^1prisijungti^2 arba ^3prisiregistruoti^4.',
		'notpaid_click' => 'Kol kas neapmokėtas užsakymas pas ~~~ - Paspauskite norėdami apmokėti',
		'yourapptwith' => 'Jūsų užsakymas pas',
		'openprofile' => 'Atidaryti profilį',
		'preferedtimes' => 'Pasirinkite laiką tempdami pelyte žemiau esančiame kalendoriuje. Spalvotai pažymėti langeliai yra paslaugos teikėjo siūlomi laikai. Galite pasirinkti ir kitą laiką.',
		'preferedtimes_short' => 'Pasirinkite norimą laiką tempdami pelyte žemiau esančiame kalendoriuje',
		'howtimesbymouse' => 'Kaip pasirinkti laiką',
		'specify_fullname' => 'Prašau nurodykite pilną savo vardą',
		'firstlastname' => 'Vardas ir pavardė',
		'specify_address' => 'Nurodykite savo adresą',
		'placeholder_addressexample' => 'pvz. Kosciuškos 9-99, LT-01110 Vilnius',
		'specify_birthdate' => 'Nurodykite savo gimimo datą.',
		'specify_birthdate_page' => 'Mums reikalinga Jūsų gimimo data',
		'placeholder_dateexample' => 'pvz. 1983.09.15',
		'pleasepay' => 'Pildykite sąskaitą.',
		'yourbalance' => 'Jūsų sąskaita',
		'acceptterms' => 'Sutinku su ^1Taisyklėmis^2.',
		'askforterms' => 'Prašau patvirtinkite, kad sutinkate su Taisyklėmis.',
		'btn_bookandpay' => 'Užsisakyk paslaugą dabar', // Pirkti paslaugą
		'earliesttomorrow' => 'Jūsų užsakyta paslauga gali būti anksčiausiai suteikta rytoj.',
		'notpast' => 'Jūsų užsakymas negali būti ankstesnės negu šiandienos data.',
		'onlyfixedtimes' => 'Paslauga teikiama tik mėlyna spalva pažymėtu laiku.',
		'depositafterbooking' => 'Jūsų disponuojama suma po to',
		'depositempty' => 'Jūsų disponuojama suma šiuo užsakymu išnaudota. Trūkstama suma \'+newbalancestr+\' turi būti padengta.',
		'choosecaltime' => 'Prašau išsirinkti laiką kalendoriuje.',
		'specify_email' => 'Įveskite savo el. pašto adresą.',
		'specify_validemail' => 'Prašau įveskite galiojantį el. pašto adresą.',
		'specify_password' => 'Įveskite slaptažodį.',
		'contractor_notexist' => 'Šis paslaugų teikėjas neegzistuoja.',
		'user_notexist' => 'Šis narys neegzistuoja.',
		'calendarhelp' => 'Reikia pagalbos dėl kalendoriaus?',
		'distance' => 'Atstumas',
		'time' => 'Laikas',
		'timebycar' => 'Kelionės laikas automobiliu',
		'showmap' => 'Rodyti žemėlapį',
		'hidemap' => 'paslėpti žemėlapį',
		'start' => 'Pradžia',
		'target' => 'Tikslas',
		'updatebtn' => 'Aktualizuoti',
		'specialoffers' => 'Pasiūlymai',
		'offer_validuntil' => 'Pasiūlymas galioja iki',
		'executiontime' => 'vykdymo laikas',
		'bookofferfor' => 'Pasiūlymą užsakyti',
		'choosedaytime' => 'Prašome išsirinkti dieną ir valandą:',
		'chooseday' => 'Prašome išsirinkti dieną:',
		'approx' => 'apie',
		'btn_bookoffer' => 'Užsakyti ir toliau mokėti',
		'intotal' => 'viso',
		'incl_taxes' => 'įsk. mokesčius',
		'shortlink_profile' => 'Trumpa nuoroda į šį profilį',
		'order_imp' => 'Užsakyti',
		'order_for' => 'Užsakyti už', // price follows
		'vcardlink' => 'Download vCard',
		'createlogin' => 'Sukurkite savo prisijungimo duomenis',
		'nopriceset' => 'Kaina nenurodyta',

		// page clientbalance - obsolete
		'clibal_title' => 'Likusios sumos padengimas',
		'clibal_title_overview' => 'Sąskaitos apžvalga',
		'paywith' => 'Mokėjimo būdas',
		'paywithpaypal' => 'Mokėjimas Paypal',
		'paywithbank' => 'Mokėjimas banko pavedimu',
		'btn_paynow' => 'Apmokėti',
		'upcoming_appts' => 'Būsimieji užsakymai',
		'event_paid' => 'Užsakymas apmokėtas',
		'no_balanceminus' => 'Nėra įsiskolinimo',
		'or_getdeposit' => 'Įnešti ^1pinigus (inašas)^2?',
		'pleasepaynext' => 'Apmokėkite toliau',
		'payto' => 'kam',
		'payreceiver' => 'Gavėjas',
		'afterclearbal' => 'Laukiame Jūsų apmokėjimo. Gavę Jūsų apmokėjima patvirtinsime el. paštu.',
		'paypurpose' => 'Paskirtis',
		'pay_clearance' => 'Apmokėti skirtumą', // for person
		'pay_id' => 'Mokėjimo Nr.',
		'connect_paypal' => 'Jumgiama prie PayPal …',
		'pleasewait' => 'Prašau palaukite …',
		'paypal_js' => 'Jūsų naršyklėje nėra įdiegta Javascript, paspauskite šią nuorodą norėdami tęsti apmokėjimą.',

		// page clientcalendar + contractorcalendar
		'clical_title' => 'Kalendorius',
		'notpaid_pay' => 'dar neapmokėta - Paspausti mokėti',
		'notpaidyet' => 'dar neapmokėta',
		'listclients' => 'Susisiekti su pasirinktu paslaugos teikėju',
		'embed' => 'Įtvirtinti',
		'embedcalendar' => 'Savo kalendorių galite susieti su Google kalendoriumi, Outlook, Thunderbird ir kt. Tiesiog atitinkamoje programoje  žnuorodą kaip išorinį kalendorių',
		'embedcalendar_2' => 'Čia galite peržiūrėti instrukcijas atitinamoms programoms.',
		'instructions' => 'Instrukcijos',
		'hints' => 'Nuorodos',
		'calguide_google' => 'Instrukcija Google kalendoriui',
		'calguide_outlook' => 'Instrukcija Outlook',
		'calguide_thunderbird' => 'Instrukcija Thunderbird/Lightning',
		'gcal_hint1' => 'Norėdami bendrinti savo "Google" Kalendorių, turite paslėti informaciją ir pakeisti viešumo nustatymą į "Viešas (Public)".',
		'gcal_hint2' => 'Jūsų "Kalendoriaus ID" galite rasti žemiau esančiame "Kalendoriaus informacija" Google sistemoje. Šį identifikatorių turite įvesti čia viršuje.',
		'gcal_hint3' => 'Būtinai atkreipkite dėmesį, kad Jūsų laikai Google kalendoriuje turėtų požymį "Busy/Užimtas". Laikai, kurie turės požymį "Available/Pasiekiamas", nebus rodomi mūsų kalendoriuje.',
		'screenshot' => 'Ekrano nuotrauka',
		'embedcal' => 'Susieti kalendorių',
		'import' => 'Įkelti',
		'export' => 'Eksportas',
		'google_connect' => 'Prisijunkite prie Google',
		'google_hint' => 'Čia galite integruoti savo asmeninį ^1Google Calender^2. Tokiu būdu klientai galės matyti kokiu laiku Jūs neteikiate paslaugos arba esate nepasiekiamas.',
		'google_hint_client' => 'Čia galite integruoti savo asmeninį ^1Google Calender^2. So sehen Sie Ihre eigenen Termine beim Buchen in anderen Kalendern und es kommt nicht zu Überschneidungen.',
		'google_nodetails' => 'Kalendoriuje bus matoma informacija tik apie Jūsų užimtus laikus, detalesnė informacija ką tuo metu veiksite nebus pateikiama.',
		'clipboard_copied' => '⁠⁠⁠⁠⁠⁠Nuoroda nukopijuota. Dabar galite nukopijuotą nuorodą dešiniu pelės klavišo paspaudimu įterpti.',
		'googlecal_link' => 'Nuoroda į Jūsų Google Calender',
		'eventtypes' => 'Būsena',
		'copylink' => 'Nukopijuoti nuorodą',
		'openlink' => 'Atidaryti nuorodą',

		// page clientdeposit - obsolete
		'clidep_paytitle' => 'Apmokėti įnašą',
		'clidep_noorder' => 'Užsakymas nerastas.',
		'clidep_title' => 'Įnašą',
		'clidep_intro' => 'Su įnašu Jūs galite nedelsiant  užsakyti paslaugas ir geriau kontroliuoti savo išlaidas',
		'recent_balance' => 'Jūsų ^1sąskaitoje^2 šiuo metu yra:',
		'set_deposit' => 'Pasirinkti įnašo dydį',
		'set_slider' => 'Pasirinkite įnašo dydi su kursoriumi',
		'paymethodchoice' => 'Pageidaujamas mokėjimo būdas',
		'banktransfer' => 'Mokėjimas per banką',
		'bankhint' => 'Jūs atliekate pavedimą per banką. Mokėjimas bus atliktas per 1 - 2 dienas.',
		'paypalhint' => 'Sėkmingai atlikus mokėjimą, suma bus įskaityta į Jūsų sąskaitą',
		'depositback' => 'Sąskaitoje turimą sumą bet kada galite susigrąžinti. Tokiu tveju susisiekite su mumis el. paštu.',
		'depositset' => 'Jūs nustatėte įnašą, kurio suma yra...', // leave ~~~
		'paydeposit' => 'Apmokėti įnašą',
		'clidep_mail_subject' => 'Užsakyti įnašą',
		'clidep_mail_body1' => 'Jūsų įnašas, kurio dydis ~~~ rezervuotas.',
		'clidep_mail_body2' => 'Sumokėkite ~~~, tik tuomet galėsite naudotis įnašu',
		'paymentalways' => 'Mokėjimą bet kuriuo metu galite ^1atlikti čia^2.',
		'pay_deposit_for' => 'Įnašas',
		'aftercleardeposit' => 'Gavę Jūsų apmokėjimą, galėsime patvirtinti Jūsų įnašą. Patvirtinimą Jums atsiųsime el. paštu',

		// page userprofile
		'cliprof_title' => '',
		'startcredit_activated' => 'Dovanota suma aktyvuota', // admin info mail
		'user_registered' => 'Naujas narys registruotas',
		'registered' => 'registruotas',
		'contracted' => 'sutartis',
		'can_photoupload' => 'Čia Jūs galite ^1įkelti savo nuotrauką^2.',
		'reward_profile' => 'Papildykite savo profilį ir pirmajam užsakymui Jums bus padovanotas įnašas lygus.',
		'placeholder_phone' => 'Norėdami susisiekti arba užduoti klausimus',
		'skypename' => 'Skype vardas',
		'change_pwmail' => 'Pakeisti el. pašto adresą arba slaptažodį',
		'data_updated' => 'Aktualizuoti duomenis',
		'startcredit_granted' => 'Jums buvo padovanotas įnašas įskaitytas.',
		'next_book_contractor' => 'Toliau rezervuokite paslaugos ^1teikėją^2.',
		'data_incompleted' => 'Duomenys nepakankamai užpildyti, negali būti išsaugoti.',
		'offershint' => 'Baigus registraciją galėsite įrašyti savo pasiūlymus su kainomis.',
		'getbookingbutton' => 'Užsakymo mygtukas Jūsų internetiniam puslapiui',

		// page clientratings
		'clirat_title' => 'Paslaugos teikėjo įvertinimas',
		'clirat_mail' => 'Užsakymas buvo įvertintas',
		'clirat_content' => '~name~ Jus įvertino ~date~:', // leave ~name~ and ~date~
		'see_ratings' => 'Čia Jūs galite peržiūrėti savo įvertinimus',
		'clirat_contactus' => 'Jeigu esate nepatenkinti paslaugų teikėju - susisiekite su mumis',
		'clirat_dorate' => 'Prašome įvertinti paslaugų teikėjo suteiktas paslaugas. Siekiant tobulinti teikiamų paslaugų kokybę, savo įvertinimus pateikite sąžiningai ir kritiškai.',
		'clirat_prevratings' => 'Kiti įvertinimai',
		'clirat_placeholder_rat' => 'Pateikti trumpą įvertinimą …',
		'noapptyet' => 'Paslaugų teikėjas Jums dar nesuteikė paslaugų.',
		'ratingsaved' => 'Įvertinimas buvo išsaugotas. Dėkojame.',

		// page clientschedule
		'clisched_title' => 'Užsakymai',
		'specify_needs' => 'Pateikite laiku užsakymo detales, kad paslaugos teikėjas galėtų tinkamai pasiruošti.',
		'singleappt' => 'Atskiras užsakymas',
		'onlysingleappt' => 'Jums bus rodomas konkretus užsakymas. Čia Jūs galite peržiūrėti ^1visus užsakymus^2.',
		'noappts' => 'Šiuo metu jokių užsakymų.',
		'noeventsfound' => 'Nerasta atitinkamo užsakymo.',
		'uploadfile' => 'Įkelti duomenis',
		'uploadfile_another' => 'Įkelti kitus duomenis',
		'uploadsuccess' => 'Duomenys sėkmingai įkelti',
		'pay_tooltip' => 'Užsakymas dar neapmokėtas. Spauskite čia norėdami apmokėti.',
		'pay_appt' => 'Apmokėti užsakymą',
		'savesuccess' => 'Sėkmingai išsaugotas',
		'filesizewarning' => 'Maksimalus failo dydis 8 MB. Sumažinkite failą.',
		'completed_button' => 'Patvirtinti paslaugos suteikimą',
		'completed_tooltip' => 'Užsakymas buvo sėkmingai įvykdytas ir apmokėtas.',

		// page contractorbalance
		'conbal_title' => 'Užmokestis',
		'con_noapptyet' => 'Jūs kol kas neturite užsakymų.',
		'apptcompleted_hint' => 'Užsakymas bus baigtas, kai bus įvesta nuoroda patvirtinanti baigimą.',
		'conbal_recent' => 'Aktualu',
		'conbal_onlyadmin' => 'Tik Admin',
		'conbal_turnover' => 'Apyvarta',
		'conbal_fees' => 'Užmokesčiai',
		'conbal_earnings' => 'Pelnas',

		// page contractorcalendar
		'concal_title' => 'Kalendorius',
		'change_appt' => 'Pakeisti užsakymo laiką',
		'change_appt_hint1' => 'Jūs galite nukelti atvirus užsakymus ir keisti jų trukmę (kursoriumi užeikite ant savaitės peržiūros). Atkreipkite dėmesį į tai, kad klientas turi primokėti skirtumą arba susigrąžintą permoką.',
		'change_appt_hint2' => 'Svarbu',
		'change_appt_hint3' => 'Užsakymo pakeitimas turi būti registruotas, išsiunčiant ^1žinutę^2 klientui.',
		'contact_clients' => 'Susisiekti su klientu',
		'booktimespan' => 'Rezervuoti šį laikotarpį',
		'nochanges' => 'Pakeitimai nebuvo atlikti.',
		'reloadingpage' => 'Puslapis naujai užkraunamas.',

		// page contractorinfo
		// please edit booker-page-contractorinfo.php directly
		// this information is flexible depeding on the FAQ and requirements of the project

		// page contractorlist
		'conli_title' => 'Užsakyti paslaugą',
		'voucher_until' => 'Galioja iki',
		'voucher_detail' => 'Pirmajam užsakymui Jūs gaunate ~~~ sumą dovanų.',
		'registerforbooking' => 'Norėdami užsisakyti paslaugą, Jūs turite ^1registruotis^2.',
		'registerclient' => 'Vartotojo registracija',
		'moneybackguarantee' => 'Pinigų grąžinimo garantija',
		'moneybackdetail' => 'Jeigu Jūsų netenkins suteiktos paslaugos kokybė, Jums bus grąžinti pinigai.', // not implemented
		'positiveratings' => 'Teigiami įvertinimai',
		'bookfor' => 'Užsisakyti už', // price
		'customerratings' => 'Aktualūs klientų įvertinimai',
		'recommendcontractor' => 'Pasiūlyti teikėją',
		'bestprice' => 'Geriausia kaina',
		'guaranteed' => 'garantuota',
		'bestpriceguarantee' => 'Geriausios kainos garantija',
		'weguarantee' => 'Mes garantuojame Jums geriausią kainą už pasirinktą paslaugą. Jei internete rastumėte pasiūlymą su dar geresne kaina, mes Jums suteiksime galimybę paslaugą įsigyti už Jūsų surastą geresnę kainą.',
		'moneywithhold' => 'Jūsų pinigai yra saugūs',
		'withholdguarantee' => 'Paslaugos teikėjui pinigai atitenka tik po to, kai Jūs mums pranešate, jog paslauga buvo suteikta. Iki tol Jūsų pinigai yra saugiai laikomi pas mus.',  // not implemented
		'clickmoreservices' => 'Spauskite čia norėdami ieškoti susijusių paslaugų.', // Klick hier, um nach weiteren Dienstleistern dieser Art zu suchen.

		// page userprofile
		'nav_login' => 'Prisijungti',
		'conpro_title' => 'Paslaugų teikėjo profilis',
		'yourprofile' => 'Jūsų profilis',
		'douploadphoto' => 'Trūksta Jūsų nuotraukos.',
		'facerequired' => 'Jūsų veidas turi būti atpžįstamas.',
		'forcustomertrust' => 'Svarbu siekiant klientų pasitikėjimo.',
		'accountstatus' => 'Vartotojo paskyra',
		'verified' => 'patvirtinta',
		'we_verify' => 'Nuo Jūsų registracijos per 24 val. patikrinsime pateiktus duomenis ir aktyvuosime vartotojo paskyrą.',
		'available' => 'Laisvas',
		'absent_placeholder' => 'pvz. 2016.05.01, 2016.06.05 - 2016.06.10',
		'absent_tooltip' => 'Norėdami įrašyti daugiau datų, atskirkite jas kableliu. Atskiras dienas įrašykite YYYY.MM.DD, laikotarpį tokiu formatu YYYY.MM.DD-YYYY.MM.DD',
		'weekdays_head' => 'Nedarbo dienos',
		'public_data' => 'Vieši duomenys',
		'internal_data' => 'Vidiniai duomenys',
		'basic_data' => 'Pagrindiniai duomenys',
		'contractor_data' => 'Paslaugos teikėjo duomenys',
		'contractor_data_qu' => 'Siūlote savo paslaugas?',
		'yourservice_short' => 'Jūsų paslaugos',
		'placeholder_service' => 'pvz. Advokatas',
		'yourservice_desc' => 'Aprašymas/veiklos aplankas',
		'yourservice_hint' => 'Aprašykite Jūsų teikiamas paslaugas, kurios bus viešai skelbiamos. ^1Tik premium:^2 Pridėkite nuotraukas ir teikite jokių asmeninių kontaktinių duomenų.',
		'upload_img' => 'Įkelti nuotrauką',
		'insert_img' => 'Įterpti nuotrauką',
		'textlength_warn' => 'Jūs viršijote 8000 ženklų ribą.',
		'placeholder_paypal' => 'Jūsų užmokesčiui išmokėti',
		'placeholder_address' => 'Už sutartį ir apsakaitą',
		'paypal_iban' => 'Paypal, PaySera arba IBAN',
		'skype' => 'Skype',
		'set_price' => 'Nurodykite kainą.',
		'your_price' => 'Jūsų kaina',
		'hour' => 'valanda', // € už valandą
		'hours' => 'valandos',
		'per_hour' => 'už valandą', // € per hour
		'filesizewarning_exact' => 'Jūsų failas \'+img_size+\' Mb per didelis. Leidžiamas maksimalus dydis \'+maximg_size+\' Mb.',
		'payout' => 'Išmokėjimas',
		'newcontractor' => 'Naujas paslaugų teikėjas',
		'newcon_mailsubject' => 'Naujas paslaugų teikėjas registruotas',
		'changeavatar' => 'Įkelti naują profilio nuotrauką',
		'removeavatar' => 'Ištrinti profilio nuotrauką',
		'removeavatar_confirm' => 'Ar tikrai ištrinti profilio nuotrauką?',
		'commission' => 'Komisiniai', // commission, money for provider
		'finish_registration_btn' => 'Baigta registracija',
		'company' => 'Įmonės pavadinimas',

		// page contractorratings
		'conrat_title' => 'Klientų vertinimai',
		'conrat_tellclients' => 'Informuokite klientus, kad po kiekvienos paslaugos suteikimo jie gali Jus įvertinti. Čia rasite ankstesnius įvertinimus.',
		'clientmail_auto' => 'Klientai automatiškai gauna el. laišką.',
		'conrat_notpaidyet' => 'Vis dar neapmokėta, užsakymas nebus įvykdytas.',
		'manage_event_btn' => 'Valdyti užsakymą',
		'add_details' => 'Papildykite, jeigu užsakymo detalės nėra įvestos.',

		// page contractorschedule
		'consched_title' => 'Užsakymai',
		'protocol_note' => 'Tai paslaugos teikėjo baigiamosios pastabos',
		'mail_concompleted' => 'pranešta, kad Jūsų užsakymas baigtas vykdyti.', // person ...
		'please_rate' => 'Prašome įvertinti paslaugas.',
		'torating' => 'Į įvertinimus',
		'bookingfrom' => 'Užsakymas',
		'confirmcomplete_btn' => 'Patvirtinti suteiktą paslaugą',
		'apptinpast' => 'Užsakymo laikas jau praėjo',
		'customerconfirmneeded' => 'Gavėjas turi patvirtinti paslaugos gavimą',

		// page contractorweek
		'conweek_title' => 'Mano laikas',
		'setup_times' => 'Nustatyti laiką',
		'block_times' => 'Blokuoti laiką',
		'week_hint0' => 'Jeigu paslaugas pageidaujate teikti tik konkrečiu laiku, tuomet čia galite nustatyti tikslias paslaugos teikimo valandas.',
		'week_hint1' => 'Atkreipkite dėmesį, kad bet koks paslaugų teikimo laiko apribojimas gali sumažinti klientų skaičių.',
		'week_hint2' => 'Mes siūlome vengti nurodyti konkrečius paslaugų teikimo laikus. Jeigu Kliento pasirinktas laikas Jums bus nepriimtinas, Jūs visuomet Klientui galėsite pasiūlyti kitą, Jums patogų laiką.',
		'week_hint3' => 'Paslaugos teikimo laikus bet kada galite pakeisti.',
		'week_hint4' => '- Norėdami pasirinkti laiką, paspauskite ir judėkite su kursoriumi.',
		'week_hint5' => '- Pasirinkto laiko paspaudimas jį vėl pašalina.',
		'week_updatesuccess' => 'Savaitės laikas sėkmingai aktualizuotas.',
		'week_warnonleave' => 'Savaitės laikas vis dar neišsaugotas. Norite išeiti ir puslapio?',
		'preview' => 'Peržiūra',
		'saveweek_btn' => 'Išsaugoti savaitės laikus',
		'favoritetimes' => 'Laikų nustatymas',

		// page eventhistory
		'evhis_title' => 'Užsakymų istorija',
		'put_eventid' => 'Įveskite užsakymo numeris.',
		'eventhistoryfor' => 'Užsakymo Nr. ~eventid~ istorija',
		'recent_eventdata' => 'Aktualios užsakymo datos',
		'intotal' => 'viso', // insgesamt

		// page ipn
		'payment_success' => 'Mokėjimas atliktas sėkmingai',
		'payment_success_message' => 'Ačiū už apmokėjimą. Jūs sėkmingai tapote Kvanto.lt Premium nariu ir galite mėgautis visais sistemos privalumais.', // Thanks for your payment. You are now Premium member at Kvanto.lt and can enjoy all advantages!
		'payment_fail_title' => 'Mokėjimas nepavyko',
		'payment_fail' => 'Deja mokėjimas nutrūko arba įvyko kita problema.',
		'mail_paid1' => 'Gavome Jūsų mokėjimą. Pasirengę vykdyti užsakytas paslaugas. Paslaugų teikėjas su Jumis netrukus susisieks.',
		'mail_paid2' => 'Toliau įveskite užsakymo detales',
		'clearance_success' => 'Gavome Jūsų mokėjimą. Dėkojame.',
		'deposit_success' => 'Gavome Jūsų apmokėjimą. Jūsų įnašas aktyvuotas. Dėkojame.',
		'trypaymentagain' => 'Galite bandyti dar kartą sumokėti, paprasčiausiai ^1paspauskite čia^2.',

		// page mbcontact
		'contact_intro' => 'Mums galite čia parašyti žinutę. Mes su Jumis netrukus susisieksime.',
		'yourmessage' => 'Jūsų žinutė',
		'yourname' => 'Jūsų vardas',
		'youremail' => 'Jūsų el. pašto adresas',
		'contactto' => 'Kam',

		// page mbmessages
		'msg_title' => 'Privačios žinutės',
		'msgfrom' => 'Žinutė nuo',
		'msganswer' => 'Atsakyti į šią žinutę',
		'msglist' => 'Visų žinučių sąrašas',
		'msgselferror' => 'Oi, sau neturėtumėte siųsti žinučių.',
		'msgerror1' => 'Jūs dar negalite siųsti žinučių.',
		'msgerror2' => 'Šis narys negali gauti žinučių.',
		'nameunknown' => 'Vardas neatpažįstamas',
		'msgto' => 'Žinutė skirta',
		'yourmsgto' => 'Jūsų žinutė skirta',
		'msgtocontractor' => 'Jūsų žinutė paslaugų teikėjui bus išsiusta el. paštu.',
		'msgtoclient' => 'Jūsų žinutė bus išsiųsta vartotojui el. paštu.',
		'msgtooperator' => 'Jūsų žinutė mums bus atsiųsta el. paštu.',
		'emailsecret' => 'Jūsų el. pašto adresas nebus matomas.',
		'copysaved' => 'Viena kopija bus saugoma pas mus.', // email copy
		'msg_to_us' => 'mums',
		'prevmessages' => 'Ankstesnės žinutės',
		'msgcontent' => 'Turinys',
		'sent' => 'Išsiųsta',
		'received' => 'Gauta',
		'insertmsg' => 'Įrašyti žinutę …',
		'msgsent' => 'Jūsų žinutė išsiųsta.',

		// page mbupload
		'filetype_disallowed' => 'Toks formatas neleistinas',
		'filename_exists' => 'Failas jau egzistuoja',
		'nouploadfolder' => 'Įkelimo sąrašas neegzistuoja.',

		// page pay
		'pay_title' => 'Mokėjimas',
		'deducting' => 'išskaičiuota', // minus deposit (positive balance)
		'so_only' => 'Taigi tik', // payment minus x, so only ...
		'reservation_from' => 'Rezervavo',
		'youwerebooked' => 'Jūsų paslaugas rezervavo ~name~ (rezervacijos Nr. ~bookid~)', // leave ~name~ and ~bookid~
		'paidbydeposit' => 'Jūsų paslaugos buvo apmokėtos turimu įnašu ir bus teikiamos.',
		'contactclient' => 'Prašau susisiekite su klientu',
		'appts_probexist' => 'Šiuo atveju klientas pateikė užsakymą, pasižiūrėkite į ^1užsakymų sąrašą^2.',
		'confirmtime' => 'Prašome patvirtinti šį užsakymo laiką savo užsakymų sąraše', // Bitte bestätigen Sie diesen Termin in Ihrer Terminliste
		'waitforpay' => 'Mes dar turime sulaukti apmokėjimo.',
		'appts_reserved' => 'Užsakymas ~~~ rezervuotas',
		'appts_booked' => 'Užsakymas ~~~ padarytas', // confirmed
		'bookconfirmed_deposit' => 'Užsakymas buvo apmokėtas turimu įnašu. Rezervacija patvirtinta.',
		'cansendmsg' => 'Esant poreikiui galite paslaugos teikėjui ^1parašyti žinutę^2.',
		'pleasepayamount' => 'Prašau apmokėkite sąskaitą, kurios suma ~~~. Tik tuomet Jūsų užsakymas bus patvirtintas.', // leave ~~~
		'bookedby' => 'Jūs užsakėte ~name~ paslaugas.', // leave ~name~
		'booking_bookid' => 'Užsakymo Nr. ~bookid~.', // leave ~bookid~
		'booking_success' => 'Užsakymas sėkmingai atliktas',
		'booking_thanks' => 'Dėkojame už Jūsų užsakymą.',
		'appts_activated' => 'Jūsų ^1užsakymai^2 aktivuoti.',
		'confirmwassent' => 'Jūs gavote patvirtinančią žinutę.',
		'con_willcontact' => 'Paslaugų teikėjas ~~~ su Jumis netrukus susisieks.',
		'put_details' => 'Toliau įtraukite užsakymo detales',
		'con_contactbefore' => 'Jeigu pageidaujate, galite prieš tai susisiekti su paslaugų teikėju',
		'goodluck' => 'Sėkmės!',
		'confirmpaymail' => 'Gavę Jūsų apmokėjimą, patvirtinsime Jūsų užsakymą el. paštu.',
		'servicefor' => 'Paslaugos ~client~ nuo ~contractor~', // leave ~client~
		'paybooking' => 'Apmokėti užsakymą',
		'confirmbooking' => 'Patvirtinti užsakymą',
		'nobookingchosen' => 'Nepasirinktas užsakymas.',
		'nobookingfound' => 'Neradome Jūsų užsakymo.',
		'chosentimes' => 'Pasirinkti laikai',
		'chosenoffer' => 'Pasirinktas pasiūlymas',
		'remainingdeposit' => 'Likutis',
		'bookcontractor' => 'Užsakyti paslaugų teikėją',
		'bookamount' => 'Užsakymo suma',
		'paywithinday' => 'Mokėjimą turite atlikti per 24 val. kitu atveju turėsime anuliuoti Jūsų užsakymą.',
		'bankpayhint' => 'Apmokate mokėtiną sumą banko pavedimu. Tik tuomet, kai gausime Jūsų apmokėjimą, patvirtinsime Jūsų užsakymą.',
		'paypalpayhint' => 'Jūsų užsakymas bus netrukus patvirtintas. Pasirinktas laikas Jums rezervuotas.',
		'paymillpayhint' => 'Jūsų užsakymas bus netrukus patvirtintas. Pasirinktas laikas Jums rezervuotas.',
		'btn_booknow' => 'Užsakyti dabar',
		'verification' => 'Patvirtinimas',
		'paymentwithprovider' => 'Prašome apmokėti paslaugas tik po to kai jos buvo suteiktos. Apmokėjimą tiesiogiai gauna paslaugos tiekėjas, bet ne Kvanto.',
		'providergetscontact' => 'Toliau paslaugų teikėjas gaus jūsų duomenis, patvirtins užsakymą ir susisieks su jumis.',
		'verification_hint1' => 'Užsakymui patvirtinti vieną kartą prašome įvesti jūsų banko kortelės numerį.',
		'verification_hint2' => 'Tik patvirtinimui. Pinigai <b>nebus</b> nuskaičiuojami.',
		'verification_placeholder' => 'pvz. 4567 8912 4556 1234 2547',
		'verification_error' => 'Klaida: Kortelės numeris yra neteisingas',
		'verification_success' => 'Patvirtinimas sėkmingas',
		'verification_done' => 'Ačiū už patvirtinimą',

		// contratorlist search
		'search_results' => 'Paieškos rezultatai',
		'found' => 'rasta',
		'search_label' => 'Paslaugų paieška',
		'searchlocation_label' => 'Apriboti teritoriją',
		'all_locations' => 'Visos vietovės',
		'search_placeholder' => 'Ieškoti paslaugos, profesijos arba vardo', // Ieškoti pagal paslaugą arba vardą …
		'search_clear' => 'Išvalyti paiešką',
		'nothing_found' => 'Nieko nerasta pagal pateiktą užklausą.',
		'newest_contractors' => 'Naujausi paslaugų teikėjai',
		'random_contractors' => 'Vieni iš gausybės paslaugų teikėjų',
		'alphabetic_contractors' => 'Paslaugų teikėjų sąrašas (pagal abėcėlę)',
		'showall_contractors_btn' => 'Rodyti visus paslaugų teikėjus',
		'all_contractors' => 'Visi paslaugų teikėjai',

		// page forumprofile
		'answer' => 'Atsakymas',
		'answers' => 'Atsakymai',
		'question' => 'Klausimas',
		'questions' => 'Klausimai',
		'comment' => 'Komentaras',
		'comments' => 'Komentarai',
		'bestanswers' => 'Geriausi atsakymai', // Geriausi atsakymai
		'votesreceived' => 'Mėgsta', // Gavo balsų
		'bestanswer_iconhover' => 'Įvertinimai už geriausius atsakymus',
		'thumbsup_iconhover' => 'Kiek žmonių mėgsta',
		'newestanswers' => 'Aktualūs atsakymai',
		'noansweryet' => 'Kol kas jokių atsakymų.',
		'all_answers' => 'Visi atsakymai',
		'reputation' => 'Įvertinimas',
		'points' => 'Taškai',
		'weekhistory' => '7 dienų istorija',
		'aboutme' => 'Apie mane',
		'aboutus' => 'Apie mus',
		'service' => 'Paslaugos',
		'inforum' => 'Forume',
		'secret' => 'slapta',
		'private_data' => 'asmeniniai duomenys',
		'nonpublic' => 'ne vieša informacija',
		'needfulldata' => 'Norėdami registruotis paslaugų teikėju, turite pateikti visus ir išsamius duomenis.',
		'fullnamehint' => 'Nurodydami pilną vardą ir pavardę užsitikrinsite didesnį klientų pasitikėjimą.',
		'nocompanyname' => 'Jūsų tikras vardas (nė įmonė ir nė slapyvardis)!',
		'addresshint' => 'Gatvę ir vietą rašyti vienoje eilutėje ir atskirti kableliu.',
		'execution' => 'Atlikimas', // execution of the service
		'servicelocal' => 'vietoje pas mane',
		'serviceonline' => 'online',
		'serviceatcustomer' => 'pas klientą',
		'onlineonly' => 'paslauga tik online',
		'onlinetoo' => 'paslauga taip pat online',
		'perkm' => 'už km',
		'kmratehint' => 'Pavyzdys: 10 km yra tada',
		'eg' => 'pvz.',
		'profilecreated' => 'Profilis sėkmingai registruotas',
		'changemailpw' => 'Pakeisti el. pašto adresą arba slaptažodį',
		'specify_service' => 'Prašome įrašyti savo paslaugas.',
		'specify_portfolio' => 'Prašome apibūdinti savo teikiamas paslaugas.',
		'hourprice_hint' => 'Nepildyti, jei Jūs nepageidaujate valandinių paslaugų.',

		// page contract
		'contract_title' => 'Sutartis tarp paslaugų teikėjo ir tarpininko',
		'contract_hint' => 'Tai yra paskutinis paslaugų teikėjo registracijos žingsnis. Prašome perskaityti sutarties sąlygas ir pažymėti, kad sutinkate.',
		'conclude_contract' => 'Sudaryti sutartį',
		'registersuccess' => 'registracija sėkminga',
		'newcontract_subject' => 'Nauja paslaugų teikėjo sutartis',
		'newcontract' => 'Naujas teikėjas užsiregistravo teikėjo sutarčiai.',
		'contract_line_1' => 'Tarp tarpininko',
		'contract_line_2' => 'ir Jūsų kaip teikėjo',
		'contract_line_3' => 'bus sutarta',
		'contract_line_4' => 'Teikėjas sutinka su ^1taisyklėmis^2, kurios yra esminė šios sutarties dalis.',
		'contract_line_5' => 'Komisinis mokestis yra',
		'contract_line_6' => 'Sutartis pradeda galioti po tarpininko pritarimo.',
		'contract_line_7' => 'Prašome baigiant patvirtinti',
		'contract_line_8' => 'Aš garantuoju, kad mano duomenys yra teisingi ir turiu reikiamus leidimus siūlyti ir atlikti savo paslaugas.',
		'contract_line_9' => 'Aš perskaičiau ^1taisyklės^2 ir su jomis sutinku.',
		'contract_line_10' => 'Aš suprantu, kad klientams užsisakius paslaugas, sutartis sudaroma tarp teikėjo ir kliento. Operatorius yra tik tarpininkas.',
		'contract_line_11' => 'Paspaudus mygtuką teisėtai sudarote su mumis sutartį:',
		'contract_line_12' => 'Prašau pažymėkite langelius varnele.',
		'contract_line_13' => 'Dėkojame už Jūsų teikėjo registraciją.',
		'contract_line_14' => 'Jūsų duomenis patikrinsime ir aktyvuosime per 24 valandas.',
		'contract_line_15' => 'Esant nesklandumams, mes Jums apie tai pranešime el. paštu.',

		// dropdown main menu
		'contractorslist' => 'Visų paslaugų teikėjų sąrašas',
		'forcontractors' => 'Paslaugų teikėjui',
		'forclients' => 'Klientui',
		'toptopics' => 'Top Temos',

		// extra
		'motto' => 'Kvanto - vienas už visus ir visi už vieną',

		// page eventmanager
		'evman_title' => 'Įvykių valdymas',
		'events_available_title' => 'Galimi laikai',
		'events_allocated' => 'Deja visi galimi laikai jau užsakyti.',
		'events_available' => 'Kiti galimi laikai pas šį paslaugų teikėją dar laisvi. Galite juos pasirinkti.',
		'events_coordinate' => 'Atitinkami laikai',
		'events_allocated_client' => 'Tikėtina, kad visi laikai jau pasirinkti.',
		'events_findtime' => 'Kita paslaugų teikimo data dar turi būti suderinta:',
		'event_accepted_title' => 'Užsakymas priimtas',
		'event_accepted' => 'Dėkojame, Jūs pasirinkote užsakymą Nr. ~eventid~.',
		'backtoeventlist' => 'Toliau į užsakymų sąrašą',
		'event_hint_title' => 'Nuorodą į užsakymą',
		'event_hint' => 'Užsakymas Nr. ~eventid~ jau buvo priimtas iš ^1~name~^2 ',
		'event_backdetails' => 'Toliau į užsakymo detales',
		'event_rejectreason' => 'Užsakymo laiko atmetimo priežastys',
		'rejectplaceholder' => 'Įvardinti priežastį …',
		'reject_btn' => 'Atmesti',
		'event_rejected_title' => 'Užsakymo laikas atmestas',
		'event_rejected' => 'Jūs atmetėte užsakymą Nr. ~eventid~. Kitas paslaugų teikėjas perims užsakymą.',
		'already_rejected' => 'Jūs jau atmetėte užsakymą Nr. ~eventid~.',
		'newtimeproposed_title' => 'Pasiūlyti naują užsakymo laiką',
		'proposenewtime' => 'Pasiūlyti naują užsakymo Nr. ~eventid~ laiką.',
		'eventduration' => 'Užsakymo laikas: ~eventduration~ min',
		'starttime' => 'Pradžia',
		'addmoreproposals' => 'Pridėti kitus užsakymo laikų pasirinkimus?',
		'propose_btn' => 'Pasiūlyti',
		'event_proposed_title' => 'Pasiūlyti naujus užsakymo laikus',
		'event_proposed' => 'Jūs pasiūlėte naujus užsakymo Nr. ~eventid~ laikus. Vartotojas bus apie tai informuotas ir pasirinks užsakymo laiką.',
		'event_iscompleted' => 'Užsakymas Nr. ~eventid~ jau įvykdytas.',
		'event_notpaidyet' => 'Užsakymas Nr. ~eventid~ dar neapmokėtas.',
		'event_alreadyaccepted' => 'Užsakymas Nr. ~eventid~ jau priimtas.',
		'event_notexist' => 'Užsakymo laikas neegzistuoja.',
		'contractor_firstbooked' => 'Pirmiau užsakytas paslaugų teikėjas', // contractor who rejected the event
		'eventtime' => 'Užsakymo laikas',
		'reject_event_btn' => 'Atmesti laiko pasiūlymą',
		'propose_event_btn' => 'Pasiūlyti kitą laiką',
		'accept_event_btn' => 'Patvirtinti pasiūlytą laiką',
		'eventproposals' => 'Naujo laiko pasiūlymai',
		'clickconfirm' => 'Paspaudus patvirtinamas laikas',

		// dropdown extras
		'pointsystem' => 'Taškų sistema',
		'monthbest' => 'Šio mėnesio geriausi',
		'newsletter' => 'Naujienlaiškis',
		'yourquestions' => 'Jūsų klausimai',
		'youranswers' => 'Jūsų atsakymai',
		'youractivity' => 'Jūsų veiklos',

		// mini user statistic in top menu
		'points' => 'taškai',
		'bestanswers' => 'geriausi atsakymai',
		'votesreceived' => 'mėgsta',

		// page userrecommend
		'recommend_hint' => 'Čia galite pasiūlyti paslaugų teikėją, kuris pas mus dar nėra prisiregistravęs. Mes peržiūrėsime Jūsų pasiūlymą ir susisieksime su paslaugos teikėju el. paštu.',
		'placeholder_email_con' => 'Teikėjo el. paštas',
		'newcon_suggested' => 'Naują teikėjas pasiūlytas',
		'back_services' => 'Atgal į paslaugų puslapį',
		'specify_fullname_con' => 'Prašome įrašyti teikėjo vardą.',
		'specify_email_con' => 'Prašome įrašyti teikėjo el. paštą.',
		'specify_service_con' => 'Prašome įrašyti teikėjo paslaugas.',
		'specify_address_con' => 'Prašome įrašyti teikėjo adresą.',
		'userrecommended' => 'Vartotojas pasiūlytas, nuoširdžiai dėkojame.',

		// page offercreate
		'offer_pagetitle' => 'Sukurti pasiūlymą',
		'offer_edit' => 'Redaguoti pasiūlymą',
		'offer_hint' => 'Čia Jūs galite įkelti pasiūlymą, kuris yra nepriklausomas nuo užsakymo datos. Pvz. fotografas gali pasiūlyti vestuvių fotosesiją už 1800 €, vietoje valandinių fotografo paslaugų.',
		'offer_hint_2' => 'Jūs galite įrašyti daugiausiai 5 pasiūlymus. Visi pasiūlymai bus rodomi Jūsų užsakymų puslapyje.',
		'offertitle' => 'Pasiūlymo pavadinimas',
		'offertitle_placeholder' => 'pvz. vestuvių nuotraukos su retušavimu',
		'offerprice' => 'Pasiūlymo kaina',
		'offerprice_placeholder' => 'pvz. 1800',
		'specify_price' => 'Prašau įrašykite kainą.',
		'duration' => 'Trukmė',
		'duration_placeholder' => 'pvz. 5',
		'specify_duration' => 'Prašau įrašyti apytikslę trukmę.',
		'offerend' => 'Pasiūlymo pabaiga.',
		'offerend_hint' => 'Palikti tuščią, jei ilgalaikis.',
		'offerduration_hint' => 'Palikti tuščią, jei nežinoma.',
		'description' => 'Aprašymas',
		'youroffer_hint' => 'Išsamiai aprašykite savo pasiūlymą ir pridėkite nuotrauką ar video filmukų. Paslaugą užsakyti bus galima per Jūsų užsakymų puslapį. ',
		'new_offer' => 'Naujas pasiūlymas ',
		'newcon_offer' => 'Naujas pasiūlymas sukurtas', // new offer created
		'flags' => 'Flags',
		'back_profile' => 'Atgal į Jūsų profilį',
		'back_offers' => 'Atgal į Jūsų pasiūlymus',
		'another_offer' => 'Dar vienas pasiūlymas',
		'offer' => 'Pasiūlymas',
		'offers' => 'Pasiūlymai',
		'offer_activated' => 'Pasiūlymas aktyvuota.',
		'offer_deactivated' => 'Pasiūlymas deaktyvuota.',
		'offer_created' => 'Pasiūlymas sukurtas.',
		'offer_created_thx' => 'Pasiūlymas sukurtas, labai dėkojame.',
		'offer_edited' => 'Pasiūlymas aktualizuotas.',
		'offer_deleted' => 'Pasiūlymas ištrinta.',
		'offer_approved' => 'Pasiūlymas patvirtinta.',
		'offer_disapproved' => 'Pasiūlymas nepritarta.',
		'offer_tobechecked' => 'Šis pasiūlymas yra tikrinamas ir netrukus bus paskelbtas.',
		'offer_gotdisapproved' => 'Šis pasiūlymas neatitiko kriterijų.',
		'offer_gotdeleted' => 'Šis pasiūlymas buvo ištrintas.',
		'offer_gotdeactivated' => 'Šis pasiūlymas buvo deaktyvuotas.',
		'offer_expired' => 'Šis pasiūlymas jau nebegalioja.',
		'premium_paid' => 'Premium sumokėta',
		'premium_activated' => 'Premium aktivuoti',
		'options' => 'Nustatymai',
		'edit' => 'papildyti',
		'deactivate' => 'deaktyvuoti',
		'deactivated' => 'deaktyvuota',
		'activate' => 'aktyvuoti',
		'activated' => 'aktyvuota',
		'remove' => 'pašalinti',
		'deleted' => 'ištrinta',
		'needcontractor' => 'Norėdami kurti pasiūlymus Jūs turite ^1užsiregistruoti kaip paslaugos teikėjas^2.',

		// page contractoroffers
		'conoff_title' => 'Jūsų pasiūlymai',
		'nooffers' => 'Dar neįkeltas nė vienas pasiūlymas.',
		'table_created' => 'sukurta',
		'conoff_intro' => 'Čia matote sąrašą su visais savo pasiūlymais. Jūs galite sukurti naują pasiūlymą arba papildyti esamus.',
		'offer_create_btn' => 'Sukurti naują pasiūlymą',

		// page clientrequests
		'clirequ_title' => 'Jūsų paslaugų prašymai',
		'norequests' => 'Dar neįdėtas nė vienas paslaugų prašymas.',
		'clirequ_intro' => 'Čia Jūs matote savo paslaugų prašymą, kartu su ateinančiais pasiūlymais. Jūs taip pat galite sukurti naują paslaugų prašymą.',
		'request_create_btn' => 'Įdėti paslaugų prašymą',
		'newrequest_create_btn' => 'Įdėti naują paslaugų prašymą',
		'ownrequest_create_btn' => 'Įdėti savo paslaugų prašymą',
		'request' => 'Skelbimas',
		'requests' => 'Skelbimai',
		'bestprice' => 'Geriausia kaina',
		'priceoffers' => 'Kainų pasiūlymai',
		'removerequest_confirm' => 'Ar Jūs tikrai norite ištrinti paslaugų prašymą?',
		'choosebid' => 'Pasirinkti pasiūlymą',
		'nobidsyet' => 'dar jokių pasiūlymų',
		'disabled' => 'deaktyvuota',
		'notapprovedyet' => 'dar ne patvirtinta',
		'ischecked' => 'tikrinamas',
		'share' => 'Share',
		'sharefacebook' => 'Share on Facebook',
		'adminrequ_title' => 'Admin: Skelbimai',

		// page requestlist
		'all_requests' => 'Visi paslaugų prašymai',
		'my_requests' => 'Mano paslaugų prašymai',
		'reli_search_label' => 'Skelbimų paieška',
		'reli_search_placeholder' => 'pvz. fotosesija', // Berlin
		'endsin' => 'baigiasi per', // days, hours ...

		// page offerlist
		'all_offers' => 'Visi pasiūlymai',
		'my_offers' => 'Mano pasiūlymai',
		'offli_search_label' => 'Pasiūlymų paieška',
		'offli_search_placeholder' => 'pvz. remontas', // Berlin
		'ownoffer_create_btn' => 'Įdėti savo pasiūlymas',

		// page requestcreate
		'request_pagetitle' => 'Įdėti paslaugų prašymą',
		'request_create' => 'Sukurti paslaugų prašymą',
		'request_open' => 'Atidaryti paslaugų prašymą',
		'request_edit' => 'Redaguoti paslaugų prašymą',
		'request_savebtn' => 'Išsaugoti paslaugų prašymą',
		'request_hint_1' => 'Čia Jūs galite paviešinti paslaugų prašymą. Tiekėjai pasiūlys savo kainas už Jums reikalingą paslaugą. Tuomet Jūs galite išsirinkti geriausią pasiūlymą.',
		'request_hint_2' => 'Visi paslaugų prašymai rodomi centralizuotai ^1paslaugų prašymų puslapis^2',
		'request_hint_3' => 'Kai Jūs išsirinkate vieną iš tiekėjų, tuomet turite sumokėti sutartą kainą.',
		'requesttitle' => 'Man reikalingas',
		'requesttitle_placeholder' => 'pvz. Pastatyti dušo kabiną',
		'requestprice' => 'Mein Budget',
		'requestprice_placeholder' => 'z. B. 250',
		'specify_price' => 'Prašau nurodyti kainą.',
		'duration_placeholder' => 'pvz. 5',
		'specify_duration' => 'Prašau nurodyti apytikslę darbo trukmę.',
		'requestend' => 'Skelbimas online iki',
		'requestend_hint' => 'Galiojimo trukmė maks. 2 savaitės.',
		'requestduration_hint' => 'Palikti laisvą, jei neįmanoma nustatyti.',
		'yourrequest_hint' => 'Detaliai aprašykite savo paslaugų prašymą ir pridėkite nuotraukas arba Youtube filmuką.',
		'new_request' => 'Naujas paslaugų prašymas',
		'newcon_request' => 'Naujas paslaugų prašymas sukurtas', // new request created
		'back_requests' => 'Atgal į Jūsų paslaugų prašymus',
		'another_request' => 'Sukurti tolesnius paslaugų prašymus',
		'request_created' => 'Skelbimas sukurtas',
		'request_activated' => 'Skelbimas aktyvuotas',
		'request_deactivated' => 'Skelbimas deaktyvuotas',
		'request_gotcreated' => 'Skelbimas sukurtas, maloniai dėkojame.',
		'request_edited' => 'Skelbimas aktualizuotas',
		'request_deleted' => 'Skelbimas ištrinta',
		'request_approved' => 'Skelbimas patvirtinta',
		'request_disapproved' => 'Skelbimas nepritarta',
		'specify_requesttitle' => 'Prašau įveskite paslaugų prašymo pavadinimą.',
		'specify_date' => 'Prašau įveskite pabaigos datą.',
		'specify_description' => 'Prašau įveskite aprašymą.',
		'format' => 'Formatas',
		'specify_realname' => 'Prašau pirmiausia įrašykite ^1savo vardą^2.',
		'specify_realname_request' => 'Tam, kad galėtumėte sukurti paslaugų prašymą, pirmiausia įrašykite ^1savo vardą^2.',
		'mail_btncheck_request' => 'Patikrinti duomenis + paslaugų prašymą priimti',
		'mail_btncheck_offer' => 'Patikrinti duomenis + pasiūlymą priimti',

		// page adminoffers
		'adminoffers_title' => 'Admin: Pasiūlymai',
		'offerid' => 'Pasiūlymo Nr.',
		'nr' => 'Nr.', // number

		// page adminsearchtrack
		'adminsearch_title' => 'Admin: Search Tracking',
		'searchtrack' => 'Search Tracking',
		'searchterm' => 'Paieškos žodis', // number
		'ipaddress' => 'IP adresas',
		'menubtn_admin_searchtrack' => '🔍',
		'nodata' => 'nėra duomenų',

		// page bid
		'bid_pagetitle' => 'Ieškota', // Angebot abgeben
		'request_notexist' => 'Šis paslaugų prašymas negalioja.',
		'request_expired' => 'Šis paslaugų prašymas jau nebegalioja.',
		'alreadybid' => 'Šiam pasiūlymui Jūs įvedėte datą ~date~.',
		'service_required' => 'Reikalingi šie darbai',
		'bid_ends' => 'Skelbimas baigiasi',
		'yourpricebid' => 'Jūsų kainos pasiūlymas',
		'yourprice' => 'Jūsų kaina',
		'yourprice_placeholder' => 'pvz. 200',
		'yourcomment' => 'Jūsų pastaba',
		'bid_pricehint' => 'Prašau atkreipti dėmesį, kad Jūsų pasiūlymas yra privalomas. Tai reiškia, kad už Jūsų pasiūlytą kainą privalote suteikti aprašytą paslaugą.',
		'postoffer_btn' => 'Siūlyti',
		'postsuccess' => 'Sėkmingai pasiūlyta',
		'request_tobechecked' => 'Šis paslaugų prašymas yra tikrinamas ir netrukus bus paskelbtas.',
		'request_gotdisapproved' => 'Šis paslaugų prašymas neatitiko kriterijų.',
		'request_gotdeleted' => 'Šis paslaugų prašymas buvo ištrintas.',

		// page bookingbutton
		'bookbtn_title' => 'Užsakymo mygtukas Jūsų internetiniam puslapiui',
		'bookbtn_intro' => 'Įterpikite užsakymo mygtuką savo internetiniam puslapiui. Taip Jūsų lankytojai turės galimybę iš karto užsakyti Jūsų teikiamą paslaugą!',
		'bookme_example' => 'Užsakymo mygtuko pavyzdžiai',
		'bookmenow_btn' => 'Užsakyk mane dabar', // Užsisakyk šią paslaugą dabar
		'bookbtn_label' => 'Užsakymo mygtuko antraštė',
		'buttonstyle' => 'Užsakymo mygtuko vaizdinė išraiška',
		'simplelink' => 'Paprasta nuoroda',
		'menu_bookingbutton' => 'Mygtukas',

		// paymill
		'paymill_title' => 'apmokėta per Paymill',
		'paymill_error' => 'Atsirado nenumatyta klaida.',
		'contactus' => 'Prašome susisiekti su mumis',
		'missing_data' => 'Trūksta duomenų',

		// userforumprofile
		'recommendation' => 'rekomendacija',
		'recommendations' => 'rekomendacijos',
		'recommendedby' => 'Šie asmenys rekomenduoja ~username~',
		'personrecommendedby' => 'Šis asmuo rekomenduoja',
		'irecommend' => 'Rekomenduoju ~username~', // Aš rekomenduoju ~username~
		'unrecommend' => 'Atsiimti rekomendaciją?',
		'recommends' => '~username~ rekomenduoja',

		// adminlogview
		/*
		'adviewlog_title' => 'Event Logs',
		'mail_sent' => 'E-Mail versendet',
		'msg_sent' => 'Nachricht versendet',
		'msg_deleted' => 'Nachricht gelöscht',
		'eventname' => 'Eventname',
		'logdata' => 'Logdaten',
		'profile_edited' => 'Profil bearbeitet',
		'avatar_removed' => 'Profilbild entfernt',
		'avatar_uploaded' => 'Profilbild hochgeladen',
		'bid_posted' => 'Preisangebot gepostet',
		'payment_deleted' => 'Zahlung gelöscht',
		'contractor_weekupdated' => 'Wochenzeiten aktualisiert',
		'profile_created' => 'Profil angelegt',
		'client_depositorder' => 'Kunde bestellt Guthaben',
		'contractor_paid' => 'Anbieter wurde bezahlt',
		'contractor_contracted' => 'Anbieter akzeptiert Vertrag',
		'deposit_release' => 'Guthaben freigegeben',
		'event_deleted' => 'Termin gelöscht',
		'client_clearance' => 'Kontoausgleich ausgelöst',
		'contractor_recommended' => 'Vorschlag eines Anbieters',
		'client_creditnote' => 'Startguthaben aktiviert', // voucher
		*/

		// page businesscard
		'bcard_title' => 'Jūsų suasmeninta vizitinė kortelė', // Ihre persönliche Visitenkarte
		'bcard_intro' => 'Jei esate Premium narys, jums bus išsiųstos asmeninės vizitinės kortelės. Esant standartiniu nariu, korteles galite užsisakyti pas mus atskirai, tiesiog parašykite mums.', // Wenn Sie Premium-Mitglied sind, erhalten Sie von uns Ihre persönlichen Visitenkarten zugesendet. Als Standard-Mitglied können Sie Visitenkarten separat bestellen.
		'bcard_preview' => 'Peržiūrėti', // Vorschau
		'bcard_design' => 'Dizainas',
		'website' => 'Tinklapis',
		'bookme' => 'Užsakykite mane',

		// page premium
		'premium_title' => 'Premium planai paslaugų teikėjams', // Premium planai ir kainos
		'premium_intro' => 'Tapdami Premium arba VIP nariais gausite daug vertingų privalumų. Susipažinkite su detalėmis:',
		'youarecurrently' => 'Dabartinis planas',
		'member_basic' => 'Basic narys',
		'member_premium' => 'Premium narys',
		'member_vip' => 'VIP narys',
		'yourownpage' => '^1Jūsų asmeninis puslapis^2 su pagrindine informacija ir jūsų nuotrauka',
		'servicedesc_page' => 'Paslaugos aprašymas jūsų puslapyje',
		'servicedesc_limited' => '(ribotas: tik tekstas, be nuorodų ir paveikslėlių)',
		'servicedesc_unlimited' => '(neribotas: tekstas, nuorodos, nuotraukos ir video)',
		'createoffer_basic' => 'Sukurkite ^11 specialų pasiūlymą^2 geresnei reklamai ir pardavimams padidinti',
		'createoffer_premium' => 'Sukurkite ^15 specialius pasiūlymus^2 geresnei reklamai ir pardavimams padidinti',
		'createoffer_vip' => 'Sukurkite ^1 iki 20 specialų pasiūlymą^2 geresnei reklamai ir pardavimams padidinti',
		'bookcal_basic' => 'Jūsų asmeninis paslaugų ^1rezervavimo kalendorius^2 su ^3laiko nustatymais^4 ir ^5ICS eksportavimo^6 galimybe',
		'eventmanagement' => 'Užsakymų laiko administravimas: pakeiskite užsakymo laiką, priimkite ar atmeskite užsakymą',
		'bookbtn_external' => '^1Užsakymo mygtukas^2 jūsų internetinei svetainei ir Facebook puslapiui',
		'gopremium' => 'Tapkite Premium',
		'premium' => 'Premium',
		'govip' => 'Tapkite VIP',
		'commission_bookings' => 'Mokestis už užsakymus',
		'commission_details' => '12 mėnesiams, po to 25%',
		'monthly_price' => 'Mėnesio mokestis', // translated as Value by purpose (psychology)
		'free' => 'nemokama', // price
		'become' => 'Tapkite', // become premium member
		'subdomain_desc' => 'Subdomenas jūsų puslapiui, pavyzdžiui "marius.kvanto.lt"',
		'gcal_integration' => '^1Google Kalendoriaus^2 integracija į jūsų užsakymų kalendorių',
		'payment_integration' => 'Mokėjimų integracija: gaukite pinigus iš kliento iškart po jūsų paslaugos užsakymo',
		'sendprivatemessages' => 'Siųskite ^1asmenines žinutes^2 visiems Kvanto.lt nariams',
		'vcardcontact' => 'Kontaktinių duomenų pateikimas vartotojui patogiai išsisaugoti telefone ar kompiuteryje V-Card formatu vieno mygtuko paspaudimu.',
		'adfree' => 'Visiškai be reklamų',
		'forever' => 'visada',
		'eurospermonth' => '€/mėn.',
		'become_contractor' => 'Tapkite paslaugų teikėjas',
		'become_premium' => 'Tapkite Premium',
		'become_premiummember' => 'Tapkite Premium nariu dabar', // Jetzt Premium Mitglied werden
		'become_vipmember' => 'Tapkite VIP nariu dabar', // Jetzt VIP Mitglied werden
		'getbusinesscards_desc' => 'Gaukite ^1100 gražių vizitinių kortelių^2 užsisakę VIP narystę',
		'moneyback_desc' => 'Suteikiame 30 dienų pinigų gražinimo garantiją jeigu apsigalvotumėte.',
		'member_payment_hint' => 'Pirmas mokėjimą atliekate jūs, tolimesni mėnesiniai mokėjimai automatiškai nuskaičiuojami iš jūsų sąskaitos.',
		'needpremium' => 'Jūs turite būti Premium narys norint naudotis šia funkcija.',
		'needpremium_links' => 'Nuoroda nėra rodoma, kadangi narys neturi Premium teisių.',
        	'needpremium_email' => 'El. pašto nuoroda nėra rodoma, kadangi narys neturi Premium teisių.',
        	'needpremium_phone' => 'Telefono numeris nėra rodomas, kadangi narys neturi Premium teisių.',
        	'needpremium_offers' => 'Jeigu norite praplėsti savo pasiūlymų galimybes, pakeiskite planą į Premium.',
        	'needpremium_messages' => 'Būdamas Premium nariu, galėsite išsiųsti žinutes visiems.',
		'faq_head' => 'Dažniausiai užduodami klausimai',
		'faq_01_h1' => 'Kas vyks toliau po apmokėjimo?', // What happens after my payment?
		'faq_01_content' => 'Iškart po jūsų apmokėjimo visi Premium privalumai ir funkcijos bus aktyvuotos.', // After your payment all premium features get unlocked for you immediately.
		'faq_02_h1' => 'Kada bus atliktas sekantis apmokėjimas?', // When is my next billing?
		'faq_02_content' => 'Jūsų mokėjimų laikotarpis prasideda nuo jūsų pirmojo apmokėjimo už Premium narystę dienos ir bus nuskaičiuoajamas kas mėnesį tą pačią dieną.', // Your billing cycle starts from the day of your first payment and you will be charged monthly for your premium account.
		'faq_03_h1' => 'Ar galiu panorėjęs atšaukti Premium narystę?', // Can I downgrade at anytime?
		'faq_03_content' => 'Taip. Mes siekiame patenkinti visus jūsų verslo poreikius, nesvarbu ar jūsų veikla auga ar mažėja. Todėl jūs galite atsisakyti Premium plano bet kuriuo mėnesio metu.', // Yes. We meet your business needs wherever you are, whether you are growing or scaling back. You can upgrade or downgrade to the end of each month.
		'faq_04_h1' => 'Ar galiu atskirai pasirinkti norimus skirtingus privalumus?',// Can I choose only certain features that I need?
		'faq_04_content' => 'Ne, šiuo metu neturime pasirnktinai konfigūruojamų planų. Tapdami Premium ar VIP nariais jūs gausite visus Kvanto.lt sistemos teikiamus privalumus.', // No, we do not have feature-specific pricing plans. As premium member you benefit from the entire Kvanto system.
		'faq_05_h1' => 'Ar aš galiu apmokėti už visus metus?', // Can I pay for a yearly subscription?
		'faq_05_content' => 'Ne, šiuo metu nėra tokios galimybės. Mokėjimai atliekami kiekvieną mėnesį.', // No, this is currently not possible. We charge on a monthly basis to give everyone more flexibility. // Yes. Setmore has an Annual plan priced at $199 that includes all premium features. Your card will be charged immediately after signing up for the annual plan.
		'faq_06_h1' => 'Ar galiu atgauti pinigus jei Kvanto.lt nepatenkina mano verslo poreikių?', // Can I get my money back if something goes wrong?
		'faq_06_content' => 'Nors esame tvirtai įsitikinę, kad Kvanto.lt gali tapti nepakeičiama paslaugų užsakymų platforma, jūs galite atsisakyti Premium narystės ir per 30 dienų nuo pirmojo užsakymo pranešę mums galite susigrąžinti sumokėtus pinigus už Premium narystę.', // Yes, you have up to 30 days after your premium payment to notify us, if you are not satisfied. We refund you of course.
		'membership' => 'Narystė',
		'youarepremium' => 'Jūs esate Premium narys',
		'premiumtrial_promo' => 'Dovanojama Premium narystė užsisakius iki 2017.07.31',
		'premiumtrial_click' => 'Tapkite "Premium" nariu ir gaukite dovanų 6 mėnesių narystę nemokamai.',
		'premiumpayments' => 'Premium Payments',

		// premiumpay
		'membership_premium' => 'Premium narystė',
		'price_premium' => 'Premium narystės kaina',
		'membership_vip' => 'VIP narystė',
		'price_vip' => 'VIP narystės kaina',
		'vat_included' => '~vatvalue~ % PVM įskaičiuota', // leave ~vatvalue~, this will be replaced
		'payment' => 'Mokėjimas',

		// startpage
		'mainsearchlabel' => 'Rask specialistus visiems gyvenimo atvejams', // Surask savo specialistą
		'forexample' => 'Pavyzdžiui',
		'photograph_link' => 'fotograf', // custom links below search bar
		'photograph_linktext' => 'vestuvių fotografas', // name of link
		'dentist_link' => 'odontolog',
		'dentist_linktext' => 'odontologas',
		'mechanic_link' => 'mechanik',
		'mechanic_linktext' => 'auto mechanikas',
		'nanny_link' => 'auklė',
		'nanny_linktext' => 'auklė',
		'translator_link' => 'vertėj',
		'translator_linktext' => 'vertėjas',
		'trainer_link' => 'treneris',
		'trainer_linktext' => 'asmeninis treneris',
		'apartmentrepair_link' => 'remontas',
		'apartmentrepair_linktext' => 'buto remontas',
		'designer_link' => 'dizaineris',
		'designer_linktext' => 'dizaineris',
		'findinstantly_h1' => 'Greitai raskite paslaugų teikėjus',
		'findinstantly_text' => 'Greitai naršykite mūsų plačiame ir nuolat augančiame paslaugų teikėjų sąraše, kurie padės jums užbaigti savo užduotis. Nuo paprastų užduočių iki profesionalių paslaugų - Kvanto siūlo įvairias paslaugas. Tiesiog naudokite paieškos žymą rasti norimą specialistą, užsisakyti jį ar ją, ir jūsų problema bus greitai išspręsta.',
		'findinstantly_button' => 'Ieškokite paslaugos teikėjų',
		'timeyouneed_h1' => 'Užsakykite paslaugą jums tinkamu laiku',
		'timeyouneed_text' => 'Galite pasirinkti jums tinkamą pasalugos teikimo laiką. Ar jums reikia tik valandos ar visos dienos, galite pasirinkti laiką lengvai su mūsų patogiu kalendoriumi. Taip pat galite pasirinkti tam tikrus pasiūlymus, jei paslaugos tiekėjas siūlo tam tikrus pasiūlymus.',
		'timeyouneed_button' => 'Raskite paslaugos teikėją',
		'askquestion_h1' => 'Užduokite klausimus ir gaukite ekpertų atsakymus',
		'askquestion_text' => 'Prisijunkite prie mūsų bendruomenės ir gaukite atsakymus, patarimus ir rekomendacijas dėl jums aktualių problemų. Netgi galite užsisakyti ekspertą tiesiai į forumą, kuris padės išspręsti problemas asmeninės konsultacijos dėka.',
		'askquestion_button' => 'Ką norite sužinoti?',
		'becomeprovider_h1' => 'Tapkite paslaugos teikėju',
		'becomeprovider_text' => 'Lygiai taip pat paprasta, kaip ieškant paslaugų teikėjo, jūs galite pradėti siūlyti savo paslaugas ir padidinti savo žinomumą su Kvanto pagalba. Tapkite lengviau randamas naujų klientų ir taip padidinkite savo pajamas. Kvanto kasdien apsilanko tūkstančiai potencialių klientų, kuriems reikia jūsų pagalbos.',
		'becomeprovider_button' => 'Užsiregistruokite kaip paslaugos teikėjas',
		'offerpackages_h1' => 'Pasiūlykite paslaugų paketus',
		'offerpackages_text' => 'Jei jums reikia atlikti specialias paslaugas, kurios netelpa į valandinį užmokestį (pavyzdžiui, "vestuvių paketas" iš fotografo siūlomų paslaugų), galite reklamuoti juos iš anksto, kaip paslaugų paketą. Klientai galės įsigyti juos iš karto ir pasirinkti datą kalendoriuje. Daugiau pavyzdžių: "Vakarinis makiažas", "Namo vandentiekio techninė priežiūra", "3-jų mėnesių asmeninis fitneso treneris". Tegul pasaulis žino, ką sugebate.',
		'offerpackages_button' => 'Sukurkite paslaugų paketą',
		'clientmanagement_h1' => 'Patogi klientų valdymo sistema',
		'clientmanagement_text' => 'Kai jūsų paslauga užsakoma, galite lengvai valdyti užsakymus savo paskyroje ir planuoti laikus. Mes suteikiame jums įrankius, kurie padeda jums būti produktyvesniais, reguliuoti finansus ir tvarkyti kalendorių. Viskas vienoje vietoje. Ar visada norėjote pagerinti savo produktyvumą? Kvanto išpręs visas problemas ir leis džiaugtis maloniu bendradarbiavimu tarp jūsų ir kliento.',
		'clientmanagement_button' => 'Atidaryti valdymo skyrelį',
		'getpremium_h1' => 'Tapkite Premium nariu',
		'getpremium_text' => 'Jeigu norite Kvanto naudotis kaip kasdieniu įrankiu klientų valdymui, jums tikrai patik VIP narystė. Gausite daugiau galimybių pasiekti savo klientus, nematysite reklaminių žinučių, patogesnė programų integraciją ir 100 aukštos kokybės verslo kortelių pristatyta jums, tiesiai į namus.',
		'getpremium_button' => 'Pamatykite Premium planus',
		'participate_h1' => 'Kelkite reputaciją ir didinkite savo pažįstamų ratą',
		'participate_text' => 'Dalyvaukite Kvanto sukurtume ekspertų klausimų-atsakymų forume. Atsakydami į klausimus jūs gausite reputacijos taškų. Leiskite potencialiems klientams pamatyti jūsų profesinius įgūdžius ir savo žinias. Leiskite žmonėms jus rekomenduoti ir pristatyti savo draugams, paspaudus dalinimosi mygtukus socialinėje medijoje. Greitai auginkite savo klientų ratą.',
		'participate_button' => 'Padidinkite savo reputaciją',
		'getbookingpage' => 'Gaukite savo užsakymų puslapį jau dabar',
		'signupnow' => 'Užsiregistruokite',
		'ask_service' => 'Prašyti paslaugos',

		// IMPORTANT FOR QA-THEME.PHP
		'lang_code' => 'lt',
		'headtitle' => 'Kvanto - Rask specialistus visiems gyvenimo atvejams', // Surask savo asmeniškai specialistą
		'interviewlabel' => 'Interviu',
		'interviewtag' => 'interviu',
		'lang_askquestion' => 'Užduok savo klausimą!',
		'lang_withoutregistration' => 'nemokamai + be registracijos',
		'lang_qu_alreadyexists' => 'jau egzistuoja',
		'lang_qu_closed' => 'uždarytas',
		'lang_footer_about' => 'apie mus',
		'lang_footer_terms' => 'taisyklės',
		'lang_footer_legal' => 'teisinė informacija',
		'lang_footer_contacts' => 'kontaktai',
		'lang_footer_premium' => 'premium',
		'lang_shortlink' => 'trumpa nuoroda į šį puslapį',
		'lang_print' => 'spausdinti',
		'lang_sharefacebook' => 'dalintis Facebook',
		'lang_sharegoogleplus' => 'dalintis Google Plus',
		'lang_thismember' => 'Narys',
		'lang_thisguest' => 'Šis svečias',
		'lang_wrotethosequ' => 'paprašė šiuos klausimus',
		'lang_pointsforqu' => 'Taškai uz klausima',
		'lang_bestanswer' => 'geriausias?',
		'lang_answer' => 'Atsakymas',
		'lang_answers' => 'Atsakymai',
		'lang_existsalready' => 'Klausimas jau egzistuoja. Prašome klausti originaliame klausime.',
		'lang_yourquestions' => 'Jūsų klausimai',
		'lang_search' => 'paieška',
		'lang_mailorusername' => 'Naudotojo vardas arba el. pašto adresas',
		'lang_password' => 'Slaptažodis',
		'lang_rememberme' => 'Likti prisijungus',
		'lang_login' => 'prisijungti',
		'lang_qufastanswer' => 'Jūsų klausimas bus greit atsakytas.',
		'lang_followlatest' => 'Sekit naujausi veikla',
		'lang_commentanswer' => 'Komentuokit atsakymą, jeigu norite <b>pasitikslinti</b>',
		'lang_qudelete' => 'Šis klausimas bus ištrintas.',
		'lang_writecomment' => 'Pasitikslinimą rašyk visada į komentarui skirtą langelį.',
		'lang_whatis' => 'Kvanto.lt yra ekspertų bendruomenė padedanti jums.',
		'lang_registerquickly' => 'Prisijunkite prie mūsų, tai truks tik minutėlę',
		'lang_register' => 'Registruotis',
		'lang_forgot_link' => 'Pamiršau slaptažodį',
		'whatis' => 'Kas yra',

	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
