<?php

/*
	Plugin Name: q2apro Booking System
	Plugin URI: http://www.q2apro.com/plugins/bookingsystem
*/

	return array(

		// default
		'enable_plugin' => 'Plugin aktivieren',
		'minimum_level' => 'Auf Seite zugreifen:',
		'plugin_disabled' => 'Dieses Plugin wurde deaktiviert.',
		'access_forbidden' => 'Zugriff nicht erlaubt.',
		'plugin_page_url' => 'Seite im Forum öffnen:',
		'contact' => 'Bei Fragen bitte ^1q2apro.com^2 besuchen.',

		// time formats
		'datetime_format' => 'DD.MM.YYYY hh:mm', // humans
		'datetime_format_js' => 'd.m.y h:s',
		'datetime_format_php' => 'd.m.Y H:i',
		'datetime_format_php_fullhour' => 'd.m.Y H:00',
		'date_format' => 'DD.MM.YYYY', // humans
		'date_format_php' => 'd.m.Y', // http://php.net/manual/de/function.date.php
		'date_format_momentjs' => 'DD.MM.YYYY', // http://momentjs.com/docs/#/displaying/format/
		'date_format_calendarweek' => 'YYYY MM', // fullcalendar title on booking page

		// plugin general
		'meta_description' => 'Bestellen Sie schnell und bequem den Service, den Sie brauchen. Wann und wo Sie wollen!',
		'contractor' => 'Anbieter',
		'client' => 'Kunde',
		'member' => 'Mitglied',
		'user' => 'Benutzer',
		'nav_main_contractor' => 'Service finden', // main menu on top
		'book_service_btn' => 'Service buchen',
		'admin_maillist' => 'E-Mail-Listing',
		'optional' => 'optional',
		'additional' => 'zusätzlich',
		'fee' => 'Honorar',
		'feepay' => 'Auszahlung Honorar',
		'btn_submit' => 'Absenden',
		'btn_create' => 'Anlegen',
		'order' => 'Auftrag',
		'protocol' => 'Protokoll',
		'event' => 'Termin', // Event
		'eventid' => 'Termin Nr.', // Event-ID
		'date' => 'Datum',
		'time' => 'Uhrzeit',
		'timeabbr' => 'Uhr', // e.g. 10:00 Uhr
		'hourabbr' => 'Std', // e.g. h
		'min' => 'min', // minutes abbreviation
		'timespan' => 'Zeitspanne',
		'price' => 'Preis',
		'sum' => 'Summe',
		'anonymous' => 'anonym',
		'length' => 'Länge',
		'start' => 'Start',
		'end' => 'Ende',
		'eventdetails' => 'Auftragdetails',
		'attachments' => 'Anlagen',
		'bookingnr' => 'Buchung Nr.',
		'bookingtotal' => 'Gesamtpreis der Buchung',
		'ev_former' => 'Vorher',
		'ev_new' => 'Neu',
		'ev_until' => 'bis',
		'reason' => 'Grund',
		'eventproposal' => 'Terminvorschlag',
		'file' => 'Datei',
		'absent' => 'abwesend',
		'reserved' => 'reserviert',
		'already_reserved' => 'bereits reserviert',
		'booked' => 'gebucht',
		'completed' => 'fertig',
		'event_completed' => 'abgeschlossen',
		'paid' => 'bezahlt',
		'confirmed' => 'angenommen',
		'save_btn' => 'Speichern',
		'saveall_btn' => 'Alles speichern',
		'from' => 'von', // e.g. paid from
		'address' => 'Anschrift',
		'location' => 'Ort',
		'portfolio' => 'Portfolio',
		'birthdate' => 'Geburtsdatum',
		'deposit' => 'Guthaben', // a fixed amount can be bought by client, and he can use this deposit money to book contractors
		'balance' => 'Saldo',
		'accountbalance' => 'Kontostand',
		'balance_plus' => 'Guthaben',
		'balance_minus' => 'Rückstand',
		'clearance' => 'Kontoausgleich', // to balance the account to zero
		'paymentin' => 'Eingang', // Zahlungseingang
		'paymentout' => 'Ausgang', // Zahlungsausgang
		'appt' => 'Termin',
		'appts' => 'Termine',
		'myappts' => 'Meine Termine',
		'appt_from' => 'Termin vom',
		'sendmsg_btn' => 'Nachricht senden',
		'message' => 'Nachricht',
		'messages' => 'Nachrichten',
		'per' => 'je', // price per hour
		'status' => 'Status',
		'name' => 'Name',
		'payamount' => 'Zahlbetrag',
		'password' => 'Passwort',
		'forum' => 'Wissensforum',
		'forum_short' => 'Forum',
		'notallowed' => 'Nicht erlaubt',
		'error' => 'Fehler',
		'only' => 'nur', // price
		'notspecified' => 'keine Angabe',
		'myaccount' => 'Mein Konto',
		'created' => 'Erstellt',
		'or' => 'oder',
		'value' => 'Wert',
		'accepted' => 'angenommen',
		'title' => 'Titel',

		// week
		'monday' => 'Montag',
		'tuesday' => 'Dienstag',
		'wednesday' => 'Mittwoch',
		'thursday' => 'Donnerstag',
		'friday' => 'Freitag',
		'saturday' => 'Samstag',
		'sunday' => 'Sonntag',
		'mon' => 'Mo',
		'tue' => 'Di',
		'wed' => 'Mi',
		'thu' => 'Do',
		'fri' => 'Fr',
		'sat' => 'Sa',
		'sun' => 'So',

		// qa-plugin.php
		'no_bookings' => 'Keine Buchungen gefunden.',
		'prefered_times' => 'Bevorzugte Zeiten',
		'prefered_times_none' => 'Keine Zeiten eingetragen',
		'appts_with' => 'Termine mit',
		'appt_paid' => 'bezahlt',
		'hello' => 'Hallo',
		'thxpaid' => 'Vielen Dank für Ihre Zahlung',
		'mail_thxpaid' => 'vielen Dank für Ihre Zahlung.',
		'mail_willcontact' => 'muss den Termin noch bestätigen. Er wird sich mit Ihnen in Verbindung setzen.', // person ...
		'mail_askdetails' => 'Haben Sie schon Ihre Auftragdetails eingetragen?',
		'mail_btndetails' => 'Auftragdetails eintragen',
		'mail_yourappts' => 'Ihre Termine sind:',
		'mail_canmessage' => 'Sie können Ihrem Anbieter jederzeit direkt ^1eine Nachricht^2 senden.',
		'mail_greetings' => 'Freundliche Grüße',
		'mail_greeter' => 'Kyga Team',
		'notmentioned' => 'nicht angegeben',
		'confirm_appts' => 'Termine bestätigen',
		'directmessage' => 'direkte Nachricht',
		'telephone' => 'Telefon',
		'telephone_abbr' => 'Tel.',
		'mailtocon_custopaid' => 'der Kunde ~~~ hat die gebuchten Termine bezahlt.', // leave ~~~, this will be replaced by the client name
		'mailtocon_doconfirm' => 'Bitte bestätigen Sie die Termine in Ihrer ^1Terminübersicht^2.',
		'mailtocon_contactcusto' => 'Bitte melden Sie sich beim Kunden. Kontakt: ',
		'mailtocon_bookdetails' => 'Die Termine zur Buchung Nr. ~~~ sind:', // leave ~~~, this will be replaced by the booking id
		'eventsavailable' => 'Neue Termine verfügbar', // email subject
		'mail_neweventsav' => 'es gibt neue Termine, für die noch kein Anbieter gefunden wurde. Sie können sie hier ablehnen oder übernehmen:',
		'mail_gotoevents' => 'Termine aufrufen',
		'mail_eventaccepted_subject' => 'Termin von ~~~ angenommen', // email subject, leave ~~~, this will be replaced by the contractorname
		'mail_eventaccepted' => 'Ihr Termin wurde von ~~~ akzeptiert und findet statt.', // leave ~~~, this will be replaced by the contractorname
		'mail_seeyourschedule' => 'Hier können Sie Ihre Terminübersicht aufrufen',
		'mail_eventrejected_subject' => 'Termin von ~~~ abgelehnt', // email subject, leave ~~~, this will be replaced by the contractorname
		'mail_eventrejected' => 'leider kann ~~~ Ihre Termine nicht wahrnehmen.', // leave ~~~, this will be replaced by the contractorname
		'mail_rejectreason' => 'Grund: „~~~“', // leave ~~~, this will be replaced
		'mail_othersinformed' => 'Alle anderen Anbieter wurden informiert, den Termin zu übernehmen. Ein Anbieter wird sich bei Ihnen in Kürze zur Terminübernahme melden.',
		'mail_newtime_subject' => 'Neue Zeiten für Ihre Termine',
		'mail_newtime' => 'für Ihre Termine sind neue Zeiten vorgeschlagen worden. Bitte nehmen Sie einen passenden Termin an:',
		'mail_clearancesuccess' => 'Kontoausgleich erfolgreich', // in case of negative balance the client pays
		'mail_clearanceintro' => 'Vielen Dank für Ihre Zahlung in Höhe von ~~~, damit ist Ihr Konto ausgeglichen.', // leave ~~~
		'mail_depositsuccess_subject' => 'Guthaben gutgeschrieben',
		'mail_depositsuccess' => 'Ihre Zahlung ist bei uns eingegangen, vielen Dank. Ein Guthaben in Höhe von ~~~ wurde Ihnen gutgeschrieben.',
		'mail_bookcontractors' => 'Sie können das Guthaben nun verwenden, um ^1Anbieter^2 Ihrer Wahl zu buchen.',

		// events
		'evname_openevent' => 'Kunde initiiert Bestellung',
		'evname_openevent2' => 'offen', // Bestellung
		'evname_reserved' => 'Kunde reserviert Termin',
		'evname_reserved2' => 'Termin reserviert',
		'evname_paid' => 'Kunde hat bezahlt',
		'evname_changed' => 'Terminzeit geändert',
		'evname_setdetails' => 'Kunde legt Auftragdetails fest',
		'evname_setdetails2' => 'Auftragdetails festgelegt',
		'evname_consetdetails' => 'Anbieter legt Auftragdetails fest',
		'evname_consetdetails2' => 'Auftragdetails festgelegt',
		'evname_findtime' => 'Terminzeit wird verhandelt',
		'evname_findtime2' => 'Terminzeit in Verhandlung',
		'evname_accepted' => 'Termin wurde vereinbart und findet statt',
		'evname_accepted2' => 'Termin findet statt',
		'evname_rejected' => 'Anbieter lehnt Termin ab',
		'evname_rejected2' => 'Termin abgelehnt',
		'evname_conneeded' => 'Für Termin wird Anbieter gesucht',
		'evname_conneeded2' => 'Anbieter wird gesucht',
		'evname_completed' => 'Anbieter schließt Termin ab',
		'evname_completed2' => 'Termin abgeschlossen',
		'evname_rated' => 'Kunde bewertet Termin',
		'evname_rated2' => 'Termin bewertet',
		'evname_available' => 'Contractor available',
		'view_appt' => 'Termin anschauen',

		// ratings
		'rating' => 'Bewertung',
		'ratings' => 'Bewertungen',
		'ratingtext' => 'Bewertungstext',
		'noratings' => 'Noch keine Bewertungen.',
		'comment' => 'Kommentar',

		// layer
		'profile' => 'Profil',
		'calendar' => 'Kalender',
		'yourcalendar' => 'Ihr Kalender',
		'menubtn_con_week' => 'Wochenzeiten',
		'menubtn_con_balance' => 'Honorar',
		'menubtn_con_info' => 'Info',
		'menubtn_cli_ratings' => 'Bewerten',
		'menubtn_cli_balance' => 'Kontoübersicht',
		'menubtn_cli_profile' => 'Profil',
		'menubtn_balance' => 'Honorare',
		'menubtn_con_offers' => 'Angebote',
		'payments' => 'Zahlungen',
		'contractors' => 'Anbieter',
		'clients' => 'Kunden',
		'menubtn_messages' => '✉',
		'topright_next_appt' => 'Nächster Termin',
		'topright_no_appt' => 'kein Termin',
		'topright_msg' => 'Nachrichten',
		'admin' => 'Admin',
		'upcomingappts' => 'Anstehende Termine',
		'earningbookings' => 'Einnahmen aus Buchungen der letzten 30 Tage',
		'recentrequests' => 'Ihre aktuellen Service-Anfragen',

		// page general
		'page_deactive' => 'Diese Seite ist derzeit deaktiviert.',
		'page_noaccess' => 'Keine Zugriffsberechtigung.',
		'fee_balance' => 'Saldo',

		// page adminbalance
		'adminbal_title' => 'Admin: Honorare',
		'income' => 'Einnahmen',
		'fee_payout' => 'Auszahlung Honorar',
		'fee_lastmonth' => 'letzter Monat',
		'fee_sum' => 'SUMME',
		'forcontractor' => 'für Anbieter',

		// page admincalendar
		'admincal_title' => 'Admin: Alle Termine',
		'admincal_perhaps' => 'eventuell',
		'admincal_unpaid' => 'unbezahlt',
		'admincal_from' => 'von',
		'admincal_by' => 'bei', // person
		'btnupdate_appt' => 'Termine aktualisieren',
		'admincal_nochanges' => 'Keine Änderungen vorgenommen.',
		'updatesuccess' => 'Termin erfolgreich aktualisiert.',
		'reloadpage' => 'Lade Seite neu.',
		'cal_warnonleave' => 'Termine wurden geändert, aber noch nicht gespeichert. Wirklich Seite verlassen?',

		// page adminclients + admincontractors
		'admincli_title' => 'Admin: Kunden',
		'admincon_title' => 'Admin: Anbieter',
		'admin_tab_userdata' => 'Benutzerdaten',
		'admin_tab_birthdate' => 'Geburtstag',
		'admin_tab_address' => 'Adresse',
		'admin_tab_price' => 'Preis',
		'admin_tab_absent' => 'Abwesenheit (z. B. Urlaub)',
		'paymethod' => 'Zahlmethode',
		'admin_tab_spec' => 'Spezialisierung',
		'admin_tab_portfolio' => 'Portfolio',
		'email' => 'E-Mail',
		'admin_sendmsg' => 'Nachricht schreiben',
		'forum_profile' => 'Forenprofil',
		'pointstatistic' => 'Punktestatistik',
		'forumstatistic' => 'Forenstatistik',
		'forumactivity' => 'Forenaktivität',
		'bookingsite' => 'Buchungsseite',
		'nolocationset' => 'Kein Ort angegeben.',
		'admin_open_gmaps' => 'In Google Maps öffnen.',
		'approve' => 'genehmigen',
		'approved' => 'genehmigt',
		'doapprove' => 'genehmigen',
		'dounlock' => 'freischalten',
		'removeapprove' => 'Genehmigung entfernen',
		'disapprove' => 'ablehnen',
		'disapproved' => 'abgelehnt',
		'removedisapprove' => 'Sperrung aufheben',
		'bookingvolume' => 'Buchungsvolumen',

		// page admineventedit
		'admineved_title' => 'Admin: Event editieren',
		'admineved_missingid' => 'Event-ID bitte angeben.',
		'admineved_success' => 'Event Update erfolgreich.',
		'admineved_back' => 'Zurück zur Terminliste.',

		// page adminmessages
		'adminmsg_title' => 'Admin: Alle Nachrichten',
		'adminmsg_from' => 'Von',
		'adminmsg_to' => 'An',
		'delete' => 'löschen',
		'nomessages' => 'Noch keine Nachrichten vorhanden.',
		'adminmsg_confirmdel' => 'Wirklich löschen?',
		'message_deleted' => 'Nachricht gelöscht.',

		// page adminpayments
		'adminpaym_title' => 'Admin: Zahlungen',
		'adminpaym_paymethod' => 'Zahlmethode',
		'adminpaym_bank' => 'Bank',
		'adminpaym_paypal' => 'Paypal',
		'adminpaym_creditnote' => 'Gutschrift',
		'adminpaym_elimination' => 'Ausbuchung',
		'adminpaym_paid' => 'Gezahlt',
		'adminpaym_timestamp' => 'Zeitpunkt',
		'adminpaym_paybookid' => 'Buchung Nr. (bei gezahltem Termin)',
		'adminpaym_payid' => 'Zahl-ID',
		'adminpaym_deposit' => 'Guthaben',
		'adminpaym_validate' => 'bestätigen',
		'adminpaym_delete' => 'löschen',
		'adminpaym_unpaid' => 'unbezahlt',
		'adminpaym_created' => 'Zahlung angelegt',

		// page adminratings
		'adminrat_title' => 'Admin: Bewertungen',
		'rat_negativ' => 'negativ',
		'rat_neutral' => 'neutral',
		'rat_good' => 'gut',
		'rat_verygood' => 'sehr gut',
		'rat_excellent' => 'ausgezeichnet',
		'adminrat_tab_client' => 'Kunde',
		'adminrat_tab_contractor' => 'Anbieter',

		// page adminschedule
		'adminsched_title' => 'Admin: Termine',
		'apptcount' => 'Termine, die nicht älter als 30 Tage sind',
		'adminsched_id' => 'ID',
		'adminsched_price' => 'Preis',
		'adminsched_contractor' => 'Anbieter',
		'adminsched_client' => 'Kunde',
		'adminsched_needs' => 'Auftragdetails',
		'adminsched_state' => 'Status',
		'adminsched_paidpaypal' => 'bezahlt per Paypal',
		'adminsched_paidbank' => 'bezahlt per Bank',
		'adminsched_paiddeposit' => 'bezahlt via Guthaben',
		'hintincomplete1' => 'Auftragdetails ergänzen und Hinweis zum Abschluss eintragen',
		'hintincomplete2' => 'Auftragdetails ergänzen',
		'hintincomplete3' => 'Hinweis zum Abschluss eintragen',
		'apptdetails' => 'Auftragdetails angeben',
		'adminsched_placeholder' => 'Hinweis zum Abschluss angeben',
		'adminsched_bookedon' => 'gebucht am',
		'adminsched_unit' => 'je Einheit',
		'adminsched_confirmdelete' => 'Event wirklich löschen',

		// page booking
		'bookservice' => 'Zeit buchen',
		'onlyregistered' => 'Nur als angemeldetes Mitglied können Sie diese Seite nutzen.',
		'noservice' => 'Es wurde kein Service gewählt.',
		'con_notavailable' => 'Dieser Anbieter ist derzeit nicht verfügbar.',
		'notavailable' => 'nicht verfügbar',
		'needregisterlogin' => 'Bitte ^1loggen Sie sich ein^2 oder ^3registrieren Sie sich^4.',
		'needreglogin_service' => 'Bitte ^1loggen Sie sich ein^2 oder ^3registrieren Sie sich^4, um den Service zu buchen.',
		'notpaid_click' => 'Noch nicht bezahlter Termin bei ~~~ - Klick zur Zahlung',
		'yourapptwith' => 'Ihr Termin bei',
		'openprofile' => 'Profil aufrufen',
		'preferedtimes' => 'Wählen Sie eine Zeit aus, indem Sie auf einen Bereich im Kalendar klicken. Wenn ^1farbige Bereiche^2 eingetragen sind, können Sie nur diese Bereich wählen. Graue Zeiten sind bereits vergeben oder nicht verfügbar.',
		'preferedtimes_short' => 'Wählen Sie eine Zeit aus, indem Sie mit der Maus einen Bereich im Kalender ziehen.',
		'howtimesbymouse' => 'Wie man Zeiten auswählt',
		'specify_fullname' => 'Bitte geben Sie Ihren vollständigen Namen an',
		'firstlastname' => 'Vor- und Nachname',
		'specify_address' => 'Bitte geben Sie Ihre Anschrift an.',
		'placeholder_addressexample' => 'z. B. Musterstraße 12, D-80335 München',
		'specify_birthdate' => 'Bitte geben Sie Ihr Geburtsdatum an.',
		'specify_birthdate_page' => 'Zuletzt benötigen wir noch Ihr Geburtsdatum',
		'placeholder_dateexample' => 'z. B. 15.09.1981',
		'pleasepay' => 'Bitte Kontostand ausgleichen.',
		'yourbalance' => 'Ihr Kontostand',
		'acceptterms' => 'Ich akzeptiere die ^1AGB und das Widerrufsrecht^2.',
		'askforterms' => 'Bitte akzeptieren Sie die AGB.',
		'btn_bookandpay' => 'Service jetzt buchen',
		'earliesttomorrow' => 'Der Termin kann frühestens morgen stattfinden. Jeder Anbieter braucht Vorbereitungszeit.',
		'notpast' => 'Der Termin kann nicht in der Vergangenheit liegen.',
		'onlyfixedtimes' => 'Der Termin muss in einem blauen Bereich liegen.',
		'depositafterbooking' => 'Ihr Guthaben danach',
		'depositempty' => 'Ihr Guthaben ist mit dieser Buchung aufgebraucht. Der Restbetrag von \'+newbalancestr+\' ist noch auszugleichen.',
		'choosecaltime' => 'Bitte einen Zeitraum im Kalender wählen.',
		'specify_email' => 'Bitte geben Sie Ihre E-Mail an.',
		'specify_validemail' => 'Bitte eine gültige E-Mail angeben.',
		'specify_password' => 'Bitte geben Sie ein Passwort an.',
		'contractor_notexist' => 'Dieser Anbieter existiert nicht.',
		'user_notexist' => 'Dieser Benutzer existiert nicht.',
		'calendarhelp' => 'Hilfe zum Kalender?',
		'distance' => 'Distanz',
		'time' => 'Zeit',
		'timebycar' => 'Fahrzeit mit dem Auto',
		'showmap' => 'Karte zeigen',
		'hidemap' => 'Karte verstecken',
		'start' => 'Start',
		'target' => 'Ziel',
		'updatebtn' => 'Aktualisieren',
		'specialoffers' => 'Angebote',
		'offer_validuntil' => 'Angebot gültig bis',
		'executiontime' => 'Ausführungszeit',
		'bookofferfor' => 'Angebot buchen für',
		'choosedaytime' => 'Bitte wählen Sie Tag und Uhrzeit:',
		'chooseday' => 'Bitte wählen Sie den Tag:',
		'approx' => 'ca.',
		'btn_bookoffer' => 'Angebot buchen und weiter zum Bezahlen',
		'intotal' => 'gesamt',
		'incl_taxes' => 'inkl. aller Steuern',
		'shortlink_profile' => 'Kurzlink zu diesem Profil',
		'order_imp' => 'Bestellen Sie',
		'order_for' => 'Buchen für', // price follows
		'vcardlink' => 'Download vCard',
		'createlogin' => 'Login anlegen',
		'nopriceset' => 'Kein Stundenpreis angegeben',

		// page clientbalance - obsolete
		'clibal_title' => 'Ausgleich des Rückstands',
		'clibal_title_overview' => 'Kontoübersicht',
		'paywith' => 'Zahlung per',
		'paywithpaypal' => 'Zahlung per Paypal',
		'paywithbank' => 'Zahlung per Bank',
		'btn_paynow' => 'Jetzt bezahlen',
		'upcoming_appts' => 'Kommende Termine',
		'event_paid' => 'Termin bezahlt',
		'no_balanceminus' => 'Keinen Kontorückstand festgestellt.',
		'or_getdeposit' => '^1Guthaben^2 stattdessen erwerben?',
		'pleasepaynext' => 'Überweisen Sie bitte als nächstes',
		'payto' => 'an',
		'payreceiver' => 'Empfänger',
		'afterclearbal' => 'Nach Eingang der Zahlung wird Ihr Kontoausgleich bestätigt. Sie erhalten eine E-Mail von uns.',
		'paypurpose' => 'Verwendungszweck',
		'pay_clearance' => 'Kontoausgleich für',
		'pay_id' => 'Zahlung Nr.',
		'connect_paypal' => 'Verbinde zu PayPal …',
		'pleasewait' => 'Bitte warten …',
		'paypal_js' => 'Ihr Browser verwendet kein Javascript, bitte klicken Sie den folgenden Button, um die Transaktion fortzusetzen.',

		// page clientcalendar + contractorcalendar
		'clical_title' => 'Kalender',
		'notpaid_pay' => 'noch nicht bezahlt - Klick zur Zahlung',
		'notpaidyet' => 'noch nicht bezahlt',
		'listclients' => 'Aktuelle Anbieter kontaktieren',
		'embed' => 'Einbinden',
		'embedcalendar' => 'Ihren Kalender können Sie in Google Kalender, Outlook, Thunderbird etc. einbinden. Einfach im jeweiligen Programm den folgenden Link als externen Kalender importieren',
		'embedcalendar_2' => 'Schauen Sie hierzu in die Anleitung des jeweiligen Programms.',
		'instructions' => 'Anleitungen',
		'hints' => 'Hinweise',
		'calguide_google' => 'Anleitung für Google Kalender',
		'calguide_outlook' => 'Anleitung für Outlook',
		'calguide_thunderbird' => 'Anleitung für Thunderbird/Lightning',
		'gcal_hint1' => 'Um Ihren Google Calendar freizugeben, müssen Sie zuerst die Einstellung auf "Public" setzen und die Termindetails verstecken.',
		'gcal_hint2' => 'Ihre "Calendar ID" finden Sie weiter unten bei den "Calendar Details" in Google. Diese ID müssen Sie oben eingeben!',
		'gcal_hint3' => 'Achten Sie darauf, dass Ihre Termine im Google Calendar stets den Status "Busy/Beschäftigt" haben. Wenn die Termine den Status "Available/Verfügbar" aufweisen, so werden sie nicht in unserem Kalender angezeigt.',
		'screenshot' => 'Screenshot',
		'embedcal' => 'Kalender einbinden',
		'import' => 'Import',
		'export' => 'Export',
		'google_connect' => 'Mit Google verbinden',
		'google_hint' => 'Sie können Ihren ^1Google Calendar^2 bei uns einbinden. So erkennen Kunden sofort, zu welchen Zeiten Sie nicht verfügbar sind.',
		'google_hint_client' => 'Sie können Ihren ^1Google Calendar^2 bei uns einbinden. So sehen Sie Ihre eigenen Termine beim Buchen in anderen Kalendern und es kommt nicht zu Überschneidungen.',
		'google_nodetails' => 'Die Termine werden nur mit Uhrzeiten angezeigt, es werden öffentlich keine Details freigegeben.',
		'clipboard_copied' => 'Link kopiert. Jetzt können Sie den Link mit der rechten Maustaste einfügen.',
		'googlecal_link' => 'Link zu Ihrem Google Calendar',
		'eventtypes' => 'Termintypen',
		'copylink' => 'Link kopieren',
		'openlink' => 'Link aufrufen',

		// page clientdeposit - obsolete
		'clidep_paytitle' => 'Zahlung des Guthabens',
		'clidep_noorder' => 'Wir konnten keine Bestellung finden.',
		'clidep_title' => 'Guthaben erwerben',
		'clidep_intro' => 'Mit dem Guthaben können Sie jeden Anbieter sofort buchen und haben eine bessere Kostenkontrolle.',
		'recent_balance' => 'Ihr aktueller ^1Kontostand^2 beläuft sich auf:',
		'set_deposit' => 'Guthaben festlegen',
		'set_slider' => 'Wählen Sie Ihr Guthaben mit dem Schieber',
		'paymethodchoice' => 'Gewünschte Zahlweise',
		'banktransfer' => 'Banküberweisung',
		'bankhint' => 'Sie überweisen den Zahlbetrag per Bank. Eingang nach 1 bis 2 Tagen.',
		'paypalhint' => 'Nach erfolgter Zahlung wird das Guthaben sofort auf Ihrem Account verbucht.',
		'depositback' => 'Sie können Ihr Guthaben jederzeit zurück erhalten. Hierzu reicht eine Mail an uns.',
		'depositset' => 'Sie haben ein Guthaben in Höhe von ~~~ festgelegt.', // leave ~~~
		'paydeposit' => 'Guthaben bezahlen',
		'clidep_mail_subject' => 'Bestellung eines Guthabens',
		'clidep_mail_body1' => 'Sie haben ein Guthaben in Höhe von ~~~ gebucht.',
		'clidep_mail_body2' => 'Bitte zahlen Sie noch den Betrag von ~~~, erst danach ist das Guthaben gültig.',
		'paymentalways' => 'Die Zahlung können Sie jederzeit ^1hier vornehmen^2.',
		'pay_deposit_for' => 'Guthaben für',
		'aftercleardeposit' => 'Nach Eingang der Zahlung wird Ihr Guthaben bestätigt. Sie erhalten eine E-Mail von uns.',

		// page userprofile
		'cliprof_title' => '',
		'startcredit_activated' => 'Startguthaben aktiviert für', // admin info mail
		'user_registered' => 'Neues Mitglied registriert',
		'registered' => 'registriert',
		'contracted' => 'unter Vertrag',
		'can_photoupload' => 'Hier können Sie ein ^1persönliches Foto^2 hochladen.',
		'reward_profile' => 'Füllen Sie Ihr Profil aus und für Ihre erste Buchung erhalten Sie ein Guthaben von',
		'placeholder_phone' => 'für Kontakt und Rückfragen',
		'skypename' => 'Skypename',
		'change_pwmail' => 'E-Mail oder Passwort ändern',
		'data_updated' => 'Daten aktualisiert',
		'startcredit_granted' => 'Ihr Startguthaben wurde gutgeschrieben.',
		'next_book_contractor' => 'Buchen Sie als nächstes einen ^1Anbieter^2.',
		'data_incompleted' => 'Daten sind unvollständig, konnte nicht speichern.',
		'offershint' => 'Nach der Registrierung können Sie Ihre einzelnen Angebote mit Preisen erstellen.',
		'getbookingbutton' => 'Buchungsbutton für Ihre Webseite',

		// page clientratings
		'clirat_title' => 'Bewertung der Anbieter',
		'clirat_mail' => 'Ihr Termin wurde bewertet',
		'clirat_content' => '~name~ hat Sie am ~date~ bewertet:', // leave ~name~ and ~date~
		'see_ratings' => 'Schauen Sie all Ihre Bewertungen hier an',
		'clirat_contactus' => 'Sie können uns jederzeit kontaktieren, wenn Sie mit einem Anbieter nicht zufrieden sind',
		'clirat_dorate' => 'Bitte bewerten Sie jeden Termin, den Sie bei einem Anbieter hatten. Seien Sie ehrlich und kritisch, denn nur so kann sich der Anbieter weiter verbessern.',
		'clirat_prevratings' => 'Bisherige Bewertungen',
		'clirat_placeholder_rat' => 'kurze Bewertung eingeben …',
		'noapptyet' => 'Sie haben noch keinen Termin bei einem Anbieter gehabt.',
		'ratingsaved' => 'Bewertung wurde gespeichert, vielen Dank.',

		// page clientschedule
		'clisched_title' => 'Termine',
		'specify_needs' => 'Legen Sie hier bitte rechtzeitig die Auftragdetails für Ihre Termine fest, so kann sich der Anbieter optimal vorbereiten.',
		'singleappt' => 'Einzeltermin',
		'onlysingleappt' => 'Ihnen wird nur ein bestimmter Termin angezeigt. Hier können Sie ^1all Ihre Termine^2 aufrufen.',
		'noappts' => 'Derzeit keine Termine.',
		'noeventsfound' => 'Keinen entsprechenden Termin gefunden.',
		'uploadfile' => 'Datei hochladen',
		'uploadfile_another' => 'Weitere Datei hochladen',
		'uploadsuccess' => 'Erfolgreich hochgeladen',
		'pay_tooltip' => 'Termin ist noch nicht bezahlt. Hier klicken zum Bezahlen.',
		'pay_appt' => 'Termin bezahlen',
		'savesuccess' => 'Erfolgreich gespeichert',
		'filesizewarning' => 'Maximale Dateigröße 8 MB. Bitte Datei verkleinern oder zippen.',
		'completed_button' => 'Terminabschluss bestätigen',
		'completed_tooltip' => 'Termin wurde abgeschlossen und ist bezahlt.',

		// page contractorbalance
		'conbal_title' => 'Honorar',
		'con_noapptyet' => 'Sie haben noch keine Termine.',
		'apptcompleted_hint' => 'Ein Termin gilt als abgeschlossen, wenn der Kunde dies bestätigt hat.',
		'conbal_recent' => 'Aktuell',
		'conbal_onlyadmin' => 'Nur für Admin',
		'conbal_turnover' => 'Umsatz',
		'conbal_fees' => 'Honorare',
		'conbal_earnings' => 'Gewinn',

		// page contractorcalendar
		'concal_title' => 'Kalender',
		'change_appt' => 'Termine ändern',
		'change_appt_hint1' => 'Sie können jeden offenen Termin verschieben und in seiner Dauer verändern (Anfasser in Wochenansicht ziehen). Beachten Sie, dass der Kunde die Differenz nachzahlen muss oder als Guthaben erhält.',
		'change_appt_hint2' => 'Wichtig',
		'change_appt_hint3' => 'Jede Terminänderung ist mit einer ^1Nachricht^2 an den Kunde zu dokumentieren.',
		'contact_clients' => 'Kunden kontaktieren',
		'booktimespan' => 'Diesen Zeitraum buchen',
		'nochanges' => 'Keine Änderungen vorgenommen.',
		'reloadingpage' => 'Lade Seite neu.',

		// page contractorinfo
		// please edit booker-page-contractorinfo.php directly
		// this information is flexible depeding on the FAQ and requirements of the project

		// page contractorlist
		'conli_title' => 'Service buchen',
		'voucher_until' => 'Gültig bis',
		'voucher_detail' => 'Für Ihre erste Buchung erhalten Sie ~~~ Guthaben.',
		'registerforbooking' => 'Um einen Anbieter buchen zu können, müssen Sie sich ^1kurz registrieren^2.',
		'registerclient' => 'Als Kunde registrieren',
		'moneybackguarantee' => 'Geld-Zurück-Garantie',
		'moneybackdetail' => 'Sollten Sie mit dem gebuchten Service nicht zufrieden sein, erhalten Sie Ihr Geld zurück. Ohne irgendein „Wenn und Aber“.', // not implemented
		'positiveratings' => 'Positive Bewertungen',
		'bookfor' => 'Buchen für', // price
		'customerratings' => 'Aktuelle Kundenbewertungen',
		'recommendcontractor' => 'Anbieter vorschlagen',
		'bestprice' => 'Bester Preis',
		'guaranteed' => 'garantiert',
		'bestpriceguarantee' => 'Bestpreisgarantie',
		'weguarantee' => 'Wir garantieren Ihnen den bestmöglichen Preis für den gewählten Service bei diesem Anbieter. Sollten Sie das Angebot im Internet preiswerter finden, passen wir Ihren Preis sofort an.',
		'moneywithhold' => 'Ihr Geld ist sicher',
		'withholdguarantee' => 'Der Anbieter erhält sein Geld erst, wenn Sie den Auftrag als erledigt melden. Bis dahin halten wir Ihr Geld sicher zurück.', // not implemented
		'clickmoreservices' => 'Klick hier, um nach weiteren Dienstleistern dieser Art zu suchen.',

		// page userprofile
		'nav_login' => 'Login',
		'conpro_title' => 'Anbieterprofil',
		'yourprofile' => 'Ihr Profil',
		'douploadphoto' => 'Ein Foto von Ihnen fehlt noch.', // Bitte ein persönliches Foto hochladen.
		'facerequired' => 'Ihr Gesicht muss erkennbar sein.',
		'forcustomertrust' => 'Wichtig für Kundenvertrauen.',
		'accountstatus' => 'Kontostatus',
		'verified' => 'genehmigt',
		'we_verify' => 'Nach Ihrer Registrierung verifizieren wir Ihren Account und schalten ihn innerhalb von 24 Stunden frei.',
		'available' => 'Verfügbar',
		'absent_placeholder' => 'z. B. 01.05.2016, 05.06.2016 - 10.06.2016',
		'absent_tooltip' => 'Einzelne Tage mit dd.mm.yyyy eingeben. Mehrere Zeiten mit Komma trennen. Einen Zeitraum mit dd.mm.yyyy - dd.mm.yyyy eintragen.',
		'weekdays_head' => 'Nicht-verfügbare Wochentage',
		'public_data' => 'Öffentliche Daten',
		'internal_data' => 'Interne Daten',
		'basic_data' => 'Basisdaten',
		'contractor_data' => 'Anbieterdaten',
		'contractor_data_qu' => 'Bieten Sie einen Service an?',
		'yourservice_short' => 'Ihr Service',
		'placeholder_service' => 'z. B. Rechtsanwalt für Mietrecht',
		'yourservice_desc' => 'Beschreibung / Portfolio',
		'yourservice_hint' => 'Beschreiben Sie Ihren Service, der veröffentlicht werden soll. ^1Nur Premium:^2 Fügen Sie Fotos und Videos hinzu sowie persönliche Kontaktdaten.',
		'upload_img' => 'Bild hochladen',
		'insert_img' => 'Bild einfügen',
		'textlength_warn' => 'Achtung, Sie haben 8000 Zeichen überschritten.',
		'placeholder_paypal' => 'für alle Zahlungen',
		'placeholder_address' => 'für Vertrag und Abrechnungen',
		'paypal_iban' => 'Paypal oder IBAN',
		'skype' => 'Skype',
		'set_price' => 'Bitte Preis eingeben.',
		'your_price' => 'Ihr Preis',
		'hour' => 'Stunde',
		'hours' => 'Stunden',
		'per_hour' => 'je Stunde',
		'filesizewarning_exact' => 'Ihre Datei ist mit \'+img_size+\' Mb zu groß. Erlaubt sind maximal \'+maximg_size+\' Mb.',
		'payout' => 'Auszahlung',
		'newcontractor' => 'Neuer Anbieter',
		'newcon_mailsubject' => 'Neuer Anbieter registriert',
		'changeavatar' => 'Anderes Profilbild hochladen',
		'removeavatar' => 'Profilbild entfernen',
		'removeavatar_confirm' => 'Profilbild wirklich entfernen?',
		'commission' => 'Kommission',
		'finish_registration_btn' => 'Registrierung abschließen',
		'company' => 'Firma',

		// page contractorratings
		'conrat_title' => 'Kundenbewertungen',
		'conrat_tellclients' => 'Weisen Sie Ihre Kunden nach jedem Termin darauf hin, dass sie Sie bewerten können. Hier finden Sie Ihre bisherigen Bewertungen.',
		'clientmail_auto' => 'Der Kunde erhält automatisch eine E-Mail.',
		'conrat_notpaidyet' => 'Noch nicht bezahlt, der Termin findet ggf. nicht statt.',
		'manage_event_btn' => 'Terminzeit verwalten',
		'add_details' => 'Falls Auftragdetails nicht eingetragen sind, bitte ergänzen.',

		// page contractorschedule
		'consched_title' => 'Termine',
		'protocol_note' => 'Dies ist die Abschlussnotiz des Anbieters',
		'mail_concompleted' => 'hat Ihren Termin als abgeschlossen gemeldet.', // person ...
		'please_rate' => 'Bitte bewerten Sie den Service.',
		'torating' => 'zur Bewertung',
		'bookingfrom' => 'Buchung vom',
		'confirmcomplete_btn' => 'Termin abschließen',
		'apptinpast' => 'Termin liegt in Vergangenheit',
		'customerconfirmneeded' => 'Abschlussbestätigung des Kunden steht noch aus',

		// page contractorweek
		'conweek_title' => 'Meine Zeiten',
		'setup_times' => 'Zeiten einrichten',
		'block_times' => 'Zeiten blocken',
		'week_hint0' => 'Wenn Kunden Ihren Service nur zu festen Zeiten buchen sollen, dann legen Sie die Zeiten hier fest.',
		'week_hint1' => 'Dies kann zu weniger Kunden führen, da keine flexiblen Zeiten mehr buchbar sind.',
		'week_hint2' => 'Wir empfehlen, auf feste Zeiten zu verzichten. Sie können jede eingehende Buchung in der Zeit verändern und mit dem Kunden abstimmen.',
		'week_hint3' => 'Die Zeiten lassen sich jederzeit wieder ändern.',
		'week_hint4' => '- Auswahl mit Klick und Ziehen der Maus.',
		'week_hint5' => '- Ein Klick auf die gewählte Zeit entfernt diese wieder.',
		'week_updatesuccess' => 'Wochenzeiten erfolgreich aktualisiert.',
		'week_warnonleave' => 'Wochenzeiten wurden noch nicht gespeichert. Wirklich Seite verlassen?',
		'preview' => 'Vorschau',
		'saveweek_btn' => 'Wochenzeiten speichern',
		'favoritetimes' => 'Feste Zeiten',

		// page eventhistory
		'evhis_title' => 'Termin-History',
		'put_eventid' => 'Bitte Terminnummer angeben.',
		'eventhistoryfor' => 'History für Termin Nr. ~eventid~',
		'recent_eventdata' => 'Aktuelle Termindaten',
		'intotal' => 'gesamt',

		// page ipn
		'payment_success' => 'Zahlung erfolgreich',
		'payment_success_message' => 'Vielen Dank für Ihre Zahlung. Sie sind nun Premium-Mitglied und können nun alle Vorteile nutzen. Viel Erfolg!', // Thanks for your payment. You are now Premium member at Kvanto.lt and can enjoy all advantages!
		'payment_fail_title' => 'Zahlung nicht erfolgt',
		'payment_fail' => 'Leider wurde die Zahlung abgebrochen oder es kam zu einem anderen Problem.',
		'mail_paid1' => 'Ihre Zahlung ist bei uns eingegangen und der Anbieter steht für Sie bereit. Er wird sich in Kürze bei Ihnen melden.',
		'mail_paid2' => 'Tragen Sie bitte als nächstes Ihre Auftragdetails hier ein',
		'clearance_success' => 'Ihre Zahlung ist bei uns eingegangen und Ihr Konto ist nun ausgeglichen. Vielen Dank.',
		'deposit_success' => 'Ihre Zahlung ist bei uns eingegangen und Ihr Guthaben wurde aktiviert. Vielen Dank.',
		'trypaymentagain' => 'Sie können die Zahlung noch einmal versuchen, ^1einfach hier klicken^2.',

		// page mbcontact
		'contact_intro' => 'Schreiben Sie uns hier eine Nachricht. Wir werden uns so schnell wie möglich bei Ihnen melden.',
		'yourmessage' => 'Ihre Nachricht',
		'yourname' => 'Ihr Name',
		'youremail' => 'Ihre E-Mail',
		'contactto' => 'Kontakt zu',

		// page mbmessages
		'msg_title' => 'Private Nachrichten',
		'msgfrom' => 'Nachricht von',
		'msganswer' => 'Auf diese Nachricht antworten',
		'msglist' => 'Liste aller Nachrichten',
		'msgselferror' => 'Moment, Sie sollten sich selbst keine Nachricht senden.',
		'msgerror1' => 'Sie können noch keine Nachricht senden.',
		'msgerror2' => 'Dieses Mitglied kann keine Nachrichten empfangen.',
		'nameunknown' => 'Name nicht bekannt',
		'msgto' => 'Nachricht an',
		'yourmsgto' => 'Ihre Nachricht an',
		'msgtocontractor' => 'Ihre Nachricht wird dem Anbieter per E-Mail zugestellt.',
		'msgtoclient' => 'Ihre Nachricht wird dem Kunden per E-Mail zugestellt.',
		'msgtooperator' => 'Ihre Nachricht wird uns per E-Mail zugestellt.',
		'emailsecret' => 'Dabei bleibt Ihre E-Mail geheim. ',
		'copysaved' => 'Eine Kopie wird von uns gespeichert.',
		'msg_to_us' => 'uns',
		'prevmessages' => 'Bisherige Nachrichten',
		'msgcontent' => 'Inhalt',
		'sent' => 'Gesendet',
		'received' => 'Empfangen',
		'insertmsg' => 'Nachricht eingeben …',
		'msgsent' => 'Ihre Nachricht wurde versendet.',

		// page mbupload
		'filetype_disallowed' => 'Dateityp nicht erlaubt',
		'filename_exists' => 'Dateiname existiert bereits',
		'nouploadfolder' => 'Upload-Verzeichnis existiert nicht.',

		// page pay
		'pay_title' => 'Zahlung',
		'deducting' => 'abzüglich', // minus deposit (positive balance)
		'so_only' => 'also nur', // payment minus x, so only ...
		'reservation_from' => 'Reservierung von',
		'youwerebooked' => 'Sie wurden von ~name~ wie folgt gebucht (Buchung Nr. ~bookid~)', // leave ~name~ and ~bookid~
		'paidbydeposit' => 'Der Termin wurde mittels Guthaben bezahlt und findet statt.',
		'contactclient' => 'Bitte nehmen Sie Kontakt zum Kunden auf',
		'appts_probexist' => 'Ggf. hat der Kunde die Auftragdetails bereits angegeben, bitte schauen Sie in Ihre ^1Terminliste^2.',
		'confirmtime' => 'Bitte bestätigen Sie diesen Termin in Ihrer Terminliste',
		'waitforpay' => 'Wir müssen als nächstes noch den Eingang der Zahlung abwarten.',
		'appts_reserved' => 'Termine bei ~~~ reserviert',
		'appts_booked' => 'Termine bei ~~~ gebucht', // confirmed
		'bookconfirmed_deposit' => 'Der Betrag wurde über Ihr Guthaben ausgeglichen. Die Buchung gilt als bestätigt.',
		'cansendmsg' => 'Bei Bedarf können Sie dem Anbieter eine ^1Nachricht senden^2.',
		'pleasepayamount' => 'Bitte zahlen Sie noch den Betrag von ~~~, erst danach gilt die Buchung als bestätigt.', // leave ~~~
		'bookedby' => 'Sie haben einen Service bei ~name~ gebucht.', // leave ~name~
		'booking_bookid' => 'Buchung Nr. ~bookid~.', // leave ~bookid~
		'booking_success' => 'Buchung erfolgreich',
		'booking_thanks' => 'Vielen Dank für Ihre Buchung.',
		'appts_activated' => '^1Ihre Termine^2 wurden soeben freigeschaltet.',
		'confirmwassent' => 'Sie haben eine Bestätigungsmail erhalten.',
		'con_willcontact' => 'Der Anbieter ~~~ wird sich in Kürze bei Ihnen melden.',
		'put_details' => 'Tragen Sie als nächstes die Auftragdetails ein:',
		'con_contactbefore' => 'Falls Sie möchten, können Sie den Anbieter bereits vorab kontaktieren',
		'goodluck' => 'Viel Erfolg!',
		'confirmpaymail' => 'Nach Eingang der Zahlung wird Ihr Termin per E-Mail bestätigt.',
		'servicefor' => 'Service für ~client~ bei ~contractor~', // leave ~~
		'paybooking' => 'Buchung bezahlen',
		'confirmbooking' => 'Buchung bestätigen',
		'nobookingchosen' => 'Es wurde keine Buchung gewählt.',
		'nobookingfound' => 'Es wurde keine Buchung hierzu gefunden.',
		'chosentimes' => 'Gewählte Zeiten',
		'chosenoffer' => 'Gewähltes Angebot',
		'remainingdeposit' => 'Restguthaben',
		'bookcontractor' => 'Anbieter buchen',
		'bookamount' => 'Buchungsbetrag',
		'paywithinday' => 'Sie müssen die Zahlung innerhalb von 24 Stunden vornehmen, ansonsten wird die Buchung storniert.',
		'bankpayhint' => 'Sie überweisen den Zahlbetrag per Bank. Erst wenn die Zahlung eingeht, wird Ihr Termin bestätigt.',
		'paypalpayhint' => 'Ihr Termin wird sofort bestätigt. Die gewählte Zeit wird für Sie reserviert.',
		'paymillpayhint' => 'Ihr Termin wird sofort bestätigt. Die gewählte Zeit wird für Sie reserviert.',
		'btn_booknow' => 'Jetzt buchen',
		'verification' => 'Verifikation',
		'paymentwithprovider' => 'Bitte zahlen Sie den gebuchten Service erst, wenn er ausgeführt wurde. Die Zahlung geht direkt an den Dienstleister, niemals an uns.',
		'providergetscontact' => 'Als nächstes wird der Dienstleister Ihre Kontaktdaten erhalten, die gewählte Zeit bestätigen und Sie kontaktieren.',
		'verification_hint1' => 'Um Buchungen auf unserer Plattform zu verifizieren, bitten wir jeden Benutzer seine Kreditkarte oder seinen Bankverbindung einmalig einzugeben.',
		'verification_hint2' => 'Nur zur Verifizierung. Es wird <b>nichts berechnet</b>.',
		'verification_placeholder' => 'z. B. 4567 8912 4556 1234 2547',
		'verification_error' => 'Fehler: Kreditkarte nicht korrekt',
		'verification_success' => 'Verifizierung erfolgreich',
		'verification_done' => 'Danke für Ihre Verifizierung',

		// contratorlist search
		'search_results' => 'Suchergebnisse',
		'found' => 'gefunden',
		'search_label' => 'Servicesuche',
		'searchlocation_label' => 'Ort einschränken',
		'all_locations' => 'Alle Orte',
		'search_placeholder' => 'Suche Service, Beruf oder Name', // Suche nach Service oder Namen …
		'search_clear' => 'Suche leeren',
		'nothing_found' => 'Konnte zu dieser Eingabe nichts finden.',
		'newest_contractors' => 'Neueste Anbieter',
		'random_contractors' => 'Zufällige Anbieter',
		'alphabetic_contractors' => 'Liste aller Anbieter (alphabetisch)',
		'showall_contractors_btn' => 'Alle Anbieter anzeigen',
		'all_contractors' => 'Alle Anbieter',

		// page forumprofile
		'answer' => 'Antwort',
		'answers' => 'Antworten',
		'question' => 'Frage',
		'questions' => 'Fragen',
		'comment' => 'Kommentar',
		'comments' => 'Kommentare',
		'bestanswers' => 'Beste Antworten', // Geriausi atsakymai
		'votesreceived' => 'Upvotes', // Gavo balsų
		'bestanswer_iconhover' => 'Auszeichnungen für beste Antworten',
		'thumbsup_iconhover' => 'Erhaltene Votes',
		'newestanswers' => 'Aktuelle Antworten',
		'noansweryet' => 'Noch keine Antworten.',
		'all_answers' => 'Alle Antworten',
		'reputation' => 'Reputation',
		'points' => 'Punkte',
		'weekhistory' => '7-Tage-History',
		'aboutme' => 'Über mich',
		'aboutus' => 'Über uns',
		'service' => 'Service',
		'inforum' => 'Im Forum',
		'secret' => 'geheim',
		'private_data' => 'private Daten',
		'nonpublic' => 'Nicht öffentlich',
		'needfulldata' => 'Wenn Sie sich als Anbieter registrieren, müssen alle Ihre Angaben vollständig sein.', // Ihre Adresse wird den Kunden öffentlich angezeigt.
		'fullnamehint' => 'Ein vollständiger Name schafft Vertrauen.',
		'nocompanyname' => 'Kein Fantasiename, kein Firmenname, ihr echter Name!',
		'addresshint' => 'Straße und Ort in einer Zeile mit Komma getrennt.',
		'execution' => 'Ausführung', // execution of the service
		'servicelocal' => 'bei mir vor Ort',
		'serviceonline' => 'Service online',
		'serviceatcustomer' => 'beim Kunden',
		'onlineonly' => 'Service nur online',
		'onlinetoo' => 'Service auch online',
		'perkm' => 'je km', // price per km
		'kmratehint' => 'Beispiel: 10 km sind dann', // example: 10 km are ...
		'eg' => 'z. B.', // abbreviation: for example
		'profilecreated' => 'Profil erfolgreich angelegt',
		'changemailpw' => 'E-Mail oder Passwort ändern',
		'specify_service' => 'Bitte geben Sie Ihren Service an.',
		'specify_portfolio' => 'Bitte Portfolio bzw. Beschreibung Ihres Service eingeben.',
		'hourprice_hint' => 'Freilassen, falls keine stundenweise Buchung gewünscht.',

		// page contract
		'contract_title' => 'Vertrag zwischen Anbieter und Vermittler',
		'contract_hint' => 'Dies ist der letzte Schritt zur Registrierung als Anbieter. Lesen Sie bitte die Bedingungen und willigen in den Vertrag ein.',
		'conclude_contract' => 'Vertrag abschließen',
		'registersuccess' => 'Registrierung erfolgreich',
		'newcontract_subject' => 'Neuer Anbietervertrag',
		'newcontract' => 'Ein neuer Anbieter hat sich für den Anbietervertrag registriert.',
		'contract_line_1' => 'Zwischen dem Vermittler',
		'contract_line_2' => 'und Ihnen als Anbieter',
		'contract_line_3' => 'wird vereinbart',
		'contract_line_4' => 'Der Anbieter erklärt sich mit den ^1Allgemeinen Geschäftsbedingungen für Anbieter^2 einverstanden. Diese sind wesentlicher Bestandteil der Vereinbarung.',
		'contract_line_5' => 'Der Kommissionssatz beläuft sich auf',
		'contract_line_6' => 'Die Vereinbarung hat erst nach Zustimmung durch den Vermittler Gültigkeit.',
		'contract_line_7' => 'Bitte bestätigen Sie abschließend',
		'contract_line_8' => 'Ich garantiere, dass alle gemachten Angaben wahrheitsgemäß sind und dass ich die notwendigen Genehmigungen besitze, um meine Dienstleistung auszuführen und anzubieten.',
		'contract_line_9' => 'Ich habe die ^1Allgemeinen Geschäftsbedingungen für Anbieter^2 gelesen und bin damit einverstanden.',
		'contract_line_10' => 'Ich verstehe, dass bei Buchungen von Dienstleistungen durch Kunden nur ein Vertrag zwischen Anbieter und Kunde zustande kommt. Der Betreiber dieser Plattform ist nur Vermittler.',
		'contract_line_11' => 'Mit Klick auf den Button schließen Sie rechtsgültig einen Vertrag mit uns:',
		'contract_line_12' => 'Bitte setzen Sie die Haken bei allen Checkboxen.',
		'contract_line_13' => 'Herzlichen Dank für Ihre Registrierung als Anbieter.',
		'contract_line_14' => 'Wir werden Ihre Daten in den nächsten 24 Stunden überprüfen und freischalten.',
		'contract_line_15' => 'Sollte es zu Unstimmigkeiten kommen, melden wir uns bei Ihnen.',

		// dropdown main menu
		'contractorslist' => 'Liste aller Anbieter',
		'forcontractors' => 'Für Anbieter',
		'forclients' => 'Für Kunden',
		'toptopics' => 'Top-Themen',

		// extra
		'motto' => 'Kyga - Einer für alle, alle für einen',

		// page eventmanager
		'evman_title' => 'Event Manager',
		'events_available_title' => 'Verfügbare Termine',
		'events_allocated' => 'Es scheint so, als ob alle verfügbaren Termine bereits vergeben sind.',
		'events_available' => 'Nachstehende Termine sind noch nicht an Anbieter vergeben. Sie können die Termine übernehmen.',
		'events_coordinate' => 'Abzustimmende Termine',
		'events_allocated_client' => 'Es scheint so, als ob alle Termine bereits geklärt sind.',
		'events_findtime' => 'Nachstehende Termine sind noch zeitlich abzustimmen:',
		'event_accepted_title' => 'Termin angenommen',
		'event_accepted' => 'Sie haben den Termin Nr. ~eventid~ angenommen. Vielen Dank!',
		'backtoeventlist' => 'weiter zur Terminliste',
		'event_hint_title' => 'Hinweis zum Termin',
		'event_hint' => 'Der Termin Nr. ~eventid~ wurde bereits von ^1~name~^2 angenommen.',
		'event_backdetails' => 'zurück zu den Termindetails',
		'event_rejectreason' => 'Grund für Ablehnung des Termins',
		'rejectplaceholder' => 'Grund nennen …',
		'reject_btn' => 'Ablehnen',
		'event_rejected_title' => 'Termin abgelehnt',
		'event_rejected' => 'Sie haben den Termin Nr. ~eventid~ abgelehnt. Ein anderer Anbieter wird den Termin übernehmen.',
		'already_rejected' => 'Der Termin Nr. ~eventid~ wurde bereits von Ihnen abgelehnt.',
		'newtimeproposed_title' => 'Neue Zeit für Termin vorschlagen',
		'proposenewtime' => 'Schlagen Sie eine neue Zeit für den Termin Nr. ~eventid~ vor.',
		'eventduration' => 'Dauer des Termins: ~eventduration~ min',
		'starttime' => 'Startzeit',
		'addmoreproposals' => 'Weitere Terminauswahl hinzufügen?',
		'propose_btn' => 'Vorschlagen',
		'event_proposed_title' => 'Vorschlag neuer Terminzeiten',
		'event_proposed' => 'Sie haben für den Termin Nr. ~eventid~ neue Zeiten vorgeschlagen. Der Kunde wird darüber informiert und einen Termin auswählen.',
		'event_iscompleted' => 'Der Termin Nr. ~eventid~ wurde bereits abgeschlossen.',
		'event_notpaidyet' => 'Der Termin Nr. ~eventid~ wurde noch nicht bezahlt.',
		'event_alreadyaccepted' => 'Der Termin Nr. ~eventid~ wurde bereits angenommen.',
		'event_notexist' => 'Termin existiert nicht.',
		'contractor_firstbooked' => 'Zuerst gebuchter Anbieter', // contractor who rejected the event
		'eventtime' => 'Terminzeit',
		'reject_event_btn' => 'Termin ablehnen',
		'propose_event_btn' => 'Andere Zeit vorschlagen',
		'accept_event_btn' => 'Termin annehmen',
		'eventproposals' => 'Vorschläge für neue Terminzeit',
		'clickconfirm' => 'Ein Klick auf die Zeit bestätigt diese',

		// dropdown extras
		'pointsystem' => 'Punktesystem',
		'monthbest' => 'Monatsbeste',
		'newsletter' => 'Newsletter',
		'yourquestions' => 'Ihre Fragen',
		'youranswers' => 'Ihre Antworten',
		'youractivity' => 'Ihre Aktivitäten',

		// mini user statistic in top menu
		'points' => 'Punkte',
		'bestanswers' => 'Beste Antworten',
		'votesreceived' => 'Votes erhalten',

		// page userrecommend
		'recommend_hint' => 'Hier können Sie einen Service-Anbieter vorschlagen, der noch nicht bei uns registriert ist. Wir verifizieren Ihre Eingaben und informieren den Anbieter danach per E-Mail.',
		'placeholder_email_con' => 'E-Mail des Anbieters',
		'newcon_suggested' => 'Neuer Anbieter vorgeschlagen',
		'back_services' => 'Zurück zur Serviceseite',
		'specify_fullname_con' => 'Bitte geben Sie den Namen des Anbieters an.',
		'specify_email_con' => 'Bitte geben Sie die E-Mail des Anbieters an.',
		'specify_service_con' => 'Bitte geben Sie den Service des Anbieters an.',
		'specify_address_con' => 'Bitte geben Sie die Adresse des Anbieters an.',
		'userrecommended' => 'Neuer Anbieter vorgeschlagen, vielen Dank.',

		// page offercreate
		'offer_pagetitle' => 'Angebot erstellen',
		'offer_edit' => 'Angebot bearbeiten',
		'offer_hint' => 'Hier können Sie ein Angebot einstellen, das unabhängig von den Terminbuchungen existiert. Ein Fotograf kann bspw. ein Hochzeitsshooting für 1800 € anbieten, statt sich stundenweise buchen zu lassen.',
		'offer_hint_2' => 'Sie können bis zu fünf Angebote anlegen. Alle Angebote werden den Kunden auf Ihrer ^1Buchungsseite^2 angezeigt.',
		'offertitle' => 'Angebotstitel',
		'offertitle_placeholder' => 'z. B. Hochzeitsfotos inkl. Fotobearbeitung',
		'offerprice' => 'Preis des Angebots',
		'offerprice_placeholder' => 'z. B. 1800',
		'specify_price' => 'Bitte geben Sie einen Preis an.',
		'duration' => 'Dauer',
		'duration_placeholder' => 'z. B. 5',
		'specify_duration' => 'Bitte ungefähre Dauer angeben.',
		'offerend' => 'Angebot gültig bis',
		'offerend_hint' => 'Freilassen, wenn dauerhaft.',
		'offerduration_hint' => 'Freilassen, wenn nicht bestimmbar.',
		'description' => 'Beschreibung',
		'youroffer_hint' => 'Beschreiben Sie Ihr Angebot ausführlich und fügen Sie Fotos oder Videos hinzu. Die Buchung wird direkt über Ihre Buchungsseite möglich sein.',
		'new_offer' => 'Neues Angebot',
		'newcon_offer' => 'Neues Angebot erstellt', // new offer created
		'flags' => 'Flags',
		'back_profile' => 'Zurück zum Profil',
		'back_offers' => 'Zurück zu Ihren Angeboten',
		'another_offer' => 'Weiteres Angebot',
		'offer' => 'Angebot',
		'offers' => 'Angebote',
		'offer_activated' => 'Angebot aktiviert.',
		'offer_deactivated' => 'Angebot deaktiviert.',
		'offer_created' => 'Angebot erstellt.',
		'offer_created_thx' => 'Angebot erstellt, vielen Dank.',
		'offer_edited' => 'Angebot aktualisiert.',
		'offer_deleted' => 'Angebot gelöscht.',
		'offer_approved' => 'Angebot genehmigt.',
		'offer_disapproved' => 'Angebot abgelehnt.',
		'offer_tobechecked' => 'Dieses Angebot wird gerade geprüft und demnächst veröffentlicht.',
		'offer_gotdisapproved' => 'Dieses Angebot entsprach nicht den Richtlinien.',
		'offer_gotdeleted' => 'Dieses Angebot wurde gelöscht.',
		'offer_gotdeactivated' => 'Dieses Angebot wurde deaktiviert.',
		'offer_expired' => 'Dieses Angebot ist bereits abgelaufen.',
		'premium_paid' => 'Premium bezahlt.',
		'premium_activated' => 'Premium aktiviert.',
		'options' => 'Optionen',
		'edit' => 'bearbeiten',
		'deactivate' => 'deaktivieren',
		'deactivated' => 'deaktiviert',
		'activate' => 'aktivieren',
		'activated' => 'aktiviert',
		'remove' => 'entfernen',
		'deleted' => 'gelöscht',
		'needcontractor' => 'Sie müssen ^1Anbieter werden^2, um Angebote einstellen zu können.',

		// page contractoroffers
		'conoff_title' => 'Ihre Angebote',
		'nooffers' => 'Noch keine Angebote eingestellt.',
		'table_created' => 'Erstellt',
		'conoff_intro' => 'Hier sehen Sie alle Ihre Angebote in der Übersicht. Sie können ein neues Angebot erstellen oder bestehende Angebote bearbeiten.',
		'offer_create_btn' => 'Neues Angebot erstellen',

		// page clientrequests
		'clirequ_title' => 'Ihre Service-Anfragen',
		'norequests' => 'Noch keine Service-Anfragen vorhanden.',
		'clirequ_intro' => 'Hier sehen Sie Ihre Serviceanfragen inklusive eingegangener Angebote. Sie können auch eine neue Anfrage erstellen.',
		'request_create_btn' => 'Service-Anfrage erstellen',
		'newrequest_create_btn' => 'Neue Anfrage erstellen',
		'ownrequest_create_btn' => 'Eigene Anfrage erstellen',
		'request' => 'Anfrage', // Gesuch
		'requests' => 'Anfragen',
		'bestprice' => 'Bester Preis',
		'priceoffers' => 'Preisangebote',
		'removerequest_confirm' => 'Wollen Sie diese Anfrage wirklich entfernen?',
		'choosebid' => 'Angebot auswählen',
		'nobidsyet' => 'noch keine Preisangebote',
		'disabled' => 'deaktiviert',
		'notapprovedyet' => 'noch nicht genehmigt',
		'ischecked' => 'wird geprüft',
		'share' => 'Share',
		'sharefacebook' => 'Auf Facebook teilen',
		'adminrequ_title' => 'Admin: Serviceanfragen',

		// page requestlist
		'all_requests' => 'Alle Service-Anfragen',
		'my_requests' => 'Meine Anfragen',
		'reli_search_label' => 'Service-Anfrage finden',
		'reli_search_placeholder' => 'z. B. Handarbeit', // Berlin
		'endsin' => 'endet in', // days, hours ...

		// page offerlist
		'all_offers' => 'Alle Angebote',
		'my_offers' => 'Meine Angebote',
		'offli_search_label' => 'Angebotsuche',
		'offli_search_placeholder' => 'z. B. Reparatur',
		'ownoffer_create_btn' => 'Eigenes Angebot erstellen',

		// page requestcreate
		'request_pagetitle' => 'Service-Anfrage erstellen',
		'request_create' => 'Anfrage aufgeben',
		'request_open' => 'Anfrage aufrufen',
		'request_edit' => 'Anfrage bearbeiten',
		'request_savebtn' => 'Anfrage speichern',
		'request_hint_1' => 'Hier können Sie eine öffentliche Serice-Anfrage erstellen. Die Anbieter werden Ihnen einen Preis für die benötigte Leistung vorschlagen. Sie können dann das beste Angebot auswählen.',
		'request_hint_2' => 'Alle Serice-Anfragen erscheinen zentral auf der Seite ^1Service-Anfragen^2.',
		'request_hint_3' => 'Nachdem Sie einen der Anbieter für Ihren Auftrag ausgewählt haben, müssen Sie den vereinbarten Preis begleichen.', //  Auch hier gilt: Der Anbieter erhält sein Geld erst, wenn Sie den Auftrag als erledigt melden. Bis dahin halten wir Ihr Geld sicher zurück.
		'requesttitle' => 'Ich benötige',
		'requesttitle_placeholder' => 'z. B. Einbau einer Dusche',
		'requestprice' => 'Mein Budget',
		'requestprice_placeholder' => 'z. B. 250',
		'specify_price' => 'Bitte geben Sie einen Preis an.',
		'duration_placeholder' => 'z. B. 5',
		'specify_duration' => 'Bitte ungefähre Dauer angeben.',
		'requestend' => 'Anfrage online bis',
		'requestend_hint' => 'Laufzeit maximal 2 Wochen.',
		'requestduration_hint' => 'Freilassen, wenn nicht bestimmbar.',
		'yourrequest_hint' => 'Beschreiben Sie Ihre Anfrage ausführlich und fügen Sie Fotos oder Youtube-Video hinzu.',
		'new_request' => 'Neue Service-Anfrage',
		'newcon_request' => 'Anfrage erstellt', // new request created
		'back_requests' => 'Zurück zu Ihren Anfragen',
		'another_request' => 'Weitere Anfrage erstellen',
		'request_created' => 'Anfrage erstellt.',
		'request_activated' => 'Anfrage aktiviert.',
		'request_deactivated' => 'Anfrage deaktiviert.',
		'request_gotcreated' => 'Anfrage erstellt, vielen Dank.',
		'request_edited' => 'Service-Anfrage aktualisiert.',
		'request_deleted' => 'Service-Anfrage gelöscht.',
		'request_approved' => 'Service-Anfrage genehmigt.',
		'request_disapproved' => 'Service-Anfrage abgelehnt.',
		'specify_requesttitle' => 'Bitte geben Sie einen Titel für die Service-Anfrage an.',
		'specify_date' => 'Bitte geben Sie ein Enddatum an.',
		'specify_description' => 'Bitte geben Sie eine Beschreibung an.',
		'format' => 'Format',
		'specify_realname' => 'Bitte geben Sie zuerst ^1Ihren Namen^2 an.',
		'specify_realname_request' => 'Um Service-Anfragen erstellen zu können, geben Sie bitte zuerst ^1Ihren Namen^2 an.',
		'mail_btncheck_request' => 'Angaben prüfen + Anfrage freischalten',
		'mail_btncheck_offer' => 'Angaben prüfen + Angebot veröffentlichen',

		// page adminoffers
		'adminoffers_title' => 'Admin: Angebote',
		'offerid' => 'Angebot Nr.',
		'nr' => 'Nr.', // number

		// page adminsearchtrack
		'adminsearch_title' => 'Admin: Suchtracking',
		'searchtrack' => 'Suchtracking',
		'searchterm' => 'Suchbegriff',
		'ipaddress' => 'IP-Adresse',
		'menubtn_admin_searchtrack' => '🔍',
		'nodata' => 'keine Daten',

		// page bid
		'bid_pagetitle' => 'Gesucht', // Angebot abgeben
		'request_notexist' => 'Diese Service-Anfrage existiert nicht.',
		'request_expired' => 'Diese Service-Anfrage ist bereits abgelaufen.',
		'alreadybid' => 'Sie haben hierfür bereits ein Preisangebot am ~date~ abgegeben.',
		'service_required' => 'Folgende Leistung wird benötigt',
		'bid_ends' => 'Service-Anfrage endet am',
		'yourpricebid' => 'Ihr Preisangebot',
		'yourprice' => 'Ihr Preis',
		'yourprice_placeholder' => 'z. B. 200',
		'yourcomment' => 'Ihr Hinweis',
		'bid_pricehint' => 'Bitte beachten Sie, dass Ihr Preisangebot rechtlich bindend ist. Das heißt, Sie müssen die beschriebene Leistung zu dem abgegebenen Preis vollständig erbringen.',
		'postoffer_btn' => 'Angebot abgeben',
		'postsuccess' => 'Angebot erfolgreich abgegeben',
		'request_tobechecked' => 'Diese Service-Anfrage wird gerade geprüft und demnächst veröffentlicht.',
		'request_gotdisapproved' => 'Diese Service-Anfrage entsprach nicht den Richtlinien.',
		'request_gotdeleted' => 'Diese Service-Anfrage wurde gelöscht.',

		// page bookingbutton
		'bookbtn_title' => 'Buchungsbutton für Ihre Webseite',
		'bookbtn_intro' => 'Fügen Sie jetzt einen Buchungsbutton auf Ihrer Webseite ein. So geben Sie Ihren Besuchern die Möglichkeit, Sie sofort zu buchen!',
		'bookme_example' => 'Beispiel eines Kontaktformulars mit Buchungsbutton',
		'bookmenow_btn' => 'Buch mich jetzt',
		'bookbtn_label' => 'Beschriftung des Buttons',
		'buttonstyle' => 'Button-Stil',
		'simplelink' => 'Einfacher Link',
		'menu_bookingbutton' => 'Button',

		// paymill
		'paymill_title' => 'Zahlung via Paymill',
		'paymill_error' => 'Es ist ein unerwarteter Fehler aufgetreten.',
		'contactus' => 'Bitte kontaktieren Sie uns',
		'missing_data' => 'Daten fehlen',

		// userforumprofile
		'recommendation' => 'Empfehlung',
		'recommendations' => 'Empfehlungen',
		'recommendedby' => 'Diese Personen empfehlen ~username~',
		'personrecommendedby' => 'Diese Person wird empfohlen von',
		'irecommend' => 'Ich empfehle ~username~',
		'unrecommend' => 'Empfehlung zurückziehen?',
		'recommends' => '~username~ empfiehlt',

		// adminlogview
		'adviewlog_title' => 'Event Logs',
		'mail_sent' => 'E-Mail versendet',
		'msg_sent' => 'Nachricht versendet',
		'msg_deleted' => 'Nachricht gelöscht',
		'eventname' => 'Eventname',
		'logdata' => 'Logdaten',
		'profile_edited' => 'Profil bearbeitet',
		'avatar_removed' => 'Profilbild entfernt',
		'avatar_uploaded' => 'Profilbild hochgeladen',
		'bid_posted' => 'Preisangebot gepostet',
		'payment_deleted' => 'Zahlung gelöscht',
		'contractor_weekupdated' => 'Wochenzeiten aktualisiert',
		'profile_created' => 'Profil angelegt',
		'client_depositorder' => 'Kunde bestellt Guthaben',
		'contractor_paid' => 'Anbieter wurde bezahlt',
		'contractor_contracted' => 'Anbieter akzeptiert Vertrag',
		'deposit_release' => 'Guthaben freigegeben',
		'event_deleted' => 'Termin gelöscht',
		'client_clearance' => 'Kontoausgleich ausgelöst',
		'contractor_recommended' => 'Vorschlag eines Anbieters',
		'client_creditnote' => 'Startguthaben aktiviert', // voucher

		// page businesscard
		'bcard_title' => 'Ihre persönliche Visitenkarte',
		'bcard_intro' => 'Wenn Sie Premium-Mitglied sind, erhalten Sie von uns Ihre persönlichen Visitenkarten zugesendet. Als Standard-Mitglied können Sie Visitenkarten separat bestellen.',
		'bcard_preview' => 'Vorschau',
		'bcard_design' => 'Design',
		'website' => 'Webseite',
		'bookme' => 'Buchen Sie mich',

		// page premium ***
		'premium_title' => 'Premium-Pläne für Service-Anbieter',
		'premium_intro' => 'Als Premium- oder VIP-Mitglied genießen Sie viele wertvolle Vorteile. Die Tabelle zeigt Ihnen alle Details:',
		'youarecurrently' => 'Sie sind aktuell',
		'member_basic' => 'Basic Mitglied',
		'member_premium' => 'Premium Mitglied',
		'member_vip' => 'VIP Mitglied',
		'yourownpage' => '^1Ihre eigene Seite^2 mit Basisinformationen und persönlichem Photo',
		'servicedesc_page' => 'Service-Beschreibung auf Ihrer Seite',
		'servicedesc_limited' => '(beschränkt: nur Text, keine Links, keine Bilder)',
		'servicedesc_unlimited' => '(unbeschränkt: Text, Links, Bilder, Videos)',
		'createoffer_basic' => 'Erstellen Sie ^11 Angebot^2 für mehr Verkäufe und Werbung',
		'createoffer_premium' => 'Erstellen Sie ^15 Angebote^2 für mehr Verkäufe und Werbung',
		'createoffer_vip' => 'Erstellen Sie bis zu ^1100 Angebot^2 für mehr Verkäufe und Werbung',
		'bookcal_basic' => 'Ihr eigener ^1Buchungskalender^2 mit ^3Zeiteinstellungen^4 und ^5ICS-Export^6',
		'eventmanagement' => 'Terminverwaltung: Buchungszeiten ändern, akzeptieren, ablehnen',
		'bookbtn_external' => '^1Buchungsbutton^2 für Ihre externe Webseite und Ihre Facebook-Seite',
		'gopremium' => 'Premium wählen',
		'premium' => 'Premium',
		'govip' => 'VIP wählen',
		'commission_bookings' => 'Kommission auf Buchungen',
		'commission_details' => 'für 6 Monate, danach 25 %',
		'monthly_price' => 'Monatlicher Preis', // translated as Value by purpose (psychology)
		'free' => 'kostenfrei', // price
		'become' => 'Werden Sie', // werden Sie Premium Mitglied
		'subdomain_desc' => 'Subdomain für Ihre Seite, zum Beispiel "marius.kvanto.lt"',
		'gcal_integration' => '^1Google Calendar^2 Integration in Ihren Buchungskalender',
		'payment_integration' => 'Zahlungsintegration: Erhalten Sie Zahlungen des Kunden direkt nach der Buchung (PaySera-Integration)',
		'sendprivatemessages' => 'Senden Sie ^1private Nachrichten^2 an alle kvanto-Mitglieder',
		'vcardcontact' => 'Mitglieder können Ihre Kontaktdaten mit einem Klick ins Smartphone oder den Computer importieren.',
		'adfree' => 'Komplett werbefrei',
		'forever' => 'für immer',
		'eurospermonth' => '€/Monat',
		'become_contractor' => 'Anbieter werden',
		'become_premium' => 'Premium-Mitglied werden',
		'become_premiummember' => 'Jetzt Premium Mitglied werden',
		'become_vipmember' => 'Jetzt VIP Mitglied werden',
		'getbusinesscards_desc' => 'Sie erhalten ^1100 wunderschöne Visitenkarten^2 nach Ihrer VIP-Mitgliedschaft',
		'moneyback_desc' => 'Wir geben immer eine Geld-Zurück-Garantie von 30 Tagen, sollten Sie Ihre Meinung ändern.',
		'member_payment_hint' => 'Die erste Monatszahlung wird durch Sie ausgeführt. Zukünftige Zahlungen werden von Ihrem Konto eingezogen.',
		'needpremium' => 'Sie müssen Premium-Mitglied sein, um dieses Feature nutzen zu können.',
		'needpremium_links' => 'Der Link wird nicht angezeigt, da der Benutzer nicht Premium-Mitglied ist.',
		'needpremium_email' => 'Die E-Mail wird nicht angezeigt, da der Benutzer nicht Premium-Mitglied ist.',
		'needpremium_phone' => 'Die Telefonnummer wird nicht angezeigt, da der Benutzer nicht Premium-Mitglied ist.',
		'needpremium_offers' => 'Wenn Sie weitere Angebote erstellen möchten, müssen Sie Ihre Mitgliedschaft (Premium) erweitern.',
		'needpremium_messages' => 'Sie können Nachrichten an alle senden, wenn Sie Premium-Mitglied sind.',
		'faq_head' => 'Häufig gestellte Fragen',
		'faq_01_h1' => 'Was passiert nach meiner Zahlung?',
		'faq_01_content' => 'Nach Ihrer Zahlung werden alle Premium-Feature sofort freigeschaltet.',
		'faq_02_h1' => 'Wann kommt meine nächste Abrechnung?',
		'faq_02_content' => 'Ihr Abrechnungszeitraum beginnt am Tag Ihrer ersten Zahlung und die Premium-Mitgliedschaft wird monatlich abgerechnet.',
		'faq_03_h1' => 'Kann ich meine Premium-Mitgliedschaft wieder kündigen?',
		'faq_03_content' => 'Ja, wir berücksichtigen Ihre Wünsche, egal in welcher Situation Sie sich befinden. Ob Ihr Business derzeit wächst oder zurückgefahren werden muss. Sie können Premium-Mitglied jederzeit zum Monatsende bestellen oder abbestellen.',
		'faq_04_h1' => 'Kann ich nur die Premium-Features buchen, die ich brauche?',
		'faq_04_content' => 'Nein, wir bieten keine spezifischen Features zur Buchung an. Als Premium-Mitglied profitieren Sie von allen Vorteilen des Systems.',
		'faq_05_h1' => 'Kann ich einen jährlichen Beitrag bezahlen?',
		'faq_05_content' => 'Nein, dies ist zur Zeit nicht möglich. Wir rechnen auf Monatsbasis ab, um jedem mehr Flexibilität zu geben.',
		'faq_06_h1' => 'Kann ich mein Geld zurückbekommen, falls etwas nicht stimmt?',
		'faq_06_content' => 'Ja, Sie haben 30 Tage nach Buchung Ihrer Premium-Mitgliedschaft Zeit, uns zu informieren, falls Sie nicht zufrieden sind. Selbstverständlich halten Sie auch Ihr Geld zurück.',
		'membership' => 'Mitgliedschaft',
		'youarepremium' => 'Sie sind Prremium-Mitglied.',
		'premiumtrial_promo' => 'Wir schenken Ihnen eine Premium-Mitgliedschaft, wenn Sie bis 31.07.2017 bestellen.',
		'premiumtrial_click' => 'Klicken Sie "Premium buchen" und erhalten Sie 6 Monate kostenfreie Mitgliedschaft.',
		'premiumpayments' => 'Premium-Zahlungen',

		// premiumpay
		'membership_premium' => 'Premium-Mitgliedschaft',
		'price_premium' => 'Preis der Premium-Mitgliedschaft',
		'membership_vip' => 'VIP-Mitgliedschaft',
		'price_vip' => 'Preis der VIP-Mitgliedschaft',
		'vat_included' => 'UST ~vatvalue~ % inklusive', // leave ~vatvalue~, this will be replaced
		'payment' => 'Zahlung',

		// startpage
		'mainsearchlabel' => 'Finden Sie Ihren persönlichen Service',
		'forexample' => 'Zum Beispiel',
		'photograph_link' => 'fotograf', // custom links below search bar
		'photograph_linktext' => 'Hochzeitsfotograf', // name of link
		'dentist_link' => 'zahnarzt',
		'dentist_linktext' => 'Zahnarzt',
		'mechanic_link' => 'mechaniker',
		'mechanic_linktext' => 'Automechaniker',
		'nanny_link' => 'babysitter',
		'nanny_linktext' => 'Babysitter',
		'translator_link' => 'übersetzer',
		'translator_linktext' => 'Übersetzer',
		'trainer_link' => 'trainer',
		'trainer_linktext' => 'persönlicher Trainer',
		'apartmentrepair_link' => 'reparatur',
		'apartmentrepair_linktext' => 'Wohnungsreparatur',
		'designer_link' => 'designer',
		'designer_linktext' => 'Designer',
		'findinstantly_h1' => 'Finden Sie sofort Ihren Dienstleister',
		'findinstantly_text' => 'Browsen Sie durch unsere umfangreiche und ständig wachsende Liste von Service-Anbietern, die Ihnen helfen, Ihre Aufgaben zu erfüllen. Von simplen häuslichen Aufgaben bis zu Experten-Services - Sie erhalten Hilfe auf Kyga. Nutzen Sie einfach die Suche und finden Sie einen Spezialisten. Buchen Sie ihn bzw. sie und lassen Sie Ihr Problem schnell lösen.',
		'findinstantly_button' => 'Dienstleister suchen',
		'timeyouneed_h1' => 'Buchen Sie Ihre Wunschzeit',
		'timeyouneed_text' => 'Sie können selbst bestimmen, wann der Service stattfinden soll. Ob Sie eine Stunde benötigen oder einen ganzen Tag, Sie können die Zeit selbst im Kalender bestimmen. Oder Sie suchen sich einfach eines der Servicepakete aus, die von den Dienstleistern angeboten werden.',
		'timeyouneed_button' => 'Finden Sie einen Service-Anbieter',
		'askquestion_h1' => 'Stellen Sie Fragen und erhalten Sie Antworten von Experten',
		'askquestion_text' => 'Werden Sie Mitglied unserer Community und erhalten Sie Antworten, Tips und Empfehlungen für alles, was sie beschäftigt. Sie können sogar einen Experten direkt im Forum buchen, der Ihnen hilft, Ihre Probleme zu lösen.',
		'askquestion_button' => 'Was möchten Sie wissen?',
		'becomeprovider_h1' => 'Service-Anbieter werden',
		'becomeprovider_text' => 'Es ist einfach, Dienstleister bei uns zu finden. Genausogut können Sie selbst Ihre Dienstleistungen anbieten! So erhöhen Sie mit Kyga Ihre Reichweite, werden von neuen Kunden gefunden und erhöhen Ihre Einnahmen. Kyga wird täglich von mehreren tausend potentieller Kunden besucht, die Ihre Hilfe brauchen.',
		'becomeprovider_button' => 'Als Service-Anbieter registrieren',
		'offerpackages_h1' => 'Servicepakete anbieten',
		'offerpackages_text' => 'Wenn Sie spezielle Dienstleistungen anbieten, die nicht in das stündliche Buchen passen (zum Bespiel ein "Hochzeitspaket" eines Fotografen), können Sie diese als Servicepaket bewerben. Kunden können diese Pakete dann sofort buchen und ein Datum im Kalender wählen. Weitere Beispiele sind: "Abendmakeup", "Wartung der Sanitäranlage", "3 Monate persönlicher Fitnesscoach". Lassen Sie die Welt wissen, was Sie leisten können.',
		'offerpackages_button' => 'Erstellen Sie ein Servicepaket',
		'clientmanagement_h1' => 'Komplettes Kundenmanagement-System',
		'clientmanagement_text' => 'Wenn Sie gebucht werden, können Sie einfach die Buchung in Ihrem Dashboard verwalten und Ihre Zeiten planen. Wir geben Ihnen die Tools, um produktiv zu sein, Ihre Kunden zu ordnen, Ihre Finanzen und Ihren Kalender in einem zentralen Platz zu organisieren. Möchten Sie Ihre Produktivität verbessern? Kyga wird Ihnen die Kopfschmerzen nehmen und Transparenz für Sie und Ihre Kunden bringen.',
		'clientmanagement_button' => 'Dashboard öffnen',
		'getpremium_h1' => 'Premium-Mitglied werden',
		'getpremium_text' => 'Wenn Sie Kyga nutzen möchten, um täglich neue Kunden zu gewinnen, werden Sie von der Premium-Mitgliedschaft profitieren. Sie erhalten mehr Möglichkeiten, sich mit Ihren Kunden in Kontakt zu setzen, keine Werbung auf Ihrer Buchungsseite, Software-Integrationem und als Bonus 100 hochqualitative Visitenkarten, die wir Ihnen als VIP-Mitglied an die Tür liefern.',
		'getpremium_button' => 'Siehe Premium-Pläne',
		'participate_h1' => 'Schaffen Sie sich einen guten Ruf und erweitern Sie Ihr Netzwerk',
		'participate_text' => 'Nehmen Sie bei unserem Expertenforum teil. Durch das Beantworten von Fragen erhalten Sie Reputationspunkte. Zeigen Sie potentiellen Kunden Ihre Fachkenntnis, demonstrieren Sie Ihre Professionalität und Ihr Wissen. Andere Mitglieder haben die Möglichkeit, Sie weiterzuempfehlen mit unseren vorhandenen Sharing-Tools für soziale Netzwerke. Steigern Sie die Anzahl Ihrer Kunden rapide.',
		'participate_button' => 'Schaffen Sie sich einen guten Ruf',
		'getbookingpage' => 'Holen Sie sich Ihre eigene Buchungsseite',
		'signupnow' => 'Jetzt registrieren',
		'ask_service' => 'Service anfragen',

		// IMPORTANT FOR QA-THEME.PHP
		'lang_code' => 'de',
		'headtitle' => 'Kyga - Buchen Sie Ihren persönlichen Service',
		'interviewlabel' => 'Interview',
		'interviewtag' => 'interview',
		'lang_askquestion' => 'Stellen Sie Ihre Frage!',
		'lang_withoutregistration' => 'kostenfrei + ohne Registrierung',
		'lang_qu_alreadyexists' => 'existiert bereits',
		'lang_qu_closed' => 'geschlossen',
		'lang_footer_about' => 'Über uns',
		'lang_footer_terms' => 'AGB',
		'lang_footer_legal' => 'Impressum',
		'lang_footer_contacts' => 'Kontakt',
		'lang_footer_premium' => 'Premium',
		'lang_shortlink' => 'Kurzlink zu dieser Seite',
		'lang_print' => 'Drucken',
		'lang_sharefacebook' => 'Auf Facebook teilen',
		'lang_sharegoogleplus' => 'Auf Google Plus teilen',
		'lang_thismember' => 'Mitglied',
		'lang_thisguest' => 'Dieser Gast',
		'lang_wrotethosequ' => 'hat folgende Fragen gestellt',
		'lang_pointsforqu' => 'Punkte für Fragen',
		'lang_bestanswer' => 'Beste?',
		'lang_answer' => 'Antwort',
		'lang_answers' => 'Antworten',
		'lang_existsalready' => 'Frage existiert bereits! Bitte bem Original nachfragen.',
		'lang_yourquestions' => 'Ihre Fragen',
		'lang_search' => 'Suchen',
		'lang_mailorusername' => 'Benutzername oder E-Mail',
		'lang_password' => 'Passwort',
		'lang_rememberme' => 'Angemeldet bleiben',
		'lang_login' => 'Login',
		'lang_qufastanswer' => 'Ihre Frage wird demnächst beantwortet.',
		'lang_followlatest' => 'Frage folgen',
		'lang_commentanswer' => 'Bei Nachfragen bitte Antwort <b>kommentieren</b>',
		'lang_qudelete' => 'Diese Frage wird gelöscht.',
		'lang_writecomment' => 'Nachfragen bitte immer als Kommentar schreiben.',
		'lang_whatis' => 'Kyga.de ist eine Community von Experten, die Ihnen weiterhilft.',
		'lang_registerquickly' => 'Registrieren Sie sich bei uns in nur einer Minute',
		'lang_register' => 'Registrieren',
		'lang_forgot_link' => 'Passwort vergessen',
		'whatis' => 'Was ist',

	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
